Repository kserve/kserve, pull requests merged in 2019-05, with the labels that each got.

#61 KFServer & XGBoost Server
  docs/samples/xgboost/iris-input.json
  docs/samples/xgboost/xgboost.yaml
  python/.gitignore
  python/README.md
  python/kfserving/__init__.py
  python/kfserving/model.py
  python/kfserving/server.py
  python/kfserving/storage.py
  python/setup.py
  python/xgbserver/DOCKERFILE
  python/xgbserver/__main__.py
  python/xgbserver/model.py
Labels: approved, lgtm, size/L

#63 Refactors xgbserver and kfserver to separate pypi folders
  python/kfserving/README.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/model.py
  python/kfserving/kfserving/server.py
  python/kfserving/kfserving/storage.py
  python/kfserving/setup.py
  python/xgbserver/README.md
  python/xgbserver/setup.py
  python/xgbserver/xgbserver/__init__.py
  python/xgbserver/xgbserver/__main__.py
  python/xgbserver/xgbserver/model.py
Labels: approved, lgtm, size/M

#62 Includes Data Plane Architecture Diagram
  docs/README.md
  docs/diagrams/dataplane.drawio
  docs/diagrams/dataplane.jpg
Labels: approved, lgtm, size/S

#66 Fix default tensorflow image
  pkg/apis/serving/v1alpha1/kfservice_defaults.go
Labels: approved, lgtm, size/S

#70 Local development guide for kfserving and xgboost servers
  python/kfserving/README.md
  python/xgbserver/README.md
Labels: approved, lgtm, size/M

#69 Doc modifications
  README.md
  docs/README.md
  docs/control-plane.md
  docs/data-plane.md
Labels: approved, lgtm, size/S

#67 Add Developer guide for KFServing
  docs/DEVELOPER_GUIDE.md
  test/README.md
Labels: approved, lgtm, size/L

#65 Introduce KO for fast development iteration
  .gitignore
  Makefile
  config/manager/manager.yaml
  config/manager/service.yaml
  config/overlays/development/manager_image_patch.yaml
  image_patch_dev.sh
Labels: approved, lgtm, size/M

#64 Reconcile labels and annotations for configuration/route
  pkg/reconciler/ksvc/reconciler.go
  pkg/reconciler/ksvc/reconciler_test.go
Labels: approved, lgtm, size/M

#71 Added pod labels to RevisionTemplate specs and retooled configuration…
  config/default/kustomization.yaml
  docs/DEVELOPER_GUIDE.md
  image_patch_dev.sh
  pkg/apis/serving/v1alpha1/kfservice_defaults_test.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/frameworks/tensorflow/tensorflow_serving.go
  pkg/reconciler/ksvc/reconciler_test.go
  pkg/reconciler/ksvc/resources/knative_configuration.go
  pkg/reconciler/ksvc/resources/knative_configuration_test.go
Labels: approved, lgtm, size/L

#74 Setup prow for kfserving
  pkg/reconciler/ksvc/reconciler_test.go
  prow_config.yaml
  test/scripts/build-kfserving.sh
  test/scripts/run-tests.sh
  test/scripts/unit-test.sh
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/releasing/main.jsonnet
  test/workflows/environments/releasing/params.libsonnet
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: approved, lgtm, size/XXL

#77 Cleans up stale OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#76 Moved Custom sample to the samples directory
  docs/samples/custom.yaml
Labels: approved, lgtm, size/XS

#78 Remove DEPRECATED RevisionTemplate
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/reconciler/ksvc/reconciler_test.go
  pkg/reconciler/ksvc/resources/knative_configuration.go
  pkg/reconciler/ksvc/resources/knative_configuration_test.go
Labels: approved, lgtm, size/S

#75 Sklearn server
  docs/samples/sklearn/README.md
  docs/samples/sklearn/model.joblib
  python/sklearnserver/DOCKERFILE
  python/sklearnserver/README.md
  python/sklearnserver/setup.py
  python/sklearnserver/sklearnserver/__init__.py
  python/sklearnserver/sklearnserver/__main__.py
  python/sklearnserver/sklearnserver/model.py
Labels: approved, lgtm, size/L

#81 Revert "Remove DEPRECATED RevisionTemplate (#78)"
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/reconciler/ksvc/reconciler_test.go
  pkg/reconciler/ksvc/resources/knative_configuration.go
  pkg/reconciler/ksvc/resources/knative_configuration_test.go
Labels: approved, lgtm, size/S

#73 Allow Seldon and TFServing Protocols on Python KFServer
  .gitignore
  python/kfserving/Makefile
  python/kfserving/README.md
  python/kfserving/kfserving/model.py
  python/kfserving/kfserving/protocols/request_handler.py
  python/kfserving/kfserving/protocols/seldon_http.py
  python/kfserving/kfserving/protocols/tensorflow_http.py
  python/kfserving/kfserving/server.py
  python/kfserving/kfserving/storage.py
  python/kfserving/kfserving/test_server.py
  python/kfserving/setup.py
  python/xgbserver/Makefile
  python/xgbserver/README.md
  python/xgbserver/setup.py
  python/xgbserver/xgbserver/__init__.py
  python/xgbserver/xgbserver/model.py
  python/xgbserver/xgbserver/test_model.py
Labels: approved, lgtm, size/XL

#80 Includes GPU autoscaling as part of README charter
  README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorflow/input.json
  docs/samples/tensorflow/tensorflow.yaml
Labels: approved, lgtm, size/M

#88 Added PR and Issue template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/M

#92 Made python kfserving.storage return uri if local path exists
  docs/samples/sklearn/README.md
  python/kfserving/README.md
  python/kfserving/kfserving/storage.py
  python/kfserving/kfserving/test_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#93 Adds Animesh as an Approver
  OWNERS
Labels: approved, lgtm, size/XS

#95 Make deploy and deploy-dev rule of Makefile work
  Makefile
  config/default/crds/serving_v1alpha1_kfservice.yaml
  config/default/kustomization.yaml
  config/default/manager/manager.yaml
  config/default/manager/service.yaml
  config/default/rbac/auth_proxy_role.yaml
  config/default/rbac/auth_proxy_role_binding.yaml
  config/default/rbac/auth_proxy_service.yaml
  config/default/rbac/rbac_role.yaml
  config/default/rbac/rbac_role_binding.yaml
  image_patch_dev.sh
Labels: approved, lgtm, size/M

#96 Fix test error caused by crds dir changed
  pkg/apis/serving/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/kfservice/kfservice_controller_suite_test.go
  pkg/reconciler/ksvc/ksvc_suite_test.go
  prow_config.yaml
Labels: approved, lgtm, size/XS

#98 Fix python sklearn test cases with the correct model_dir
  python/sklearnserver/sklearnserver/test_model.py
Labels: approved, lgtm, needs-ok-to-test, size/XS

#100 Developer instruction fixes
  README.md
  cmd/manager/main.go
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/M

#102 Fixes an old reference to kubeflow-system
  pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#103 Disables istio-injection in the namespace
  config/default/manager/service.yaml
Labels: approved, lgtm, size/XS

#104 Removes kfserving prefix from Kustomize and explicitly applies it to all resources
  config/default/kustomization.yaml
  config/default/manager/manager.yaml
  config/default/manager/service.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/default/rbac/auth_proxy_role.yaml
  config/default/rbac/auth_proxy_role_binding.yaml
  config/default/rbac/auth_proxy_service.yaml
  image_patch_dev.sh
Labels: approved, lgtm, size/M

#101 #55, Moves trafficPercent up to KFService.spec and unifies ModelSpec
  config/default/crds/serving_v1alpha1_kfservice.yaml
  docs/control-plane.md
  docs/samples/canary.yaml
  docs/samples/pinned.yaml
  pkg/apis/serving/v1alpha1/kfservice_defaults.go
  pkg/apis/serving/v1alpha1/kfservice_defaults_test.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/kfservice_types_test.go
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/reconciler/ksvc/resources/knative_configuration_test.go
  pkg/reconciler/ksvc/resources/knative_route.go
  pkg/reconciler/ksvc/resources/knative_route_test.go
Labels: approved, lgtm, size/L

#99 Adds release for automated GitOps triggered image builds for KFServing
  config/default/manager_image_patch.yaml
  release/README.md
  release/cloud-build-configs/kfserving-controller.cloud-build.yaml
Labels: approved, lgtm, size/S

#110 Implements release process improvements and defaulting framework behavior.
  docs/RELEASE_PROCESS.md
  pkg/apis/serving/v1alpha1/kfservice_defaults_test.go
  pkg/apis/serving/v1alpha1/kfservice_framework_scikit.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorflow.go
  pkg/apis/serving/v1alpha1/kfservice_framework_xgboost.go
  pkg/reconciler/ksvc/reconciler_test.go
  pkg/reconciler/ksvc/resources/knative_configuration.go
  pkg/reconciler/ksvc/resources/knative_configuration_test.go
  pkg/reconciler/ksvc/resources/knative_route.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  release/README.md
  release/cloud-build-configs/kfserving-controller.cloud-build.yaml
Labels: approved, lgtm, size/L

#118 Cleaned up samples. Deleted GPU sample until GPUs are functional
  docs/samples/custom.yaml
  docs/samples/resource-requests.yaml
  docs/samples/rollouts/canary.yaml
  docs/samples/rollouts/pinned.yaml
  docs/samples/tensorflow.yaml
Labels: approved, lgtm, size/M

#124 update developer guide to correct file path
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#116 Added the python model download methods for S3 and GCS.
  python/kfserving/README.md
  python/kfserving/kfserving/storage.py
  python/kfserving/kfserving/test_storage.py
  python/kfserving/setup.py
  python/sklearn.Dockerfile
  python/xgb.Dockerfile
Labels: approved, lgtm, ok-to-test, size/M

#106 Adds shortname and printer columns for KFServices
  config/default/crds/serving_v1alpha1_kfservice.yaml
  docs/control-plane.md
  docs/samples/custom/custom.yaml
  pkg/apis/serving/v1alpha1/kfservice_status.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/kfservice_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/kfservice/kfservice_controller_test.go
Labels: approved, lgtm, size/L

#128 Use klog for kfserving
  pkg/apis/serving/v1alpha1/kfservice_framework.go
  pkg/apis/serving/v1alpha1/v1alpha1_suite_test.go
  pkg/controller/kfservice/kfservice_controller_suite_test.go
Labels: approved, lgtm, size/S

#112 Add KFServing TF mnist S3 saved model example
  docs/samples/s3/README.md
  docs/samples/s3/input.json
  docs/samples/s3/s3_secret.yaml
  docs/samples/s3/tensorflow_s3.yaml
Labels: approved, lgtm, size/L

#131 Add correct URLs for sklearn and xgboost
  docs/samples/sklearn/sklearn.yaml
  docs/samples/xgboost/xgboost.yaml
  python/sklearn.Dockerfile
  python/xgb.Dockerfile
Labels: approved, lgtm, size/S

#130 Cleans up rogue files in top level directory
  Makefile
  hack/image_patch_dev.sh
  model.bst
Labels: approved, lgtm, size/XS
