Repository kserve/kserve, pull requests merged in 2019-07, with the labels that each got.

#211 Add hougang as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#212 adds support for anonymous azure blobs
  docs/samples/pytorch/README.md
  docs/samples/sklearn/README.md
  docs/samples/xgboost/README.md
  pkg/apis/serving/v1alpha1/kfservice_framework_pytorch.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt_test.go
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  python/kfserving/README.md
  python/kfserving/kfserving/storage.py
  python/kfserving/kfserving/test_storage.py
  python/kfserving/setup.py
  python/pytorchserver/README.md
  python/sklearnserver/README.md
  python/xgbserver/README.md
Labels: approved, lgtm, size/L

#215 invoke credentials builder from model initializer
  pkg/controller/kfservice/resources/credentials/service_account_credentials.go
  pkg/controller/kfservice/resources/credentials/service_account_credentials_test.go
  pkg/controller/kfservice/resources/knative/configuration.go
  pkg/webhook/admission/deployment/model_initializer_injector.go
  pkg/webhook/admission/deployment/model_initializer_injector_test.go
  pkg/webhook/admission/deployment/mutator.go
  pkg/webhook/admission/deployment/suite_test.go
Labels: approved, lgtm, size/L

#210 Generated v0.1.0 release
  README.md
  hack/generate-install.sh
  install/v0.1.0/kfserving.yaml
Labels: approved, lgtm, size/XL

#173 Updates the Roadmap for Q2/Q3
  ROADMAP.md
Labels: approved, lgtm, size/M

#224 fix one problem in new kustomize 3.0.0
  hack/image_patch_dev.sh
Labels: approved, lgtm, size/XS

#216 download_local should symlink if outdir is set
  python/kfserving/kfserving/storage.py
Labels: approved, lgtm, size/S

#204 Add pb2internal unit tests for TF2OpenAPI
  tools/tf2openapi/Makefile
  tools/tf2openapi/cmd/main.go
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfmetagraph_test.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsavedmodel_test.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tfsignaturedef_test.go
  tools/tf2openapi/types/tftensor.go
  tools/tf2openapi/types/tftensor_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#227 Add pytorchserver image in kfservice-config
  config/default/configmap/kfservice.yaml
  install/v0.1.0/kfserving.yaml
Labels: approved, lgtm, size/M

#228 make model initializer injector idempotent
  pkg/webhook/admission/deployment/model_initializer_injector.go
  pkg/webhook/admission/deployment/model_initializer_injector_test.go
Labels: approved, lgtm, size/M

#220 Tf2OpenAPI: Add CLI documentation
  Gopkg.lock
  Gopkg.toml
  tools/tf2openapi/README.md
  tools/tf2openapi/cmd/main.go
Labels: approved, lgtm, ok-to-test, size/M

#232 Remove install from Makefile
  Makefile
Labels: approved, cla/yes, lgtm, size/XS

#230 minor enhancements to roadmap
  ROADMAP.md
Labels: approved, lgtm, size/S

#239 work out presubmit test problem
  test/workflows/app.yaml
Labels: approved, lgtm, size/XS

#203 Add Autoscaling example
  docs/samples/autoscaling/README.md
  docs/samples/autoscaling/autoscale.yaml
  docs/samples/autoscaling/autoscale_custom.yaml
  docs/samples/autoscaling/autoscale_gpu.yaml
  docs/samples/autoscaling/scaling_debug.png
  docs/samples/autoscaling/scaling_debug_qps.png
  docs/samples/explanation/income/.ipynb_checkpoints/Untitled-checkpoint.ipynb
Labels: approved, lgtm, size/L

#241 add cmpopts dependency
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
Labels: approved, lgtm, size/XL

#207 Use cmp to make it easy to see what is broken in kfservice_controller_test
  pkg/controller/kfservice/kfservice_controller_test.go
Labels: approved, lgtm, size/S

#244 Add model initializer config
  cmd/spec-gen/main.go
  config/default/configmap/kfservice.yaml
  config/overlays/development/kustomization.yaml
  pkg/webhook/admission/deployment/model_initializer_injector.go
  pkg/webhook/admission/deployment/model_initializer_injector_test.go
  pkg/webhook/admission/deployment/mutator.go
Labels: approved, lgtm, size/L

#214 TF2OpenAPI: Generate OpenAPI from internal models
  tools/tf2openapi/README.md
  tools/tf2openapi/cmd/main.go
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/generator/tensorflow_serving_protocol.go
  tools/tf2openapi/types/tfdtype.go
  tools/tf2openapi/types/tfdtype_test.go
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfmetagraph_test.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsavedmodel_test.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tfsignaturedef_test.go
  tools/tf2openapi/types/tftensor.go
  tools/tf2openapi/types/tftensor_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#185 Created Cloud Build Triggers for automated image building.
  Makefile
  executor.Dockerfile
  hack/generate-cloudbuild-triggers.sh
  python/xgbserver/README.md
  release/RELEASE_PROCESS.md
  release/triggers/alibi-explainer.yaml
  release/triggers/executor.yaml
  release/triggers/kfserving-controller.yaml
  release/triggers/model-initalizer.yaml
  release/triggers/pytorch.yaml
  release/triggers/sklearnserver.yaml
  release/triggers/xgbserver.yaml
  test/scripts/build-kfserving-executor.sh
Labels: approved, lgtm, size/L

#254 Remove NVCR.io workaround
  docs/samples/tensorrt/README.md
Labels: approved, lgtm, size/XS

#248 More TF2OpenAPI Unit Tests
  pkg/utils/types.go
  pkg/utils/types_test.go
  tools/tf2openapi/Makefile
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/generator/generate_test.go
  tools/tf2openapi/generator/testdata/TestColFmtMultipleTensors.golden.json
  tools/tf2openapi/generator/testdata/TestColFmtMultipleTensors.pb
  tools/tf2openapi/generator/testdata/TestColFmtMultipleTensorsReq.json
  tools/tf2openapi/generator/testdata/TestColFmtScalar.golden.json
  tools/tf2openapi/generator/testdata/TestColFmtScalar.pb
  tools/tf2openapi/generator/testdata/TestColFmtScalarReq.json
  tools/tf2openapi/generator/testdata/TestColFmtSingleTensor.golden.json
  tools/tf2openapi/generator/testdata/TestColFmtSingleTensor.pb
  tools/tf2openapi/generator/testdata/TestColFmtSingleTensorReq.json
  tools/tf2openapi/generator/testdata/TestRowFmtMultipleTensors.golden.json
  tools/tf2openapi/generator/testdata/TestRowFmtMultipleTensors.pb
  tools/tf2openapi/generator/testdata/TestRowFmtMultipleTensorsReq.json
  tools/tf2openapi/generator/testdata/TestRowFmtSingleTensor.golden.json
  tools/tf2openapi/generator/testdata/TestRowFmtSingleTensor.pb
  tools/tf2openapi/generator/testdata/TestRowFmtSingleTensorReq.json
  tools/tf2openapi/types/tfmetagraph_test.go
  tools/tf2openapi/types/tfsavedmodel_test.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tfsignaturedef_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#247 TF2OpenAPI E2E Tests
  tools/tf2openapi/Makefile
  tools/tf2openapi/cmd/e2e_test.go
  tools/tf2openapi/cmd/main.go
  tools/tf2openapi/cmd/testdata/TestCensus.golden.json
  tools/tf2openapi/cmd/testdata/TestCensus.pb
  tools/tf2openapi/cmd/testdata/TestCustomFlags.golden.json
  tools/tf2openapi/cmd/testdata/TestCustomFlags.pb
  tools/tf2openapi/cmd/testdata/TestFlowers.golden.json
  tools/tf2openapi/cmd/testdata/TestFlowers.pb
  tools/tf2openapi/cmd/testdata/TestFlowers2.golden.json
  tools/tf2openapi/cmd/testdata/TestInvalidSavedModel.pb
  tools/tf2openapi/cmd/testdata/TestPropagateOpenAPIGenerationError.pb
Labels: approved, lgtm, ok-to-test, size/L

#257 Vendor request validator for TF2OpenAPI tests
  Gopkg.lock
  vendor/github.com/getkin/kin-openapi/openapi3filter/authentication_input.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/errors.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/internal.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/options.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/req_resp_decoder.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/router.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/validate_request.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/validate_request_input.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/validate_response.go
  vendor/github.com/getkin/kin-openapi/openapi3filter/validate_response_input.go
  vendor/github.com/getkin/kin-openapi/pathpattern/node.go
Labels: approved, lgtm, ok-to-test, size/XXL

#262 TF2OpenAPI Dockerfile + CloudBuild trigger
  hack/generate-cloudbuild-triggers.sh
  release/triggers/tf2openapi.yaml
  tools/tf2openapi/Dockerfile
Labels: approved, lgtm, needs-ok-to-test, size/M

#261 TF2OpenAPI: Complete openapi
  tools/tf2openapi/cmd/e2e_test.go
  tools/tf2openapi/cmd/testdata/TestCensus.golden.json
  tools/tf2openapi/cmd/testdata/TestCustomFlags.golden.json
  tools/tf2openapi/cmd/testdata/TestCustomFlags.pb
  tools/tf2openapi/cmd/testdata/TestFlowers.golden.json
  tools/tf2openapi/cmd/testdata/TestFlowers2.golden.json
  tools/tf2openapi/generator/generate_test.go
  tools/tf2openapi/generator/tensorflow_serving_protocol.go
  tools/tf2openapi/generator/testdata/TestColFmtMultipleTensors.golden.json
  tools/tf2openapi/generator/testdata/TestColFmtScalar.golden.json
  tools/tf2openapi/generator/testdata/TestColFmtSingleTensor.golden.json
  tools/tf2openapi/generator/testdata/TestRowFmtMultipleTensors.golden.json
  tools/tf2openapi/generator/testdata/TestRowFmtSingleTensor.golden.json
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfmetagraph_test.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsavedmodel_test.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tfsignaturedef_test.go
  tools/tf2openapi/types/tftensor.go
  tools/tf2openapi/types/tftensor_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#242 Allow all annotations to be set except the disallowed list
  pkg/controller/kfservice/resources/knative/configuration.go
  pkg/controller/kfservice/resources/knative/configuration_test.go
  pkg/controller/kfservice/resources/knative/route.go
  pkg/controller/kfservice/resources/knative/route_test.go
  pkg/utils/types_test.go
Labels: approved, lgtm, ok-to-test, size/L

#267 fix some typos
  docs/samples/pytorch/README.md
  docs/samples/xgboost/README.md
  python/pytorchserver/README.md
  python/sklearnserver/README.md
  python/xgbserver/README.md
Labels: approved, lgtm, size/S

#266 add requirements.txt for explainer
  docs/samples/explanation/income/requirements.txt
Labels: approved, lgtm, needs-ok-to-test, size/XS

#274 Trigger CloudBuild with every new tag
  release/triggers/alibi-explainer.yaml
  release/triggers/executor.yaml
  release/triggers/kfserving-controller.yaml
  release/triggers/model-initalizer.yaml
  release/triggers/pytorch.yaml
  release/triggers/sklearnserver.yaml
  release/triggers/tf2openapi.yaml
  release/triggers/xgbserver.yaml
Labels: approved, lgtm, needs-ok-to-test, size/M

#275 Fix Docker Build Context for Executor
  release/triggers/executor.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS
