Repository kserve/kserve, pull requests merged in 2019-10, with the labels that each got.

#370 add rollout api for SDK
  docs/samples/client/kfserving_sdk_sample.ipynb
  python/kfserving/docs/KFServingClient.md
  python/kfserving/kfserving/api/kf_serving_client.py
Labels: approved, lgtm, size/L

#390 add optional param
  python/kfserving/kfserving/api/kf_serving_client.py
Labels: approved, lgtm, size/S

#392 Cleanly uninstall kfserving in make undeploy and undeploy-dev
  Makefile
Labels: approved, lgtm, needs-ok-to-test, size/XS

#395 Set KFservice default timeout to lower value
  pkg/constants/constants.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#388 update endpoint status
  config/default/crds/serving_v1alpha2_kfservice.yaml
  pkg/apis/serving/v1alpha2/kfservice_status.go
  pkg/apis/serving/v1alpha2/kfservice_status_test.go
  pkg/apis/serving/v1alpha2/kfservice_types.go
  pkg/apis/serving/v1alpha2/kfservice_types_test.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/resources/knative/route_test.go
  pkg/controller/kfservice/resources/knative/service_test.go
Labels: approved, lgtm, size/XL

#397 Fixes issues with Validation not applying to transformers/explainers and unified predictor concept with explainer/transformer
  config/default/configmap/kfservice.yaml
  docs/apis/README.md
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/framework.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/kfservice_framework_pytorch.go
  pkg/apis/serving/v1alpha2/kfservice_framework_tensorrt.go
  pkg/apis/serving/v1alpha2/kfservice_framework_tensorrt_test.go
  pkg/apis/serving/v1alpha2/kfservice_validation.go
  pkg/apis/serving/v1alpha2/kfservice_validation_test.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/apis/serving/v1alpha2/transformer_custom.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/resources/knative/service.go
  pkg/controller/kfservice/resources/knative/service_test.go
Labels: approved, lgtm, size/XL

#400 Migrated to PodMutator from DeploymentMutator to avoid blocking k8s d…
  pkg/constants/constants.go
  pkg/webhook/admission/deployment/storage_initializer_injector_test.go
  pkg/webhook/admission/pod/accelerator_injector.go
  pkg/webhook/admission/pod/accelerator_injector_test.go
  pkg/webhook/admission/pod/mutator.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  pkg/webhook/admission/pod/suite_test.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/XXL

#401 Tweaks README to fix typo and be more visible
  README.md
Labels: approved, lgtm, size/S

#393 Update Alibi Anchor Text Example
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/explanation/alibi/moviesentiment/moviesentiment2.yaml
  docs/samples/explanation/alibi/moviesentiment/train.py
  python/alibiexplainer/setup.py
Labels: approved, lgtm, size/L

#410 Fix url path in the example
  docs/samples/pytorch/README.md
  docs/samples/sklearn/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, size/S

#409 Pipe patch
  README.md
  docs/samples/pipelines/sample-tf-pipeline.py
Labels: approved, lgtm, size/M

#406 Refactor ExplainerSpec for better validation
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/predictor.go
Labels: approved, lgtm, ok-to-test, size/M

#420 Changes to add a VirtualService for the v1 dataplane
  cmd/manager/main.go
  config/default/configmap/kfservice.yaml
  config/default/crds/serving_v1alpha2_kfservice.yaml
  config/default/rbac/rbac_role.yaml
  pkg/apis/serving/v1alpha2/kfservice_status.go
  pkg/apis/serving/v1alpha2/kfservice_status_test.go
  pkg/apis/serving/v1alpha2/kfservice_types.go
  pkg/apis/serving/v1alpha2/kfservice_types_test.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/istio/virtualservice_reconciler.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
  pkg/controller/kfservice/reconcilers/knative/service_reconciler.go
  pkg/controller/kfservice/resources/istio/virtualservice.go
  pkg/controller/kfservice/resources/knative/route.go
  pkg/controller/kfservice/resources/knative/route_test.go
  pkg/testing/envtest_setup.go
  test/crds/istio_virtualservice.yaml
Labels: approved, lgtm, size/XXL

#422 Add default/allowed ImageVersion to ConfigMap
  Makefile
  config/default/configmap/inferenceservice.yaml
  config/default/crds/serving_v1alpha2_inferenceservice.yaml
  docs/apis/README.md
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorflow_test.go
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_defaults.go
  pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
  pkg/webhook/admission/inferenceservice/inferenceservice_defaulter.go
  pkg/webhook/admission/inferenceservice/inferenceservice_validator.go
Labels: approved, lgtm, size/XXL

#425 enhance sdk due to json path changed
  python/kfserving/kfserving/api/kf_serving_watch.py
  python/kfserving/setup.py
Labels: approved, lgtm, size/XS

#408 Generated v0.2.0 release
  README.md
  config/default/configmap/inferenceservice.yaml
  hack/generate-install.sh
  install/0.1.0/kfserving.yaml
  install/0.2.0/kfserving.yaml
Labels: approved, lgtm, size/XL

#383 Adding E2E test for KFServing
  Makefile
  config/overlays/test/kustomization.yaml
  config/overlays/test/manager_image_patch.yaml
  python/kfserving/requirements.txt
  test/e2e/test_tensorflow_inference_service.py
  test/e2e/utils.py
  test/scripts/create-cluster.sh
  test/scripts/delete-cluster.sh
  test/scripts/run-e2e-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#438 Fix SERVICE_HOSTNAME in the example
  docs/samples/pytorch/README.md
  docs/samples/sklearn/README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, size/S

#439 Fix missing alibi key in explainers configmap
  config/default/configmap/inferenceservice.yaml
  install/0.2.0/kfserving.yaml
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
Labels: approved, lgtm, size/L

#424 Improved docs for v0.2 release.
  README.md
  docs/README.md
  docs/control-plane.md
  docs/diagrams/dataplane.drawio
  docs/diagrams/dataplane.jpg
  docs/diagrams/kfserving.png
Labels: approved, lgtm, size/L

#442 Detail RuntimeVersion error message
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
Labels: approved, lgtm, size/S

#444 minor pipeline fixes
  README.md
  docs/samples/pipelines/sample-custom-model.py
  docs/samples/pipelines/sample-tf-pipeline.py
Labels: approved, lgtm, size/XS

#448 Fix sample wrong Host name
  docs/samples/explanation/alibi/imagenet/imagenet.yaml
  docs/samples/explanation/alibi/imagenet/test_imagenet.py
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/income/income.yaml
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/explanation/alibi/moviesentiment/kfserving_text_explainer.ipynb
Labels: approved, lgtm, size/S

#446 Explainer virtual service cannot work
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
Labels: approved, lgtm, size/L

#449 Fix hardcode k8s domain name
  pkg/constants/constants.go
Labels: approved, lgtm, size/XS

#450 Fix update inferenceservice status error case
  pkg/controller/inferenceservice/controller.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
Labels: approved, lgtm, size/S

#437 update docs related sdk
  README.md
  python/kfserving/README.md
  python/kfserving/docs/KFServingClient.md
  python/kfserving/kfserving/api/kf_serving_client.py
  test/e2e/test_tensorflow_inference_service.py
  test/e2e/utils.py
Labels: approved, lgtm, size/M

#459 fix one e2e test problem
  test/e2e/utils.py
Labels: approved, lgtm, size/XS

#443 Fix anchor tabular explanation serialization
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
Labels: approved, lgtm, size/XS

#457 Enhance hardcode namespace in SDK sample
  docs/samples/client/kfserving_sdk_sample.ipynb
Labels: approved, lgtm, size/S

#464 update onnx to a version that supports the v1 url format
  config/default/configmap/inferenceservice.yaml
  docs/samples/onnx/README.md
  docs/samples/onnx/mosaic-onnx.ipynb
Labels: approved, lgtm, size/L

#463 Fix variable names where should be component instead of endpoint
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/inferenceservice_status.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/inferenceservice_types_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
Labels: approved, lgtm, size/L

#466 Get detailed logs for debugging if e2e timeout
  test/e2e/test_tensorflow_inference_service.py
  test/e2e/utils.py
Labels: approved, lgtm, size/M

#454 Container resource
  .gitignore
  Makefile
  config/default/configmap/inferenceservice.yaml
  hack/image_patch_dev.sh
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
  pkg/webhook/admission/pod/mutator.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: approved, lgtm, ok-to-test, size/L

#461 One knative service to one endpoint
  docs/samples/autoscaling/README.md
  docs/samples/rollouts/pinned.yaml
  pkg/apis/serving/v1alpha2/inferenceservice_status.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
Labels: approved, lgtm, size/L

#470 Fix service account field on S3 example
  docs/samples/s3/tensorflow_s3.yaml
Labels: approved, lgtm, size/XS

#468 add docs for pvc supporting
  docs/samples/pvc/README.md
  docs/samples/pvc/mnist-pvc.yaml
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  python/kfserving/README.md
Labels: approved, lgtm, size/M

#478 Downgrade istio and knative in e2e tests
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XS

#475 Specify inference server container name
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: approved, lgtm, size/M

#476 sample pipeline notebook
  docs/samples/pipelines/kfs-pipeline.ipynb
Labels: approved, lgtm, size/L

#487 Added configmap changes
  install/0.2.0/kfserving.yaml
Labels: approved, lgtm, size/S

#488 Ignores pods in mutator that are not managed by kfserving
  pkg/webhook/admission/pod/mutator.go
Labels: approved, lgtm, size/XS

#484 Order explainer config in container args
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
Labels: approved, lgtm, size/M

#491 Configure separate timeouts for Predictor, Transformer and Explainer
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
Labels: approved, lgtm, size/M

#482 Check whether the storage initilizer really download something
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#465 Adds virtualservice tests
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Labels: approved, lgtm, size/XL

#472 Inference Logger Types
  config/default/crds/serving_v1alpha2_inferenceservice.yaml
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#501 Change the default resource to be a map to be extensible in future
  pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/utils.go
Labels: approved, lgtm, ok-to-test, size/L
