Repository kserve/kserve, pull requests merged in 2019-12, with the labels that each got.

#579 Cut 0.2.2 release
  README.md
  config/default/configmap/inferenceservice.yaml
  hack/generate-install.sh
  install/0.2.2/kfserving.yaml
  pkg/constants/constants.go
  python/alibiexplainer/setup.py
  python/kfserving/setup.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/xgbserver/setup.py
Labels: approved, lgtm, size/XXL

#588 Fix docs typos
  docs/README.md
Labels: approved, lgtm, size/S

#560 Update sklearnserver to also accept pickle
  python/sklearnserver/README.md
  python/sklearnserver/sklearnserver/example_models/joblib/model.joblib
  python/sklearnserver/sklearnserver/example_models/pickle/model.pickle
  python/sklearnserver/sklearnserver/example_models/pkl/model.pkl
  python/sklearnserver/sklearnserver/model.py
  python/sklearnserver/sklearnserver/test_model.py
Labels: approved, lgtm, size/M

#587 Upgrade knative to v0.10.0 in CI tests
  test/scripts/create-cluster.sh
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/S

#582 Fix issue of invalid ClusterRoleBinding in developer mode
  Makefile
  hack/update-clusterrolebinding.sh
Labels: approved, lgtm, ok-to-test, size/M

#592 Use containerport to let knative listen on logger port
  cmd/logger/main.go
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
Labels: approved, lgtm, size/L

#593 correct shasum algorithm
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#598 Resovle CI SDK test problem
  test/scripts/run-e2e-tests.sh
  test/scripts/sdk-test.sh
Labels: approved, lgtm, size/M

#595 Tensorrt specified container port, which will not work with logger
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
Labels: approved, lgtm, size/S

#589 Added default amazon endpoint to support standard AWS endpoints by default (and public buckets)
  python/kfserving/kfserving/storage.py
Labels: approved, lgtm, ok-to-test, size/XS

#583 Support internal host routing and add example for inference with kafka event source
  Gopkg.lock
  config/default/crds/crd_status_condition_patch.yaml
  config/default/crds/serving_v1alpha2_inferenceservice.yaml
  docs/samples/kafka/README.md
  docs/samples/kafka/addressable-resolver.yaml
  docs/samples/kafka/image_transformer/__init__.py
  docs/samples/kafka/image_transformer/__main__.py
  docs/samples/kafka/image_transformer/image_transformer.py
  docs/samples/kafka/images/0.png
  docs/samples/kafka/images/diagram.png
  docs/samples/kafka/kafka-source.yaml
  docs/samples/kafka/minio.yaml
  docs/samples/kafka/mnist_kafka.yaml
  docs/samples/kafka/s3_secret.yaml
  docs/samples/kafka/setup.py
  docs/samples/kafka/transformer.Dockerfile
  docs/samples/kafka/values.yaml
  pkg/apis/serving/v1alpha2/inferenceservice_status.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/istio/virtualservice_reconciler.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
  python/kfserving/kfserving/handlers/http.py
Labels: approved, lgtm, size/XXL

#599 Fix links in KFServing Tensorflow sample
  docs/samples/onnx/README.md
  docs/samples/pytorch/README.md
  docs/samples/sklearn/README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, size/M

#573 enhance make deploy-dev to also include logger image
  .gitignore
  config/overlays/development/configmap/ko_resolve_logger
  config/overlays/development/kustomization.yaml
  docs/DEVELOPER_GUIDE.md
  hack/image_patch_dev.sh
Labels: approved, lgtm, size/S

#600 Upgrade openapi gen which is a subtask to upgrade to knative 0.10
  .gitignore
  Gopkg.lock
  Gopkg.toml
  hack/update-openapigen.sh
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/args/args.go
  vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
  vendor/k8s.io/kube-openapi/pkg/common/common.go
  vendor/k8s.io/kube-openapi/pkg/generators/api_linter.go
  vendor/k8s.io/kube-openapi/pkg/generators/config.go
  vendor/k8s.io/kube-openapi/pkg/generators/extension.go
  vendor/k8s.io/kube-openapi/pkg/generators/openapi.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/doc.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/names_match.go
  vendor/k8s.io/kube-openapi/pkg/generators/rules/omitempty_match_case.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/empty.go
  vendor/k8s.io/kube-openapi/pkg/util/sets/string.go
Labels: approved, lgtm, size/XXL

#615 Return application/json as content-type header
  python/kfserving/Makefile
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/test/test_server.py
Labels: approved, lgtm, ok-to-test, size/M

#616 Export LoggerRequest, Fix local logger README
  docs/samples/logger/local/README.md
  pkg/logger/server.go
  pkg/logger/types.go
  pkg/logger/worker.go
Labels: approved, lgtm, size/M

#608 Set queue proxy limit to 20% resource of main container
  pkg/controller/inferenceservice/resources/knative/service.go
Labels: approved, lgtm, size/XS

#617 Fix broken link in KFServing Autoscaling sample and typo in PVC sample
  docs/samples/autoscaling/README.md
  docs/samples/pvc/README.md
Labels: approved, lgtm, size/XS
