Repository kserve/kserve, pull requests merged in 2019-09, with the labels that each got.

#320 Convert predictor default/canary configurations to knative service
  config/default/rbac/rbac_role.yaml
  pkg/apis/serving/v1alpha2/kfservice_status.go
  pkg/apis/serving/v1alpha2/kfservice_status_test.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler_test.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
  pkg/controller/kfservice/reconcilers/knative/service_reconciler.go
  pkg/controller/kfservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/kfservice/resources/knative/configuration_test.go
  pkg/controller/kfservice/resources/knative/route.go
  pkg/controller/kfservice/resources/knative/route_test.go
  pkg/controller/kfservice/resources/knative/service.go
  pkg/controller/kfservice/resources/knative/service_test.go
  pkg/utils/utils_test.go
  test/crds/knative_service.yaml
Labels: approved, lgtm, size/XXL

#258 add ONNX support
  config/default/configmap/kfservice.yaml
  config/default/crds/serving_v1alpha2_kfservice.yaml
  docs/control-plane.md
  docs/samples/onnx/README.md
  docs/samples/onnx/assets/onnx_ml_pb2.py
  docs/samples/onnx/assets/predict_pb2.py
  docs/samples/onnx/image.jpg
  docs/samples/onnx/mosaic-onnx.ipynb
  docs/samples/onnx/onnx.yaml
  docs/samples/onnx/requirements.txt
  pkg/apis/serving/v1alpha2/framework.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/kfservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#333 Temporarily point to custom location for storage-initializer
  config/default/configmap/kfservice.yaml
Labels: approved, lgtm, size/XS

#319 add available images to configmap
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/kfservice_framework_pytorch.go
Labels: approved, lgtm, size/XS

#302 storage: Allow get s3 object with fully specified path
  python/.pylintrc
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_s3_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#329 Add transformer to control plane
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
  pkg/controller/kfservice/resources/knative/service.go
  pkg/controller/kfservice/resources/knative/service_test.go
  python/kfserving/kfserving/model.py
  python/kfserving/kfserving/protocols/seldon_http.py
  python/kfserving/kfserving/protocols/tensorflow_http.py
  python/kfserving/kfserving/server.py
  python/kfserving/kfserving/transformer.py
  python/kfserving/test/test_request_handler.py
  python/kfserving/test/test_server.py
Labels: approved, lgtm, size/XXL

#340 curating sample pipelines to expand on
  README.md
  docs/samples/explanation/income/train.py
  docs/samples/pipelines/sample-custom-model.py
  docs/samples/pipelines/sample-tf-pipeline.py
  docs/samples/pytorch/cifar10.py
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/alibiexplainer/explainer_wrapper.py
  python/kfserving/kfserving/api_client.py
  python/kfserving/kfserving/rest.py
Labels: approved, lgtm, size/L

#345 Fix always update knative service in reconcile thread
  pkg/controller/kfservice/reconcilers/knative/service_reconciler.go
  pkg/controller/kfservice/reconcilers/knative/service_reconciler_test.go
Labels: approved, lgtm, size/XS

#349 fix testing problem in building image steps
  test/scripts/build-python-image.sh
Labels: approved, lgtm, size/XS

#337 Add Tabular, Text and Image Model Explainers
  docs/samples/explanation/alibi/imagenet/Makefile
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/imagenet/cat-explanation.png
  docs/samples/explanation/alibi/imagenet/cat-prediction.png
  docs/samples/explanation/alibi/imagenet/imagenet.yaml
  docs/samples/explanation/alibi/imagenet/requirements.txt
  docs/samples/explanation/alibi/imagenet/test_imagenet.py
  docs/samples/explanation/alibi/imagenet/train_explainer.py
  docs/samples/explanation/alibi/income/Makefile
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/income/income.yaml
  docs/samples/explanation/alibi/income/requirements.txt
  docs/samples/explanation/alibi/income/train.py
  docs/samples/explanation/alibi/moviesentiment/Makefile
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/explanation/alibi/moviesentiment/moviesentiment.yaml
  docs/samples/explanation/alibi/moviesentiment/requirements.txt
  docs/samples/explanation/alibi/moviesentiment/train.py
  docs/samples/explanation/income/README.md
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/kfservice_defaults.go
  pkg/apis/serving/v1alpha2/kfservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler.go
  pkg/controller/kfservice/resources/knative/service.go
  pkg/controller/kfservice/resources/knative/service_test.go
  python/alibiexplainer.Dockerfile
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/alibiexplainer/anchor_images.py
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
  python/alibiexplainer/alibiexplainer/anchor_text.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/setup.py
  python/kfserving/kfserving/protocols/seldon_http.py
  python/kfserving/kfserving/server.py
Labels: approved, lgtm, size/XXL

#348 Update the Dockerfile to support ppc64le.
  Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#356 Adds build triggers against head. Images will be tagged ":latest"
  hack/generate-cloudbuild-triggers.sh
  release/triggers/latest/alibi-explainer.yaml
  release/triggers/latest/executor.yaml
  release/triggers/latest/kfserving-controller.yaml
  release/triggers/latest/pytorch.yaml
  release/triggers/latest/sklearnserver.yaml
  release/triggers/latest/storage-initalizer.yaml
  release/triggers/latest/tf2openapi.yaml
  release/triggers/latest/xgbserver.yaml
  release/triggers/tagged/alibi-explainer.yaml
  release/triggers/tagged/executor.yaml
  release/triggers/tagged/kfserving-controller.yaml
  release/triggers/tagged/pytorch.yaml
  release/triggers/tagged/sklearnserver.yaml
  release/triggers/tagged/storage-initalizer.yaml
  release/triggers/tagged/tf2openapi.yaml
  release/triggers/tagged/xgbserver.yaml
Labels: approved, lgtm, size/L

#355 Add text explainer notebook
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/explanation/alibi/moviesentiment/kfserving_text_explainer.ipynb
Labels: approved, lgtm, size/L

#354 Add transformer example
  docs/samples/transformer/image_transformer/README.md
  docs/samples/transformer/image_transformer/image_transformer.yaml
  docs/samples/transformer/image_transformer/image_transformer/__init__.py
  docs/samples/transformer/image_transformer/image_transformer/__main__.py
  docs/samples/transformer/image_transformer/image_transformer/image_transformer.py
  docs/samples/transformer/image_transformer/input.json
  docs/samples/transformer/image_transformer/kfserving_sdk_transformer.ipynb
  docs/samples/transformer/image_transformer/setup.py
  docs/samples/transformer/image_transformer/transformer.Dockerfile
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/resources/knative/service.go
  pkg/controller/kfservice/resources/knative/service_test.go
Labels: approved, lgtm, size/XL

#358 Added descriptions to cloudbuild triggers to show more cleanly in the UI
  release/triggers/latest/alibi-explainer.yaml
  release/triggers/latest/executor.yaml
  release/triggers/latest/kfserving-controller.yaml
  release/triggers/latest/pytorch.yaml
  release/triggers/latest/sklearnserver.yaml
  release/triggers/latest/storage-initalizer.yaml
  release/triggers/latest/tf2openapi.yaml
  release/triggers/latest/xgbserver.yaml
  release/triggers/tagged/alibi-explainer.yaml
  release/triggers/tagged/executor.yaml
  release/triggers/tagged/kfserving-controller.yaml
  release/triggers/tagged/pytorch.yaml
  release/triggers/tagged/sklearnserver.yaml
  release/triggers/tagged/storage-initalizer.yaml
  release/triggers/tagged/tf2openapi.yaml
  release/triggers/tagged/xgbserver.yaml
Labels: approved, lgtm, size/S

#352 Fix errors in sdk-test in presubmit tests
  python/kfserving/requirements.txt
  python/kfserving/test/test_v1alpha2_alibi_explain_spec.py
  python/kfserving/test/test_v1alpha2_explain_spec.py
  python/kfserving/test/test_v1alpha2_model_spec.py
  test/scripts/sdk-test.sh
Labels: approved, lgtm, size/L

#346 adding inital requirements checklist for kfserving to be integrated i…
  docs/guidelines/kubeflow_kfserving_requirements.md
Labels: approved, lgtm, size/M

#364 Fix some problems in transformer example
  docs/samples/transformer/image_transformer/README.md
Labels: approved, lgtm, size/XS

#357 adding repalce and promote APIs for kfserving sdk
  docs/samples/client/kfserving_sdk_sample.ipynb
  python/kfserving/docs/KFServingClient.md
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/test/test_kfservice_client.py
Labels: approved, lgtm, size/L

#368 Remove from api client
  python/kfserving/kfserving/api/kf_serving_client.py
Labels: approved, lgtm, size/XS

#367 Fix the link to how to install kubebuilder on test/README.md
  test/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#365 Remove a workaround in the update-openapigen.sh to run 'make test' on macOS
  hack/update-openapigen.sh
  pkg/apis/serving/v1alpha2/kfservice_framework_tensorrt_test.go
Labels: approved, lgtm, ok-to-test, size/M

#362 make connection to minio configurable
  python/kfserving/kfserving/storage.py
Labels: approved, lgtm, ok-to-test, size/S

#359 Update the Knative installation guide
  README.md
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/S

#375 Points to KFServing's StorageInitializer image
  config/default/configmap/kfservice.yaml
Labels: approved, lgtm, size/XS

#373 vendor in istio types
  Gopkg.lock
  vendor/knative.dev/pkg/apis/istio/common/v1alpha1/string.go
  vendor/knative.dev/pkg/apis/istio/register.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/destinationrule_types.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/doc.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/gateway_types.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/register.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/virtualservice_types.go
  vendor/knative.dev/pkg/apis/istio/v1alpha3/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#377 Update troubleshooting to avoid a storage-initializer injection failure
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#378 Update troubleshooting to avoid a storage-initializer injection failure (take2)
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#255 Updating docs
  docs/samples/pytorch/README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  test/crds/knative_route.yaml
Labels: approved, lgtm, size/S

#380 Filter directory keys when downloading models from S3 storage
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_s3_storage.py
Labels: approved, lgtm, size/S

#381 Generate KFService api docs
  Makefile
  README.md
  docs/apis/Dockerfile
  docs/apis/README.md
Labels: approved, lgtm, size/XXL
