Repository kserve/kserve, pull requests merged in 2019-08, with the labels that each got.

#245 add basic sdk api and sample notebook
  sdk/README.md
  sdk/docs/KFServingClient.md
  sdk/kfserving/__init__.py
  sdk/kfserving/api/__init__.py
  sdk/kfserving/api/kf_serving_client.py
  sdk/kfserving/constants/__init__.py
  sdk/kfserving/constants/constants.py
  sdk/kfserving/utils/__init__.py
  sdk/kfserving/utils/utils.py
  sdk/sample/kfserving_sdk_sample.ipynb
  sdk/test/test_kfservice_client.py
  test/scripts/sdk-test.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL

#237 Update Spec for Explainers
  config/default/crds/serving_v1alpha1_kfservice.yaml
  docs/samples/explanation/income/Makefile
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/openapi_generated.go
  pkg/apis/serving/v1alpha1/swagger.json
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#256 Update Alibi Explainer to load pre-trained explainer
  docs/samples/explanation/income/Makefile
  docs/samples/explanation/income/README.md
  docs/samples/explanation/income/train.py
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/alibiexplainer/explainer_wrapper.py
  python/alibiexplainer/setup.py
  python/kfserving/kfserving/server.py
Labels: approved, lgtm, size/L

#222 Add model initialization for CustomSpec
  pkg/apis/serving/v1alpha1/framework_custom.go
  pkg/constants/constants.go
  pkg/webhook/admission/deployment/model_initializer_injector.go
  pkg/webhook/admission/deployment/model_initializer_injector_test.go
Labels: approved, lgtm, ok-to-test, size/L

#253 Fix reconcile logic for canary spec
  pkg/apis/serving/v1alpha1/kfservice_status.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler.go
Labels: approved, lgtm, size/L

#279 allow user can set kube_config in sdk client
  sdk/docs/KFServingClient.md
  sdk/kfserving/api/kf_serving_client.py
Labels: approved, lgtm, size/S

#285 Adding ClearCondition fix
  pkg/apis/serving/v1alpha1/kfservice_status.go
  pkg/controller/kfservice/kfservice_controller_test.go
Labels: approved, lgtm, size/S

#286 Minor update on SDK verbiage
  README.md
  python/kfserving/README.md
Labels: approved, lgtm, size/S

#289 update kfservice status URL
  pkg/apis/serving/v1alpha1/kfservice_status.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/kfservice_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/kfservice/kfservice_controller_test.go
Labels: approved, lgtm, size/S

#293 Set default resource limits for KFService
  pkg/apis/serving/v1alpha2/framework.go
  pkg/apis/serving/v1alpha2/kfservice_defaults_test.go
Labels: approved, lgtm, size/S

#292 support creds for azure blobs
  config/default/configmap/kfservice.yaml
  docs/samples/azure/README.md
  pkg/controller/kfservice/resources/credentials/azure/azure_secret.go
  pkg/controller/kfservice/resources/credentials/azure/azure_secret_test.go
  pkg/controller/kfservice/resources/credentials/service_account_credentials.go
  pkg/controller/kfservice/resources/credentials/service_account_credentials_test.go
  python/kfserving/kfserving/storage.py
  python/kfserving/requirements.txt
  python/model-initializer.Dockerfile
Labels: approved, lgtm, size/L

#288 Add SDK API to create Creds
  python/kfserving/docs/KFServingClient.md
  python/kfserving/kfserving/api/creds_utils.py
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/constants/constants.py
  python/kfserving/test/aws_credentials
  python/kfserving/test/gcp_credentials.json
  python/kfserving/test/test_kfservice_client.py
  python/kfserving/test/test_set_creds.py
Labels: approved, lgtm, size/L

#304 fix pytouch build timeout issue in presubmit
  test/scripts/build-python-image.sh
Labels: approved, lgtm, size/XS

#307 add overall status for kubectl get cli
  config/default/crds/serving_v1alpha2_kfservice.yaml
  docs/DEVELOPER_GUIDE.md
  docs/samples/tensorflow/README.md
  pkg/apis/serving/v1alpha2/kfservice_types.go
Labels: approved, lgtm, size/S

#309 Add azure blob download tests
  docs/samples/azure/README.md
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_azure_storage.py
Labels: approved, lgtm, size/L

#300 V1alpha2 KFService Spec for predict, explain, transform
  cmd/spec-gen/main.go
  config/default/crds/serving_v1alpha2_kfservice.yaml
  pkg/apis/serving/v1alpha2/framework.go
  pkg/apis/serving/v1alpha2/kfservice_defaults.go
  pkg/apis/serving/v1alpha2/kfservice_defaults_test.go
  pkg/apis/serving/v1alpha2/kfservice_types.go
  pkg/apis/serving/v1alpha2/kfservice_types_test.go
  pkg/apis/serving/v1alpha2/kfservice_validation.go
  pkg/apis/serving/v1alpha2/kfservice_validation_test.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler_test.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
  pkg/controller/kfservice/resources/knative/configuration.go
  pkg/controller/kfservice/resources/knative/configuration_test.go
  pkg/controller/kfservice/resources/knative/route_test.go
Labels: approved, lgtm, size/XXL
