Repository kserve/kserve, pull requests merged in 2019-06, with the labels that each got.

#126 Enabled go lint.
  Makefile
  hack/.golint_failures
  hack/verify-golint.sh
Labels: approved, lgtm, size/L

#136 fix golint install message
  hack/verify-golint.sh
Labels: approved, lgtm, size/XS

#132 tensorflow canary example
  README.md
  docs/DEVELOPER_GUIDE.md
  docs/diagrams/kfserving.png
  docs/samples/tensorflow/README.md
  docs/samples/tensorflow/tensorflow-canary.yaml
  python/sklearnserver/model.joblib
  python/xgbserver/model.bst
Labels: approved, lgtm, size/L

#114 Add ConfigMap to allow configuring framework images and credential settings
  .gitignore
  config/default/configmap/kfservice.yaml
  config/default/kustomization.yaml
  config/default/rbac/rbac_role.yaml
  pkg/apis/serving/v1alpha1/kfservice_framework.go
  pkg/apis/serving/v1alpha1/kfservice_framework_custom.go
  pkg/apis/serving/v1alpha1/kfservice_framework_scikit.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorflow.go
  pkg/apis/serving/v1alpha1/kfservice_framework_xgboost.go
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/credentials/credentials_suite_test.go
  pkg/credentials/gcs/gcs_secret.go
  pkg/credentials/gcs/gcs_secret_test.go
  pkg/credentials/s3/s3_secret.go
  pkg/credentials/s3/s3_secret_test.go
  pkg/credentials/service_account_credentials.go
  pkg/credentials/service_account_credentials_test.go
  pkg/reconciler/knative/knative_configuration_reconciler.go
  pkg/reconciler/knative/knative_configuration_reconciler_test.go
  pkg/reconciler/knative/knative_route_reconciler.go
  pkg/reconciler/knative/knative_route_reconciler_test.go
  pkg/reconciler/knative/knative_suite_test.go
  pkg/reconciler/knative/resources/knative_configuration.go
  pkg/reconciler/knative/resources/knative_configuration_test.go
  pkg/reconciler/knative/resources/knative_route.go
  pkg/reconciler/knative/resources/knative_route_test.go
Labels: approved, lgtm, size/XL

#141 Cleans up README
  README.md
Labels: approved, lgtm, size/S

#146 Add a note about scale to zero in the dev guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#150 Fix test error by golint
  Makefile
  prow_config.yaml
  test/scripts/unit-test.sh
Labels: approved, lgtm, size/S

#149 Specify kfserving-related WebhookConfigName
  pkg/constants/constants.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/S

#154 fix bad link and typo in docs
  README.md
  python/sklearnserver/README.md
Labels: approved, lgtm, size/XS

#138 Executor with Preprocess, Predict and Postprocess
  Dockerfile.executor
  Gopkg.lock
  Makefile
  cmd/executor/main.go
  pkg/apis/serving/v1alpha1/framework.go
  pkg/executor/executor.go
  pkg/executor/executor_test.go
  pkg/executor/postprocess.go
  pkg/executor/predict.go
  pkg/executor/preprocess.go
  vendor/golang.org/x/net/http2/h2c/h2c.go
Labels: approved, lgtm, size/XL

#166 Remove data plane doc
  docs/README.md
  docs/data-plane.md
Labels: approved, lgtm, size/M

#164 Add types
  tools/tf2openapi/README.md
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tftensor.go
Labels: approved, lgtm, ok-to-test, size/L

#134 add initial support for tensorrt
  README.md
  config/default/configmap/kfservice.yaml
  config/default/crds/serving_v1alpha1_kfservice.yaml
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  docs/samples/tensorrt/tensorrt.yaml
  pkg/apis/serving/v1alpha1/framework.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt_test.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#169 Revert "Add types (#164)"
  tools/tf2openapi/README.md
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tftensor.go
Labels: approved, lgtm, ok-to-test, size/L

#171 Fix gcs secret volume mount path
  pkg/controller/kfservice/resources/credentials/gcs/gcs_secret.go
  pkg/controller/kfservice/resources/credentials/gcs/gcs_secret_test.go
  pkg/controller/kfservice/resources/credentials/service_account_credentials.go
  pkg/controller/kfservice/resources/credentials/service_account_credentials_test.go
Labels: approved, lgtm, size/S

#152 Add Model Explainer Server
  docs/samples/explanation/income/.ipynb_checkpoints/Untitled-checkpoint.ipynb
  docs/samples/explanation/income/Makefile
  docs/samples/explanation/income/README.md
  docs/samples/explanation/income/train.py
  python/alibiexplainer/Makefile
  python/alibiexplainer/README.md
  python/alibiexplainer/alibiexplainer/__init__.py
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/alibiexplainer/explainer_method.py
  python/alibiexplainer/setup.py
  python/kfserving/kfserving/model.py
  python/kfserving/kfserving/protocols/seldon_http.py
  python/kfserving/kfserving/protocols/util.py
  python/kfserving/kfserving/server.py
  python/kfserving/kfserving/test_server.py
Labels: approved, lgtm, size/XL

#174 Linked to working group on front page README
  README.md
Labels: size/XS

#176 make tensorflow protocol default
  python/kfserving/kfserving/server.py
Labels: approved, lgtm, size/XS

#145 Propagate configuration/route conditions to KFService status object
  Makefile
  config/default/crds/crd_status_condition_patch.yaml
  config/default/crds/kustomization.yaml
  config/default/crds/serving_v1alpha1_kfservice.yaml
  config/default/kustomization.yaml
  config/default/manager/manager.yaml
  pkg/apis/serving/v1alpha1/kfservice_status.go
  pkg/apis/serving/v1alpha1/kfservice_status_test.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler_test.go
  pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
  pkg/testing/be_sematic_equal_matcher.go
  pkg/webhook/third_party/admission.go
Labels: approved, lgtm, size/XL

#180 Apply pylint testing for kfserving python code
  python/.pylintrc
  python/alibiexplainer/alibiexplainer/__init__.py
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/setup.py
  python/kfserving/kfserving/protocols/seldon_http.py
  python/kfserving/kfserving/protocols/tensorflow_http.py
  python/kfserving/kfserving/protocols/util.py
  python/kfserving/kfserving/storage.py
  python/kfserving/kfserving/test_server.py
  python/kfserving/kfserving/test_storage.py
  python/sklearnserver/setup.py
  python/sklearnserver/sklearnserver/model.py
  python/sklearnserver/sklearnserver/test_model.py
  python/xgbserver/setup.py
  python/xgbserver/xgbserver/__main__.py
  python/xgbserver/xgbserver/test_model.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL

#178 Compile TF protos into Go
  tools/tf2openapi/DEVELOPER_GUIDE.md
  tools/tf2openapi/Makefile
  tools/tf2openapi/generated/framework/allocation_description.pb.go
  tools/tf2openapi/generated/framework/api_def.pb.go
  tools/tf2openapi/generated/framework/attr_value.pb.go
  tools/tf2openapi/generated/framework/cost_graph.pb.go
  tools/tf2openapi/generated/framework/device_attributes.pb.go
  tools/tf2openapi/generated/framework/function.pb.go
  tools/tf2openapi/generated/framework/graph.pb.go
  tools/tf2openapi/generated/framework/graph_transfer_info.pb.go
  tools/tf2openapi/generated/framework/iterator.pb.go
  tools/tf2openapi/generated/framework/kernel_def.pb.go
  tools/tf2openapi/generated/framework/log_memory.pb.go
  tools/tf2openapi/generated/framework/node_def.pb.go
  tools/tf2openapi/generated/framework/op_def.pb.go
  tools/tf2openapi/generated/framework/reader_base.pb.go
  tools/tf2openapi/generated/framework/remote_fused_graph_execute_info.pb.go
  tools/tf2openapi/generated/framework/resource_handle.pb.go
  tools/tf2openapi/generated/framework/step_stats.pb.go
  tools/tf2openapi/generated/framework/summary.pb.go
  tools/tf2openapi/generated/framework/tensor.pb.go
  tools/tf2openapi/generated/framework/tensor_description.pb.go
  tools/tf2openapi/generated/framework/tensor_shape.pb.go
  tools/tf2openapi/generated/framework/tensor_slice.pb.go
  tools/tf2openapi/generated/framework/types.pb.go
  tools/tf2openapi/generated/framework/variable.pb.go
  tools/tf2openapi/generated/framework/versions.pb.go
  tools/tf2openapi/generated/lib/core/error_codes.pb.go
  tools/tf2openapi/generated/protobuf/meta_graph.pb.go
  tools/tf2openapi/generated/protobuf/saved_model.pb.go
  tools/tf2openapi/generated/protobuf/saver.pb.go
Labels: approved, lgtm, ok-to-test, size/XXL

#186 Add types for TF2OpenAPI
  tools/tf2openapi/README.md
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tftensor.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#193 Make TF dependency persist when dep ensure is run
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/attrs_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/example_inception_inference_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/genop_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/graph_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/op/gradients_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/op/op_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/op/scope_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/operation_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/saved_model_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/session_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/shape_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/tensor_test.go
  vendor/github.com/tensorflow/tensorflow/tensorflow/go/util_test.go
Labels: approved, lgtm, needs-ok-to-test, size/XXL

#195 Add dependency for OpenAPI generation
  Gopkg.lock
  vendor/github.com/getkin/kin-openapi/LICENSE
  vendor/github.com/getkin/kin-openapi/jsoninfo/doc.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/field_info.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/marshal.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/marshal_ref.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/strict_struct.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/type_info.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/unmarshal.go
  vendor/github.com/getkin/kin-openapi/jsoninfo/unsupported_properties_error.go
  vendor/github.com/getkin/kin-openapi/openapi3/callback.go
  vendor/github.com/getkin/kin-openapi/openapi3/components.go
  vendor/github.com/getkin/kin-openapi/openapi3/content.go
  vendor/github.com/getkin/kin-openapi/openapi3/discriminator.go
  vendor/github.com/getkin/kin-openapi/openapi3/doc.go
  vendor/github.com/getkin/kin-openapi/openapi3/encoding.go
  vendor/github.com/getkin/kin-openapi/openapi3/examples.go
  vendor/github.com/getkin/kin-openapi/openapi3/extension.go
  vendor/github.com/getkin/kin-openapi/openapi3/external_docs.go
  vendor/github.com/getkin/kin-openapi/openapi3/header.go
  vendor/github.com/getkin/kin-openapi/openapi3/info.go
  vendor/github.com/getkin/kin-openapi/openapi3/link.go
  vendor/github.com/getkin/kin-openapi/openapi3/media_type.go
  vendor/github.com/getkin/kin-openapi/openapi3/operation.go
  vendor/github.com/getkin/kin-openapi/openapi3/parameter.go
  vendor/github.com/getkin/kin-openapi/openapi3/path_item.go
  vendor/github.com/getkin/kin-openapi/openapi3/paths.go
  vendor/github.com/getkin/kin-openapi/openapi3/refs.go
  vendor/github.com/getkin/kin-openapi/openapi3/request_body.go
  vendor/github.com/getkin/kin-openapi/openapi3/response.go
  vendor/github.com/getkin/kin-openapi/openapi3/schema.go
  vendor/github.com/getkin/kin-openapi/openapi3/schema_formats.go
  vendor/github.com/getkin/kin-openapi/openapi3/security_requirements.go
  vendor/github.com/getkin/kin-openapi/openapi3/security_scheme.go
  vendor/github.com/getkin/kin-openapi/openapi3/serialization_method.go
  vendor/github.com/getkin/kin-openapi/openapi3/server.go
  vendor/github.com/getkin/kin-openapi/openapi3/swagger.go
  vendor/github.com/getkin/kin-openapi/openapi3/swagger_loader.go
  vendor/github.com/getkin/kin-openapi/openapi3/tag.go
Labels: approved, lgtm, ok-to-test, size/XXL

#187 Update Owners
  OWNERS
Labels: approved, lgtm, size/XS

#182 Dockerfile for the Seldon alibiexplainer
  python/alibiexplainer.Dockerfile
Labels: approved, lgtm, size/XS

#194 Update dep installation in DEVELOPER_GUIDE
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, ok-to-test, size/XS

#153 PyTorch Support
  config/default/crds/serving_v1alpha1_kfservice.yaml
  docs/samples/pytorch/README.md
  docs/samples/pytorch/cifar10.py
  docs/samples/pytorch/input.json
  docs/samples/pytorch/pytorch.yaml
  pkg/apis/serving/v1alpha1/framework.go
  pkg/apis/serving/v1alpha1/kfservice_framework_pytorch.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  python/pytorch.Dockerfile
  python/pytorchserver/Makefile
  python/pytorchserver/README.md
  python/pytorchserver/pytorchserver/__init__.py
  python/pytorchserver/pytorchserver/__main__.py
  python/pytorchserver/pytorchserver/model.py
  python/pytorchserver/pytorchserver/test_model.py
  python/pytorchserver/setup.py
Labels: approved, lgtm, size/XXL

#200 note on existing istio from kubeflow
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#199 Add jiwang576 as a reviewer for kfserving.
  OWNERS
Labels: approved, lgtm, needs-ok-to-test, size/XS

#202 fix route and configuration race
  pkg/controller/kfservice/kfservice_controller.go
Labels: approved, lgtm, size/XS

#167 Tf2OpenAPI: Convert Pb to internal model
  tools/tf2openapi/README.md
  tools/tf2openapi/cmd/main.go
  tools/tf2openapi/generator/generate.go
  tools/tf2openapi/types/tfmetagraph.go
  tools/tf2openapi/types/tfsavedmodel.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tftensor.go
Labels: approved, lgtm, ok-to-test, size/L

#177 Creating Go Client Libraries for KFservice CRD
  Gopkg.lock
  Gopkg.toml
  Makefile
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_kfservice.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/kfservice.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/serving/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/kfservice.go
  pkg/client/listers/serving/v1alpha1/expansion_generated.go
  pkg/client/listers/serving/v1alpha1/kfservice.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
Labels: approved, lgtm, ok-to-test, size/XXL

#206 fix pytorch pylint errors
  python/pytorchserver/pytorchserver/test_model.py
  python/pytorchserver/setup.py
Labels: approved, lgtm, size/XS

#208 Fix PyTorch type comments
  config/default/crds/serving_v1alpha1_kfservice.yaml
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#156 add model initializer
  pkg/apis/serving/v1alpha1/framework.go
  pkg/apis/serving/v1alpha1/framework_custom.go
  pkg/apis/serving/v1alpha1/framework_scikit.go
  pkg/apis/serving/v1alpha1/framework_tensorflow.go
  pkg/apis/serving/v1alpha1/framework_xgboost.go
  pkg/apis/serving/v1alpha1/kfservice_framework_pytorch.go
  pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt.go
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/controller/kfservice/reconcilers/knative/configuration_reconciler_test.go
  pkg/controller/kfservice/resources/knative/configuration.go
  pkg/controller/kfservice/resources/knative/configuration_test.go
  pkg/webhook/admission/deployment/accelerator_injector.go
  pkg/webhook/admission/deployment/accelerator_injector_test.go
  pkg/webhook/admission/deployment/model_initializer_injector.go
  pkg/webhook/admission/deployment/model_initializer_injector_test.go
  pkg/webhook/admission/deployment/mutator.go
  pkg/webhook/webhook.go
  python/kfserving/kfserving/storage.py
  python/model-initializer.Dockerfile
  python/model-initializer/scripts/initializer-entrypoint
Labels: approved, lgtm, size/XL
