Repository kserve/kserve, pull requests merged in 2019-11, with the labels that each got.

#492 Refactoring KFServer and KFModel.
  docs/samples/explanation/alibi/imagenet/test_imagenet.py
  docs/samples/transformer/image_transformer/image_transformer/image_transformer.py
  python/alibiexplainer/README.md
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/alibiexplainer/anchor_images.py
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
  python/alibiexplainer/alibiexplainer/anchor_text.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/setup.py
  python/kfserving/README.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/constants/constants.py
  python/kfserving/kfserving/handlers/__init__.py
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/kfserving/kfmodel.py
  python/kfserving/kfserving/kfserver.py
  python/kfserving/kfserving/model.py
  python/kfserving/kfserving/protocols/request_handler.py
  python/kfserving/kfserving/protocols/seldon_http.py
  python/kfserving/kfserving/protocols/tensorflow_http.py
  python/kfserving/kfserving/server.py
  python/kfserving/kfserving/transformer.py
  python/kfserving/kfserving/utils/__init__.py
  python/kfserving/kfserving/utils/numpy_encoder.py
  python/kfserving/setup.py
  python/kfserving/test/test_request_handler.py
  python/kfserving/test/test_server.py
  python/pytorchserver/pytorchserver/__main__.py
  python/pytorchserver/pytorchserver/example_model/cifar10.py
  python/pytorchserver/pytorchserver/example_model/model.pt
  python/pytorchserver/pytorchserver/model.py
  python/pytorchserver/pytorchserver/test_model.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/sklearnserver/sklearnserver/__main__.py
  python/sklearnserver/sklearnserver/example_model/model.joblib
  python/sklearnserver/sklearnserver/model.py
  python/sklearnserver/sklearnserver/test_model.py
  python/xgbserver/setup.py
  python/xgbserver/xgbserver/__main__.py
  python/xgbserver/xgbserver/example_model/model.bst
  python/xgbserver/xgbserver/model.py
  python/xgbserver/xgbserver/test_model.py
  test/scripts/sdk-test.sh
Labels: approved, lgtm, size/XXL

#510 Fix typo in resources
  pkg/apis/serving/v1alpha2/utils.go
Labels: approved, lgtm, size/XS

#506 Add test case for endpoint with both predictor and explainer.
  pkg/controller/inferenceservice/controller_test.go
Labels: approved, lgtm, size/L

#500 Validate replicas for explainer and transformer too
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/apis/serving/v1alpha2/utils.go
Labels: approved, lgtm, ok-to-test, size/M

#516 Fix flaky test for deleting canary
  pkg/controller/inferenceservice/controller_test.go
Labels: approved, lgtm, size/S

#518 fix blob breaking change
  python/kfserving/kfserving/storage.py
  python/kfserving/requirements.txt
Labels: approved, lgtm, size/XS

#509 Add explanation notebooks
  docs/samples/explanation/alibi/alibi_helper.py
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/income/income.yaml
  docs/samples/explanation/alibi/income/income_explanations.ipynb
  docs/samples/explanation/alibi/income/requirements.txt
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/explanation/alibi/moviesentiment/kfserving_text_explainer.ipynb
  docs/samples/explanation/alibi/moviesentiment/movie_review_explanations.ipynb
  docs/samples/explanation/alibi/moviesentiment/moviesentiment.yaml
  docs/samples/explanation/alibi/moviesentiment/requirements.txt
Labels: approved, lgtm, size/XL

#521 Minor fix of the link path in explainer doc
  python/alibiexplainer/README.md
Labels: approved, lgtm, size/XS

#507 Add arm64 support for kfserving
  Dockerfile
  executor.Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#498 fix mini problem and release new pypi pkg
  python/kfserving/kfserving/__init__.py
  python/kfserving/setup.py
Labels: approved, lgtm, size/XS

#526 Add CI step to build image-transformer
  test/scripts/build-custom-image-transformer.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#524 To make the sample work with the refactored kfmodel
  docs/samples/transformer/image_transformer/README.md
  docs/samples/transformer/image_transformer/image_transformer.yaml
  docs/samples/transformer/image_transformer/image_transformer/__main__.py
  docs/samples/transformer/image_transformer/image_transformer/image_transformer.py
Labels: approved, lgtm, size/S

#531 Move up label check in pod mutator
  README.md
  pkg/webhook/admission/pod/mutator.go
Labels: approved, lgtm, size/S

#532 redirecting to common troubleshooting section
  README.md
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/M

#534 update sdk requirements and version
  python/kfserving/requirements.txt
  python/kfserving/setup.py
Labels: approved, lgtm, size/M

#528 Remove redundant code which is confusing
  pkg/constants/constants.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
Labels: approved, lgtm, size/M

#503 Payload Logger
  Makefile
  cmd/executor/main.go
  cmd/logger/main.go
  docs/samples/logger/local/README.md
  docs/samples/logger/local/input.json
  executor.Dockerfile
  logger.Dockerfile
  pkg/executor/executor.go
  pkg/executor/postprocess.go
  pkg/executor/predict.go
  pkg/executor/preprocess.go
  pkg/logger/collector.go
  pkg/logger/constants.go
  pkg/logger/dispatcher.go
  pkg/logger/server.go
  pkg/logger/server_test.go
  pkg/logger/types.go
  pkg/logger/worker.go
  release/triggers/latest/executor.yaml
  release/triggers/tagged/executor.yaml
  test/scripts/build-logger.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL

#529 Generated 0.2.1 install
  README.md
  config/default/configmap/inferenceservice.yaml
  docs/samples/transformer/image_transformer/setup.py
  hack/generate-install.sh
  install/0.2.1/kfserving.yaml
  pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/constants/constants.go
  python/kfserving/docs/KFServingClient.md
Labels: approved, lgtm, size/XXL

#536 Install pytorch-cpu for cpu image
  python/pytorch.Dockerfile
Labels: approved, lgtm, size/XS

#545 Fix the log format to add more debug information
  python/kfserving/kfserving/kfserver.py
Labels: approved, lgtm, size/S

#553 #552 Fixes a bad config for 0.2.1
  install/0.2.1/kfserving.yaml
Labels: approved, lgtm, size/S

#544 * Change to use image from gcr
  docs/samples/transformer/image_transformer/kfserving_sdk_transformer.ipynb
Labels: approved, lgtm, size/M

#467 Logger
  config/default/configmap/inferenceservice.yaml
  config/default/crds/serving_v1alpha2_inferenceservice.yaml
  docs/samples/logger/basic/README.md
  docs/samples/logger/basic/iris-input.json
  docs/samples/logger/basic/logger_demo.ipynb
  docs/samples/logger/basic/message-dumper.yaml
  docs/samples/logger/basic/sklearn-logging.yaml
  docs/samples/logger/knative-eventing/README.md
  docs/samples/logger/knative-eventing/iris-input.json
  docs/samples/logger/knative-eventing/logger_demo.ipynb
  docs/samples/logger/knative-eventing/message-dumper.yaml
  docs/samples/logger/knative-eventing/sklearn-logging.yaml
  docs/samples/logger/knative-eventing/trigger.yaml
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/inference_logger.go
  pkg/apis/serving/v1alpha2/inference_logger_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
  pkg/logger/server.go
  pkg/webhook/admission/pod/logger_injector.go
  pkg/webhook/admission/pod/logger_injector_test.go
  pkg/webhook/admission/pod/mutator.go
Labels: approved, lgtm, size/XXL

#555 Fix end2end test
  test/e2e/utils.py
Labels: approved, lgtm, size/XS

#525 Add more e2e tests
  config/default/crds/serving_v1alpha2_inferenceservice.yaml
  config/default/rbac/auth_proxy_role_binding.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  config/overlays/test/kustomization.yaml
  install/0.2.1/kfserving.yaml
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/controller/inferenceservice/controller_test.go
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/kfmodel.py
  python/kfserving/kfserving/kfserver.py
  python/pytorchserver/pytorchserver/model.py
  python/pytorchserver/pytorchserver/test_model.py
  test/e2e/__init__.py
  test/e2e/common/__init__.py
  test/e2e/common/utils.py
  test/e2e/data/flower_input.json
  test/e2e/data/iris_input.json
  test/e2e/data/transformer.json
  test/e2e/predictor/__init__.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_tensorflow.py
  test/e2e/predictor/test_xgboost.py
  test/e2e/transformer/__init__.py
  test/e2e/transformer/test_transformer.py
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XL

#559 upgrade istio and knative in CI tests
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/S

#554 Roadmap changes
  ROADMAP.md
Labels: approved, lgtm, size/L

#561 Add a note to install cluster local gateway for knative 0.9.0+
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#566 Correct onnx readme steps
  docs/samples/onnx/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#570 Release the logger image
  release/triggers/latest/logger.yaml
  release/triggers/tagged/logger.yaml
Labels: approved, lgtm, size/M

#575 Remove executor in makefile and add logger/Add logger test configmap
  Makefile
  config/overlays/test/configmap/inferenceservice.yaml
Labels: approved, lgtm, size/S

#571 Add namespace selector for pod mutating webhook
  README.md
  config/default/rbac/rbac_role.yaml
  pkg/constants/constants.go
  pkg/webhook/admission/inferenceservice/inferenceservice_validator.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#578 fix typos
  README.md
Labels: approved, lgtm, size/XS

#549 [xgbserver] Expose nthread in XGBoostSpec
  config/default/crds/serving_v1alpha2_inferenceservice.yaml
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/controller/inferenceservice/resources/knative/service_test.go
  python/xgbserver/xgbserver/__main__.py
  python/xgbserver/xgbserver/model.py
  python/xgbserver/xgbserver/test_model.py
Labels: approved, lgtm, ok-to-test, size/L

#581 Skip get inferenceservice-config configmap for non-kfserving pod
  pkg/webhook/admission/pod/mutator.go
Labels: approved, lgtm, size/S
