Repository kserve/kserve, pull requests merged in 2019-04, with the labels that each got.

#8 Added KFService types
  pkg/apis/serving/v1alpha1/kfservice_types.go
Labels: approved, lgtm, size/L

#9 fix import path and regenerate crd
  cmd/manager/main.go
  config/crds/serving_v1alpha1_kfservice.yaml
  pkg/apis/addtoscheme_serving_v1alpha1.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_kfservice.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_suite_test.go
  pkg/controller/kfservice/kfservice_controller_test.go
Labels: approved, lgtm, size/L

#11 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#21 Implemented Validation and Default behavior (#12)
  cmd/manager/main.go
  config/crds/serving_v1alpha1_kfservice.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/serving/v1alpha1/kfservice_defaults.go
  pkg/apis/serving/v1alpha1/kfservice_defaults_test.go
  pkg/apis/serving/v1alpha1/kfservice_types.go
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  pkg/reconciler/ksvc/resources/knative_service.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#23 Add @yuzisun as approver
  OWNERS
Labels: approved, lgtm, size/XS

#24 OWNERS: Add gaocegege as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#25 adding animeshsingh as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#26 Added samples and documentation
  README.md
  docs/DEVELOPER_GUIDE.md
  docs/README.md
  docs/samples/canary.yaml
  docs/samples/pinned.yaml
  docs/samples/resource-requests.yaml
  docs/samples/tensorflow.yaml
Labels: approved, lgtm, size/L

#30 Fixed pointer to build manager
  Makefile
Labels: approved, lgtm, size/XS

#29 Mark Knative serving service and kfservice clear in log
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/reconciler/ksvc/reconciler.go
  pkg/reconciler/ksvc/resources/knative_service.go
Labels: approved, lgtm, size/S

#38 Add Clive as Approver
  OWNERS
Labels: approved, lgtm, size/XS

#37 Adds initial CONTRIBUTING guidelines
  CONTRIBUTING.md
Labels: approved, lgtm, size/M

#42 Fixes a markdown formatting issue in CONTRIBUTING
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#43 Fixes broken validation tests.
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  pkg/reconciler/ksvc/reconciler.go
Labels: approved, lgtm, size/M

#32 Add Data Plane Docs
  docs/README.md
  docs/control-plane.md
  docs/data-plane.md
Labels: approved, lgtm, size/L

#47 Making readme more descriptive
  README.md
Labels: approved, lgtm, size/XS

#31 Fix TODOs and improve testing code
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/frameworks/tensorflow/tensorflow_serving.go
  pkg/reconciler/ksvc/resources/knative_service.go
  pkg/reconciler/ksvc/resources/knative_service_test.go
Labels: approved, lgtm, size/L

#34 Fix RBAC
  Makefile
  config/default/manager_image_patch.yaml
  config/overlays/development/kustomization.yaml
  config/overlays/development/manager_image_patch.yaml
  config/rbac/rbac_role.yaml
  pkg/controller/kfservice/kfservice_controller.go
Labels: approved, lgtm, size/M

#45 Implements Validating and Defaulting AdmissionWebhooks for KFServices
  Gopkg.lock
  Makefile
  cmd/manager/main.go
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  config/samples/serving_v1alpha1_service.yaml
  docs/samples/tensorflow.yaml
  pkg/apis/serving/v1alpha1/doc.go
  pkg/apis/serving/v1alpha1/kfservice_defaults.go
  pkg/apis/serving/v1alpha1/kfservice_defaults_test.go
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  pkg/apis/serving/v1alpha1/register.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/webhook/admission/kfservice/kfservice_defaulter.go
  pkg/webhook/admission/kfservice/kfservice_validator.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/L

#54 Restores manager_image_patch.yaml
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/S

#40 Custom container
  Gopkg.toml
  config/samples/custom.yaml
  pkg/apis/serving/v1alpha1/kfservice_validation.go
  pkg/apis/serving/v1alpha1/kfservice_validation_test.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/frameworks/custom/custom_container.go
  pkg/reconciler/ksvc/reconciler_test.go
  pkg/reconciler/ksvc/resources/knative_service.go
  pkg/reconciler/ksvc/resources/knative_service_test.go
Labels: approved, lgtm, size/L

#51 model default/canary with two configurations and one route
  config/rbac/rbac_role.yaml
  docs/samples/canary.yaml
  docs/samples/pinned.yaml
  docs/samples/resource-requests.yaml
  pkg/apis/serving/v1alpha1/kfservice_status.go
  pkg/constants/constants.go
  pkg/controller/kfservice/kfservice_controller.go
  pkg/controller/kfservice/kfservice_controller_suite_test.go
  pkg/controller/kfservice/kfservice_controller_test.go
  pkg/reconciler/ksvc/ksvc_suite_test.go
  pkg/reconciler/ksvc/reconciler.go
  pkg/reconciler/ksvc/reconciler_test.go
  pkg/reconciler/ksvc/resources/knative_configuration.go
  pkg/reconciler/ksvc/resources/knative_configuration_test.go
  pkg/reconciler/ksvc/resources/knative_route.go
  pkg/reconciler/ksvc/resources/knative_route_test.go
  pkg/reconciler/ksvc/resources/knative_service.go
  pkg/reconciler/ksvc/resources/knative_service_test.go
  test/crds/knative_configuration.yaml
  test/crds/knative_route.yaml
Labels: approved, lgtm, size/XXL
