Repository kserve/kserve, pull requests merged in 2020-05, with the labels that each got.

#814 cleanup xgboost sample
  docs/samples/xgboost/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#816 Remove kfserving ingressgateway from doc
  docs/samples/autoscaling/README.md
  docs/samples/custom-domain/README.md
  docs/samples/custom/hello-world/README.md
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/kfserving-custom-model/kfserving_sdk_custom_image.ipynb
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/logger/basic/README.md
  docs/samples/logger/knative-eventing/README.md
  docs/samples/onnx/README.md
  docs/samples/pytorch/README.md
  docs/samples/rollouts/README.md
  docs/samples/s3/README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, size/M

#818 Return 503 from healthhandler when model is not ready
  python/kfserving/kfserving/kfserver.py
  python/kfserving/test/test_server.py
Labels: approved, lgtm, ok-to-test, size/S

#800 Add custom inference example using BentoML
  docs/samples/README.md
  docs/samples/bentoml/README.md
  docs/samples/bentoml/bentoml.yaml
Labels: approved, lgtm, ok-to-test, size/L

#821 Add KFServing on Kubeflow with Istio-Dex Example
  docs/samples/README.md
  docs/samples/istio-dex/README.md
  docs/samples/istio-dex/iris-input.json
  docs/samples/istio-dex/sklearn.yaml
Labels: approved, lgtm, ok-to-test, size/L

#819 Upgrade test-worker to use new Python for testing
  test/scripts/run-e2e-tests.sh
  test/scripts/sdk-test.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/M

#823 allow configurable region name
  python/kfserving/kfserving/storage.py
Labels: approved, lgtm, ok-to-test, size/XS

#822 Add an easier method to obtain Istio-Dex authentication token
  docs/samples/istio-dex/README.md
Labels: approved, lgtm, ok-to-test, size/M

#832 Added prefixing http for the fix to work
  python/kfserving/kfserving/storage.py
Labels: approved, lgtm, size/XS

#829 Add KFServing Debugging guide
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  docs/DEVELOPER_GUIDE.md
  docs/KFSERVING_DEBUG_GUIDE.md
  docs/diagrams/sklearn-iris-tracing.png
  pkg/webhook/admission/pod/storage_initializer_injector.go
Labels: approved, lgtm, size/L

#806 Set ContainerConcurrency to Parallelism
  pkg/controller/inferenceservice/resources/knative/service.go
Labels: approved, lgtm, ok-to-test, size/S

#838 Update test KFServing installation documentation
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#843 Doc fixes for cert manager version and s3 secret yaml
  README.md
  docs/samples/s3/README.md
Labels: approved, lgtm, size/XS

#803 Update Alibi Explainers to 0.4.0 Release
  docs/samples/explanation/alibi/alibi_helper.py
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/imagenet/imagenet.yaml
  docs/samples/explanation/alibi/imagenet/test_imagenet.py
  docs/samples/explanation/alibi/income/income.yaml
  docs/samples/explanation/alibi/income/income_explanations.ipynb
  docs/samples/explanation/alibi/moviesentiment/movie_review_explanations.ipynb
  python/.pylintrc
  python/alibiexplainer.Dockerfile
  python/alibiexplainer/Makefile
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/alibiexplainer/anchor_images.py
  python/alibiexplainer/alibiexplainer/anchor_tabular.py
  python/alibiexplainer/alibiexplainer/anchor_text.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/alibiexplainer/explainer_wrapper.py
  python/alibiexplainer/alibiexplainer/parser.py
  python/alibiexplainer/setup.py
  python/alibiexplainer/tests/__init__.py
  python/alibiexplainer/tests/test_anchor_images.py
  python/alibiexplainer/tests/test_anchor_tabular.py
  python/alibiexplainer/tests/test_anchor_text.py
  python/alibiexplainer/tests/test_parser.py
  python/alibiexplainer/tests/utils.py
Labels: approved, lgtm, size/XL
