Repository kserve/kserve, pull requests merged in 2020-08, with the labels that each got.

#990 publish batcher image to docker hub for v0.4.0
  install/v0.4.0/kfserving.yaml
Labels: approved, lgtm, size/XS

#996 Add ifilonenko & yuzliu as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#998 Update GRPC protocol to have raw tensor data at top-level of message
  docs/predict-api/v2/required_api.md
Labels: approved, lgtm, ok-to-test, size/M

#1000 fix minio storage test
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/XS

#1009 Trained model api
  pkg/apis/serving/v1beta1/trained_model.go
  pkg/apis/serving/v1beta1/trained_model_status.go
Labels: approved, lgtm, size/M

#1008 Update ingress gateway access instruction and add KFServing repo badges
  README.md
  docs/samples/autoscaling/README.md
  docs/samples/batcher/basic/README.md
  docs/samples/bentoml/README.md
  docs/samples/custom/hello-world/README.md
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/gcp-iap/README.md
  docs/samples/kafka/README.md
  docs/samples/onnx/README.md
  docs/samples/pytorch/README.md
  docs/samples/rollouts/README.md
  docs/samples/s3/README.md
  docs/samples/sklearn/README.md
  docs/samples/tensorflow/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/triton/bert/README.md
  docs/samples/triton/simple_string/README.md
  docs/samples/xgboost/README.md
Labels: lgtm, size/L

#992 Add multimodel configmap
  go.mod
  pkg/constants/constants.go
  pkg/modelconfig/configmap.go
  pkg/modelconfig/configmap_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1022 Add common case for knative authorization issue
  docs/KFSERVING_DEBUG_GUIDE.md
Labels: approved, lgtm, ok-to-test, size/S

#1018 Genericized component logic; cleaned up valdation and other interfaces
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/explainer.go
  pkg/apis/serving/v1beta1/explainer_alibi.go
  pkg/apis/serving/v1beta1/explainer_alibi_test.go
  pkg/apis/serving/v1beta1/explainer_custom.go
  pkg/apis/serving/v1beta1/explainer_custom_test.go
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_triton.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/apis/serving/v1beta1/transformer.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/XL

#1025 Update PRESENTATIONS.md
  docs/PRESENTATIONS.md
Labels: approved, lgtm, size/XS

#1026 Add ICML Presentation
  docs/PRESENTATIONS.md
Labels: approved, lgtm, size/XS

#1028 Add S3 access key format for prior version of KFServing
  docs/samples/s3/README.md
Labels: approved, lgtm, ok-to-test, size/S

#1039 Fix small typo
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#989 [POC] Multi-Model Puller
  cmd/agent/agent.Dockerfile
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/agent/downloader.go
  pkg/agent/puller.go
  pkg/agent/storage/provider.go
  pkg/agent/storage/s3.go
  pkg/agent/storage/utils.go
  pkg/agent/syncer.go
  pkg/agent/watcher.go
  pkg/modelconfig/configmap.go
  pkg/modelconfig/configmap_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#1049 Update ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, size/XS

#1053 Fix shap version to 0.35
  python/alibiexplainer/setup.py
Labels: approved, lgtm, size/XS

#1036 Docs/custom domain
  docs/samples/custom-domain/README.md
  docs/samples/custom-domain/kfserving-ingress.yaml
Labels: approved, lgtm, ok-to-test, size/L
