Repository kserve/kserve, pull requests merged in 2020-07, with the labels that each got.

#907 add customized urls and sample
  docs/samples/custom/customized-urls/Dockerfile
  docs/samples/custom/customized-urls/Readme.md
  docs/samples/custom/customized-urls/app.py
  docs/samples/custom/customized-urls/customized-urls.yaml
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Labels: approved, lgtm, ok-to-test, size/L

#914 remove the unstable check
  pkg/controller/inferenceservice/controller_test.go
Labels: approved, lgtm, ok-to-test, size/S

#807 Disable retries in Istio VirtualService
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Labels: approved, lgtm, ok-to-test, size/M

#921 update custom/grpc-service sample
  docs/samples/custom/grpc-server/README.md
  docs/samples/custom/grpc-server/grpc-service.yaml
Labels: approved, lgtm, ok-to-test, size/S

#917 Remove framework image version list from configmap
  Makefile
  config/configmap/inferenceservice.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  docs/samples/sklearn/README.md
  docs/samples/xgboost/README.md
  go.sum
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorflow_test.go
  pkg/apis/serving/v1alpha2/framework_triton.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/inferenceservice/controller_test.go
  python/sklearnserver/README.md
  python/xgbserver/README.md
  test/e2e/predictor/test_xgboost.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#926 update pipeline sample to point to mnist e2e one
  docs/samples/pipelines/README.md
  docs/samples/pipelines/images/kfserving-mnist-pipeline.png
Labels: approved, lgtm, size/S

#908 Create TrainedModel CRD
  config/configmap/inferenceservice.yaml
  config/crd/serving.kubeflow.org_inferencerouters.yaml
  config/crd/serving.kubeflow.org_trainedmodels.yaml
  pkg/apis/serving/v1beta1/trained_model.go
  pkg/apis/serving/v1beta1/trained_model_status.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/L

#837 make default req log url more flexible
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/logger/basic/README.md
  pkg/constants/constants.go
  pkg/webhook/admission/pod/logger_injector.go
Labels: approved, lgtm, size/S

#935 fix config map format
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
Labels: approved, lgtm, ok-to-test, size/M

#934 add custom default conainer name
  pkg/apis/serving/v1alpha2/framework_custom.go
Labels: approved, lgtm, ok-to-test, size/XS

#931 Update KFServing 0.4 API docs
  README.md
  config/overlays/test/configmap/inferenceservice.yaml
  docs/apis/README.md
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/triton/simple_string/README.md
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
Labels: approved, lgtm, size/L

#932 Fix tf2openapi dockerfile
  tools/tf2openapi/Dockerfile
Labels: approved, lgtm, size/XS

#945 Resolve custom sample deploy error.
  docs/samples/custom/grpc-server/grpc-service.yaml
  docs/samples/custom/hello-world/custom.yaml
  docs/samples/custom/kfserving-custom-model/custom.yaml
  docs/samples/custom/prebuilt-image/custom.yaml
  pkg/apis/serving/v1alpha2/framework_custom.go
Labels: approved, lgtm, ok-to-test, size/XS

#925 Add LivenessProbe to Tensorflow Predictor
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorflow_test.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
Labels: approved, lgtm, ok-to-test, size/L

#952 Create ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, size/S

#956 Create PRESENTATIONS.md
  README.md
  docs/PRESENTATIONS.md
Labels: approved, lgtm, size/S

#955 update adopters.md
  ADOPTERS.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#957 correct Kubeflow spelling
  docs/PRESENTATIONS.md
Labels: approved, lgtm, size/XS

#961 Update ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, size/XS

#960 Add Max Kelsen to ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test, size/XS

#959 add anchor kfserving podcast + arrange adopters alphabetically
  ADOPTERS.md
  docs/PRESENTATIONS.md
Labels: approved, lgtm, size/XS

#958 Add Qingshan Chen from Inspur as a reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#964 Fix link to logging documentation in README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#963 Update KNative annotation when modifying minReplicas to 0
  pkg/controller/inferenceservice/resources/knative/service.go
Labels: approved, lgtm, ok-to-test, size/XS

#933 Publish KFServing 0.4 release
  config/configmap/inferenceservice.yaml
  hack/boilerplate.go.txt
  hack/boilerplate.python.txt
  hack/generate-install.sh
  install/v0.4.0/kfserving.yaml
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/inference_logger.go
  pkg/apis/serving/v1alpha2/inference_logger_test.go
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/apis/serving/v1alpha2/transformer_custom.go
  pkg/apis/serving/v1alpha2/utils.go
  pkg/constants/constants.go
  pkg/logger/collector.go
  pkg/logger/constants.go
  pkg/logger/dispatcher.go
  pkg/logger/types.go
  pkg/logger/worker.go
  pkg/webhook/admission/pod/logger_injector.go
  pkg/webhook/admission/pod/logger_injector_test.go
  python/alibiexplainer/alibiexplainer/parser.py
  python/alibiexplainer/setup.py
  python/alibiexplainer/tests/__init__.py
  python/alibiexplainer/tests/test_anchor_images.py
  python/alibiexplainer/tests/test_anchor_tabular.py
  python/alibiexplainer/tests/test_anchor_text.py
  python/alibiexplainer/tests/test_parser.py
  python/alibiexplainer/tests/utils.py
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/setup.py
  python/kfserving/test/test_v1alpha2_batcher.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/xgbserver/setup.py
Labels: approved, lgtm, size/XXL

#969 Update ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test, size/XS

#970 Update ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test, size/XS

#967 updated instruction for Curl the `InferenceService` in README.md #966
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#968 Update KFS 0.4 installation instruction
  README.md
  docs/samples/istio-dex/README.md
  docs/samples/s3/README.md
  docs/samples/s3/s3_secret.yaml
  hack/quick_install.sh
  test/scripts/sdk-test.sh
Labels: approved, lgtm, size/M

#936 Migrate controller tests to use BDD testing style
  cmd/manager/main.go
  go.mod
  pkg/apis/addtoscheme_serving_v1alpha2.go
  pkg/apis/apis.go
  pkg/apis/serving/group.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/add_inferenceservice.go
  pkg/controller/inferenceservice/controller.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/suite_test.go
  pkg/credentials/azure/azure_secret.go
  pkg/credentials/azure/azure_secret_test.go
  pkg/credentials/credentials_suite_test.go
  pkg/credentials/gcs/gcs_secret.go
  pkg/credentials/gcs/gcs_secret_test.go
  pkg/credentials/s3/s3_secret.go
  pkg/credentials/s3/s3_secret_test.go
  pkg/credentials/service_account_credentials.go
  pkg/credentials/service_account_credentials_test.go
  pkg/testing/envtest_setup.go
  pkg/utils/utils_test.go
  pkg/webhook/admission/pod/mutator.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: approved, lgtm, size/XXL

#978 Generate SDK for 0.4 release
  cmd/spec-gen/main.go
  hack/boilerplate.sh
  hack/python-sdk/client-gen.sh
  hack/update-openapigen.sh
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  python/kfserving/docs/KnativeVolatileTime.md
  python/kfserving/docs/V1alpha2AlibiExplainerSpec.md
  python/kfserving/docs/V1alpha2Batcher.md
  python/kfserving/docs/V1alpha2DeploymentSpec.md
  python/kfserving/docs/V1alpha2ExplainerSpec.md
  python/kfserving/docs/V1alpha2InferenceService.md
  python/kfserving/docs/V1alpha2InferenceServiceList.md
  python/kfserving/docs/V1alpha2InferenceServiceSpec.md
  python/kfserving/docs/V1alpha2InferenceServiceStatus.md
  python/kfserving/docs/V1alpha2Logger.md
  python/kfserving/docs/V1alpha2ONNXSpec.md
  python/kfserving/docs/V1alpha2PredictorSpec.md
  python/kfserving/docs/V1alpha2PyTorchSpec.md
  python/kfserving/docs/V1alpha2SKLearnSpec.md
  python/kfserving/docs/V1alpha2StatusConfigurationSpec.md
  python/kfserving/docs/V1alpha2TensorflowSpec.md
  python/kfserving/docs/V1alpha2TransformerSpec.md
  python/kfserving/docs/V1alpha2TritonSpec.md
  python/kfserving/docs/V1alpha2XGBoostSpec.md
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/v1alpha2_alibi_explainer_spec.py
  python/kfserving/kfserving/models/v1alpha2_batcher.py
  python/kfserving/kfserving/models/v1alpha2_deployment_spec.py
  python/kfserving/kfserving/models/v1alpha2_explainer_spec.py
  python/kfserving/kfserving/models/v1alpha2_inference_service.py
  python/kfserving/kfserving/models/v1alpha2_inference_service_list.py
  python/kfserving/kfserving/models/v1alpha2_inference_service_spec.py
  python/kfserving/kfserving/models/v1alpha2_inference_service_status.py
  python/kfserving/kfserving/models/v1alpha2_logger.py
  python/kfserving/kfserving/models/v1alpha2_onnx_spec.py
  python/kfserving/kfserving/models/v1alpha2_predictor_spec.py
  python/kfserving/kfserving/models/v1alpha2_py_torch_spec.py
  python/kfserving/kfserving/models/v1alpha2_sk_learn_spec.py
  python/kfserving/kfserving/models/v1alpha2_status_configuration_spec.py
  python/kfserving/kfserving/models/v1alpha2_tensorflow_spec.py
  python/kfserving/kfserving/models/v1alpha2_transformer_spec.py
  python/kfserving/kfserving/models/v1alpha2_triton_spec.py
  python/kfserving/kfserving/models/v1alpha2_xg_boost_spec.py
  python/kfserving/setup.py
  test/e2e/batcher/test_batcher.py
Labels: approved, lgtm, size/XL
