Repository kserve/kserve, pull requests merged in 2020-01, with the labels that each got.

#591 Enable make to apply local changes of model servers, explainer and storage-initializer
  .gitignore
  Makefile
  config/overlays/dev-image-config/kustomization.yaml
  docs/DEVELOPER_GUIDE.md
  hack/alibi_patch_dev.sh
  hack/misc_patch_dev.sh
  hack/model_server_patch_dev.sh
Labels: approved, lgtm, size/L

#626 pin pillow version to 6.1
  docs/samples/transformer/image_transformer/setup.py
Labels: approved, lgtm, size/XS

#610 add APIs to wait for isvc ready and check status
  python/kfserving/README.md
  python/kfserving/docs/KFServingClient.md
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/constants/constants.py
  test/e2e/common/utils.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_tensorflow.py
  test/e2e/predictor/test_xgboost.py
  test/e2e/transformer/test_transformer.py
Labels: approved, lgtm, size/L

#603 Fix for the bug #602
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#631 Updated docs for KFserving pipeline to make it more clear
  docs/samples/pipelines/README.md
Labels: approved, lgtm, size/XS

#636 Pin pillow for pytorchserver
  python/alibiexplainer.Dockerfile
  python/pytorch.Dockerfile
  python/sklearn.Dockerfile
  python/xgb.Dockerfile
Labels: approved, lgtm, size/S

#641 Use pip 19.3.1 instead of 20.x for installing xgboost wheel
  python/xgb.Dockerfile
Labels: approved, lgtm, size/XS

#585 Update Knative Serving API version from v1alpha1 to v1
  cmd/manager/main.go
  pkg/apis/serving/v1alpha2/inferenceservice_status.go
  pkg/apis/serving/v1alpha2/inferenceservice_status_test.go
  pkg/controller/inferenceservice/controller.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
  pkg/testing/envtest_setup.go
  test/crds/knative_configuration.yaml
  test/crds/knative_route.yaml
  test/crds/knative_service.yaml
Labels: approved, lgtm, size/XL

#643 Add storage uri for transformer
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/controller/inferenceservice/resources/knative/service.go
Labels: approved, lgtm, size/S

#613 Initialize SecurityContext in injected containers and improve logging
  Dockerfile
  pkg/constants/constants.go
  pkg/webhook/admission/pod/logger_injector.go
  pkg/webhook/admission/pod/mutator.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
Labels: approved, lgtm, ok-to-test, size/S

#646 Added licenses.
  hack/generate-licenses.sh
  third_party/library/license.txt
  third_party/library/license_go.txt
  third_party/library/license_python.txt
Labels: approved, lgtm, size/XXL

#647 Update reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#649 Enabled test_sklearn.py, etc. to run in an env without ext load balancer
  test/e2e/common/utils.py
Labels: approved, lgtm, size/XS
