Repository kserve/kserve, pull requests merged in 2020-10, with the labels that each got.

#1110 Fix typo in benchmark doc
  test/benchmark/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1055 Harden model puller logic and add tests
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/agent/agent_suite_test.go
  pkg/agent/downloader.go
  pkg/agent/puller.go
  pkg/agent/storage/provider.go
  pkg/agent/storage/s3.go
  pkg/agent/syncer.go
  pkg/agent/watcher.go
  pkg/agent/watcher_test.go
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/kfserving/kfserver.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_server.py
Labels: lgtm, size/XL

#1113 Update Triton repo links
  docs/apis/README.md
  docs/predict-api/v2/README.md
  docs/samples/triton/bert/bert_tokenizer/Dockerfile
  pkg/apis/serving/v1alpha2/framework_triton.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1beta1/predictor.go
  python/kfserving/docs/V1alpha2PredictorSpec.md
  python/kfserving/kfserving/models/v1alpha2_predictor_spec.py
Labels: approved, lgtm, ok-to-test, size/S

#1115 Add instruction from #977 to the developer guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/S

#1118 Correction for the sample invocation of pytorchserver
  docs/samples/pytorch/README.md
Labels: approved, lgtm, size/XS

#1103 Make standalone installation kustomizable.
  config/certmanager/certificate.yaml
  config/configmap/inferenceservice.yaml
  config/default/cainjection_conversion_webhook.yaml
  config/default/inferenceservice_conversion_webhook.yaml
  config/default/kustomization.yaml
  config/default/params.env
  config/default/params.yaml
  config/default/webhookcainjection_patch.yaml
  config/overlays/kubeflow/kustomization.yaml
  config/overlays/kubeflow/params.env
  config/rbac/leader_election_role_binding.yaml
  config/webhook/manifests.yaml
  hack/generate-install.sh
Labels: approved, lgtm, ok-to-test, size/L

#1121 Use kfserving-examples gs bucket
  docs/samples/onnx/onnx.yaml
  docs/samples/triton/bert/bert.yaml
Labels: lgtm, size/XS

#1122 Fixed issues on openshift
  cmd/manager/main.go
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/rbac/role.yaml
  config/webhook/service.yaml
  pkg/controller/v1alpha2/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller.go
Labels: approved, lgtm, size/XXL

#1125 add a comma at the end of ingressGateway name
  config/default/params.env
  config/overlays/kubeflow/params.env
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1126 use "kustomize build" instead of "kubectl kustomize"
  config/default/kustomization.yaml
  config/overlays/kubeflow/kustomization.yaml
  hack/generate-install.sh
Labels: approved, lgtm, ok-to-test, size/XS

#1134 Add inferenceservice finalizer rbac rules
  config/rbac/role.yaml
  pkg/controller/v1alpha2/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller.go
Labels: approved, lgtm, size/XS

#1114 Add David Goodwin as approver
  OWNERS
Labels: approved, lgtm, size/XS

#1137 Cherry pick kfserving sdk dependency fix
  python/alibiexplainer/setup.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_storage.py
  test/scripts/run-e2e-tests.sh
Labels: approved, size/S

#1136 Cherry-pick of OpenShift fixes (#1122 and #1134) to release-0.4
  cmd/manager/main.go
  config/rbac/role.yaml
  config/webhook/service.yaml
  pkg/controller/inferenceservice/controller.go
Labels: approved, lgtm, size/M

#1140 fix conditional in ONNX storage URI validation
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1146 Release 0.4.1 for OpenShift
  config/configmap/inferenceservice.yaml
  docs/samples/explanation/aix/mnist/aix-explainer-v1alpha2.yaml
  docs/samples/explanation/aix/mnist/aix-explainer.yaml
  docs/samples/explanation/aix/mnist/rfserver/rf.Dockerfile
  docs/samples/transformer/image_transformer/setup.py
  hack/generate-install.sh
  install/v0.4.1/kfserving.yaml
  python/aixexplainer/setup.py
  python/alibiexplainer/setup.py
  python/kfserving/setup.py
  python/pytorchserver/README.md
  python/pytorchserver/setup.py
  python/sklearnserver/README.md
  python/sklearnserver/setup.py
  python/xgbserver/README.md
  python/xgbserver/setup.py
Labels: approved, lgtm, size/XXL

#1152 Update developer guide knative links
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#1157 Add yq as dep in developer guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/XS

#1128 Support Kubernetes 1.18
  config/crd/kustomization.yaml
  config/crd/patches/protocol.yaml
  docs/samples/custom/prebuilt-image/custom.yaml
  docs/samples/v1beta1/custom/simple.yaml
  docs/samples/v1beta1/tensorflow/grpc.yaml
Labels: approved, lgtm, size/M

#1144 upgrade k8s and kn go library versions
  Dockerfile
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/crd/serving.kubeflow.org_trainedmodels.yaml
  go.mod
  go.sum
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/inferenceservice.go
  pkg/controller/v1alpha2/inferenceservice/suite_test.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  pkg/controller/v1beta1/trainedmodel/controller_test.go
  pkg/controller/v1beta1/trainedmodel/suite_test.go
  pkg/testing/envtest_setup.go
  test/README.md
Labels: approved, lgtm, size/XXL

#1166 bump up minimal Kube and Istio requirements
  README.md
Labels: approved, lgtm, size/S

#1169 Cherry-pick of 'Support Kubernetes 1.18' (#1128) to release-0.4
  config/crd/kustomization.yaml
  config/crd/patches/protocol.yaml
  docs/samples/custom/prebuilt-image/custom.yaml
Labels: lgtm, size/M
