Repository kserve/kserve, pull requests merged in 2020-12, with the labels that each got.

#1208 Update Outlier and Drift examples for latest knative and cloudevents
  docs/samples/drift-detection/alibi-detect/cifar10/.gitignore
  docs/samples/drift-detection/alibi-detect/cifar10/README.md
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10.yaml
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10_drift.ipynb
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10cd.yaml
  docs/samples/drift-detection/alibi-detect/cifar10/message-dumper.yaml
  docs/samples/drift-detection/alibi-detect/cifar10/trigger.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/.gitignore
  docs/samples/outlier-detection/alibi-detect/cifar10/README.md
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10_outlier.ipynb
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10od.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/message-dumper.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/requirements_notebook.txt
  docs/samples/outlier-detection/alibi-detect/cifar10/trigger.yaml
  pkg/logger/worker.go
Labels: approved, lgtm, size/XXL

#1231 Fix sklearn/xgboost protocol configmap for v1alpha2 defaulter
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/controller/v1alpha2/inferenceservice/resources/knative/service_test.go
Labels: approved, size/L

#1236 Fix: Missing API version in the samples path
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1235 Add adriangonz as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#1186 Feature: Add model archive and config generator for torchserve
  docs/samples/v1beta1/torchserve/model-archiver/README.md
  docs/samples/v1beta1/torchserve/model-archiver/model-archiver-image/Dockerfile
  docs/samples/v1beta1/torchserve/model-archiver/model-archiver-image/README.md
  docs/samples/v1beta1/torchserve/model-archiver/model-archiver-image/dockerd-entrypoint.sh
  docs/samples/v1beta1/torchserve/model-archiver/model-archiver.yaml
  docs/samples/v1beta1/torchserve/model-archiver/model-store/README.md
  docs/samples/v1beta1/torchserve/model-archiver/model-store/densenet_161/index_to_name.json
  docs/samples/v1beta1/torchserve/model-archiver/model-store/densenet_161/model.py
  docs/samples/v1beta1/torchserve/model-archiver/model-store/mnist/mnist.py
  docs/samples/v1beta1/torchserve/model-archiver/model-store/mnist/mnist_handler.py
  docs/samples/v1beta1/torchserve/model-archiver/model-store/properties.json
  docs/samples/v1beta1/torchserve/model-archiver/pv.yaml
  docs/samples/v1beta1/torchserve/model-archiver/pvc.yaml
  docs/samples/v1beta1/torchserve/model-archiver/pvpod.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#1223 Consolidate logger to model agent sidecar and add readiness probe to model container
  .github/workflows/batcher-docker-publisher.yml
  agent.Dockerfile
  cmd/agent/execprobe.go
  cmd/agent/main.go
  cmd/logger/main.go
  config/overlays/test/configmap/inferenceservice.yaml
  go.mod
  go.sum
  hack/image_patch_dev.sh
  logger.Dockerfile
  pkg/constants/constants.go
  pkg/controller/v1alpha2/inferenceservice/resources/knative/service.go
  pkg/controller/v1alpha2/inferenceservice/suite_test.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/logger/collector.go
  pkg/logger/constants.go
  pkg/logger/dispatcher.go
  pkg/logger/handler.go
  pkg/logger/handler_test.go
  pkg/logger/worker.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
  pkg/webhook/admission/pod/logger_injector.go
  pkg/webhook/admission/pod/logger_injector_test.go
  pkg/webhook/admission/pod/mutator.go
  test/e2e/logger/test_logger.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1202 Feature: Add torchserve metrics
  docs/samples/custom/torchserve/docs/images/grafana.png
  docs/samples/custom/torchserve/docs/images/prometheus.png
  docs/samples/custom/torchserve/docs/images/prometheus_graph.png
  docs/samples/custom/torchserve/docs/metrics.md
  docs/samples/custom/torchserve/metrics.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#1239 Update metrics service label and selector
  config/rbac/auth_proxy_service.yaml
Labels: approved, lgtm, size/XS

#1228 Feature: Add torchserve logger
  docs/samples/custom/torchserve/README.md
  docs/samples/custom/torchserve/logger/README.md
  docs/samples/custom/torchserve/logger/logger_demo.ipynb
  docs/samples/custom/torchserve/logger/message-dumper.yaml
  docs/samples/custom/torchserve/logger/torchserve-logger.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#1245 Fix minio python client version
  python/kfserving/requirements.txt
Labels: approved, lgtm, size/XS

#1238 Update and fix kafka example for v1beta1
  Dockerfile
  docs/samples/kafka/README.md
  docs/samples/kafka/image_transformer/image_transformer.py
  docs/samples/kafka/kafka-source.yaml
  docs/samples/kafka/minio.yaml
  docs/samples/kafka/mnist_kafka.yaml
  docs/samples/kafka/s3_secret.yaml
  docs/samples/kafka/transformer.Dockerfile
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/explainer_aix360.go
  pkg/apis/serving/v1beta1/explainer_alibi.go
  pkg/apis/serving/v1beta1/explainer_custom.go
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_triton.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/constants/constants.go
  pkg/controller/v1alpha2/inferenceservice/controller_test.go
  pkg/controller/v1alpha2/inferenceservice/resources/istio/virtualservice_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Labels: approved, lgtm, size/L

#1161 Add torchserve to v1beta1 spec
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/transformer/torchserve_image_transformer/README.md
  docs/samples/transformer/torchserve_image_transformer/image_transformer/__init__.py
  docs/samples/transformer/torchserve_image_transformer/image_transformer/__main__.py
  docs/samples/transformer/torchserve_image_transformer/image_transformer/image_transformer.py
  docs/samples/transformer/torchserve_image_transformer/image_transformer/transformer_model_repository.py
  docs/samples/transformer/torchserve_image_transformer/setup.py
  docs/samples/transformer/torchserve_image_transformer/transformer.Dockerfile
  docs/samples/v1beta1/torchserve/README.md
  docs/samples/v1beta1/torchserve/autoscaling.yaml
  docs/samples/v1beta1/torchserve/canary.yaml
  docs/samples/v1beta1/torchserve/config.properties
  docs/samples/v1beta1/torchserve/docs/autoscaling.md
  docs/samples/v1beta1/torchserve/docs/canary.md
  docs/samples/v1beta1/torchserve/docs/metrics.md
  docs/samples/v1beta1/torchserve/gpu.yaml
  docs/samples/v1beta1/torchserve/imgconv/0.png
  docs/samples/v1beta1/torchserve/imgconv/1.png
  docs/samples/v1beta1/torchserve/imgconv/README.md
  docs/samples/v1beta1/torchserve/imgconv/img2bytearray.py
  docs/samples/v1beta1/torchserve/imgconv/input.json
  docs/samples/v1beta1/torchserve/metrics.yaml
  docs/samples/v1beta1/torchserve/mnist.json
  docs/samples/v1beta1/torchserve/model-archiver/README.md
  docs/samples/v1beta1/torchserve/pv.yaml
  docs/samples/v1beta1/torchserve/pvc.yaml
  docs/samples/v1beta1/torchserve/pvpod.yaml
  docs/samples/v1beta1/torchserve/torchserve.yaml
  docs/samples/v1beta1/torchserve/transformer.yaml
  go.sum
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller.go
Labels: approved, lgtm, ok-to-test, size/XXL

#1250 Cut Release 0.5.0-rc1 for torchserve integration test
  config/configmap/inferenceservice.yaml
  hack/generate-install.sh
  install/v0.5.0-rc1/kfserving.yaml
Labels: approved, lgtm, size/XXL

#1252 Fix: image converter for torchserve
  docs/samples/v1beta1/torchserve/imgconv/img2bytearray.py
Labels: approved, lgtm, needs-ok-to-test, size/S

#1255 Fix: Wrong link to README.md for ONNX InferenceService
  docs/samples/v1alpha2/onnx/mosaic-onnx.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#1260 Fix: mosaic-onnx sample for ONNX InferenceService
  docs/samples/v1alpha2/onnx/mosaic-onnx.ipynb
Labels: approved, lgtm, needs-ok-to-test, size/S

#1149 Introduce defaultTimeout for predictor and apply in tfserving
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/apis/README.md
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorflow_test.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/controller/v1alpha2/inferenceservice/controller_test.go
  pkg/controller/v1alpha2/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/v1alpha2/inferenceservice/resources/knative/service_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
Labels: approved, lgtm, size/L

#1263 Fix: Update inference config map with torchserve 0.3
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  hack/quick_install.sh
Labels: approved, lgtm, needs-ok-to-test, size/S

#1213 Support LightGBM server
  .github/workflows/lightgbm-docker-publish.yml
  .github/workflows/python-test.yml
  Makefile
  cmd/manager/main.go
  cmd/spec-gen/main.go
  config/configmap/inferenceservice.yaml
  config/crd/patches/protocol.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/lightgbm/README.md
  docs/samples/lightgbm/iris-input.json
  docs/samples/lightgbm/lightgbm.yaml
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/framework_lightgbm.go
  pkg/apis/serving/v1alpha2/framework_lightgbm_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_conversion.go
  pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/apis/serving/v1beta1/predictor_lightgbm.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  python/kfserving/docs/V1alpha2LightGBMSpec.md
  python/kfserving/docs/V1alpha2PredictorSpec.md
  python/kfserving/docs/V1beta1LightGBMSpec.md
  python/kfserving/docs/V1beta1PredictorSpec.md
  python/kfserving/docs/V1beta1PredictorsConfig.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/v1alpha2_light_gbm_spec.py
  python/kfserving/kfserving/models/v1alpha2_predictor_spec.py
  python/kfserving/kfserving/models/v1beta1_light_gbm_spec.py
  python/kfserving/kfserving/models/v1beta1_predictor_spec.py
  python/kfserving/kfserving/models/v1beta1_predictors_config.py
  python/kfserving/test/test_v1alpha2_light_gbm_spec.py
  python/kfserving/test/test_v1beta1_light_gbm_spec.py
  python/lgb.Dockerfile
  python/lgbserver/Makefile
  python/lgbserver/README.md
  python/lgbserver/lgbserver/__init__.py
  python/lgbserver/lgbserver/__main__.py
  python/lgbserver/lgbserver/example_model/model/model.bst
  python/lgbserver/lgbserver/lightgbm_model_repository.py
  python/lgbserver/lgbserver/model.py
  python/lgbserver/lgbserver/test_lightgbm_model_repository.py
  python/lgbserver/lgbserver/test_model.py
  python/lgbserver/setup.py
  test/e2e/common/utils.py
  test/e2e/data/iris_input_v3.json
  test/e2e/predictor/test_lightgbm.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/XXL

#1261 Fix: Missing link to Python SDK samples
  python/kfserving/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1264 Fix: Change folder structure
  docs/samples/README.md
  docs/samples/v1beta1/custom/torchserve/README.md
  docs/samples/v1beta1/custom/torchserve/autoscale.yaml
  docs/samples/v1beta1/custom/torchserve/bert-sample/bert.yaml
  docs/samples/v1beta1/custom/torchserve/bert-sample/hugging-face-bert-sample.md
  docs/samples/v1beta1/custom/torchserve/canary.yaml
  docs/samples/v1beta1/custom/torchserve/custom-server-with-external-storage.md
  docs/samples/v1beta1/custom/torchserve/docs/autoscaling.md
  docs/samples/v1beta1/custom/torchserve/docs/canary.md
  docs/samples/v1beta1/custom/torchserve/docs/images/grafana.png
  docs/samples/v1beta1/custom/torchserve/docs/images/prometheus.png
  docs/samples/v1beta1/custom/torchserve/docs/images/prometheus_graph.png
  docs/samples/v1beta1/custom/torchserve/docs/metrics.md
  docs/samples/v1beta1/custom/torchserve/gpu.yaml
  docs/samples/v1beta1/custom/torchserve/logger/README.md
  docs/samples/v1beta1/custom/torchserve/logger/logger_demo.ipynb
  docs/samples/v1beta1/custom/torchserve/logger/message-dumper.yaml
  docs/samples/v1beta1/custom/torchserve/logger/torchserve-logger.yaml
  docs/samples/v1beta1/custom/torchserve/metrics.yaml
  docs/samples/v1beta1/custom/torchserve/pv.yaml
  docs/samples/v1beta1/custom/torchserve/pvc.yaml
  docs/samples/v1beta1/custom/torchserve/pvpod.yaml
  docs/samples/v1beta1/custom/torchserve/torchserve-custom-pv.yaml
  docs/samples/v1beta1/custom/torchserve/torchserve-custom.yaml
  docs/samples/v1beta1/custom/torchserve/torchserve-image/Dockerfile
  docs/samples/v1beta1/custom/torchserve/torchserve-image/README.md
  docs/samples/v1beta1/custom/torchserve/torchserve-image/config.properties
  docs/samples/v1beta1/custom/torchserve/torchserve-image/dockerd-entrypoint.sh
  docs/samples/v1beta1/custom/torchserve/torchserve-image/model-store/.gitignore
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1268 Fix: Update readme docs, broken links
  docs/samples/v1beta1/torchserve/README.md
  docs/samples/v1beta1/torchserve/docs/autoscaling.md
  docs/samples/v1beta1/torchserve/docs/canary.md
  docs/samples/v1beta1/torchserve/docs/images/grafana.png
  docs/samples/v1beta1/torchserve/docs/images/prometheus.png
  docs/samples/v1beta1/torchserve/docs/images/prometheus_graph.png
  docs/samples/v1beta1/torchserve/docs/metrics.md
  docs/samples/v1beta1/torchserve/imgconv/input.json
Labels: approved, lgtm, needs-ok-to-test, size/S

#1269 Fix: Use istio's grafana and prometheus addons for torchserve metrics
  docs/samples/v1beta1/torchserve/README.md
  docs/samples/v1beta1/torchserve/docs/metrics.md
  docs/samples/v1beta1/torchserve/metrics.yaml
  hack/quick_install.sh
Labels: approved, lgtm, ok-to-test, size/L

#1265 Feature: Add e2e test for torchserve
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  test/e2e/data/torchserve_input.json
  test/e2e/predictor/test_torchserve.py
Labels: approved, lgtm, ok-to-test, size/L

#1271 Update torchserve docs
  docs/samples/v1beta1/torchserve/README.md
  docs/samples/v1beta1/torchserve/autoscaling/README.md
  docs/samples/v1beta1/torchserve/autoscaling/autoscaling.yaml
  docs/samples/v1beta1/torchserve/bert/README.md
  docs/samples/v1beta1/torchserve/bert/bert.yaml
  docs/samples/v1beta1/torchserve/bert/config.properties
  docs/samples/v1beta1/torchserve/bert/sample_text.txt
  docs/samples/v1beta1/torchserve/canary/README.md
  docs/samples/v1beta1/torchserve/canary/canary.yaml
  docs/samples/v1beta1/torchserve/config.properties
  docs/samples/v1beta1/torchserve/docs/autoscaling.md
  docs/samples/v1beta1/torchserve/docs/canary.md
  docs/samples/v1beta1/torchserve/metrics/README.md
  docs/samples/v1beta1/torchserve/metrics/images/grafana.png
  docs/samples/v1beta1/torchserve/metrics/images/prometheus.png
  docs/samples/v1beta1/torchserve/metrics/images/prometheus_graph.png
  docs/samples/v1beta1/torchserve/metrics/metrics.yaml
  docs/samples/v1beta1/torchserve/model-archiver/README.md
  docs/samples/v1beta1/torchserve/pv.yaml
  docs/samples/v1beta1/torchserve/pvc.yaml
  docs/samples/v1beta1/torchserve/pvpod.yaml
Labels: approved, size/XL

#1270 Generate v1beta1 API docs
  Makefile
  README.md
  docs/apis/Dockerfile
  docs/apis/v1alpha2/README.md
  docs/apis/v1beta1/README.md
  pkg/apis/serving/v1beta1/explainer.go
  pkg/apis/serving/v1beta1/explainer_alibi.go
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/transformer.go
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/models/v1beta1_trained_model.py
  python/kfserving/kfserving/models/v1beta1_trained_model_list.py
  python/kfserving/kfserving/models/v1beta1_trained_model_spec.py
  python/kfserving/kfserving/models/v1beta1_trained_model_status.py
  python/kfserving/test/test_v1beta1_trained_model.py
  python/kfserving/test/test_v1beta1_trained_model_list.py
  python/kfserving/test/test_v1beta1_trained_model_spec.py
  python/kfserving/test/test_v1beta1_trained_model_status.py
Labels: approved, lgtm, size/XXL
