Repository kserve/kserve, pull requests merged in 2020-06, with the labels that each got.

#855 Renaming ellis-bigelow -> ellistarn
  OWNERS
Labels: approved, lgtm, size/XS

#853 Add new KFServing sample for GCP IAP
  docs/samples/README.md
  docs/samples/gcp-iap/README.md
  docs/samples/gcp-iap/iris-input.json
  docs/samples/gcp-iap/make-prediction.sh
  docs/samples/gcp-iap/sklearn-iap-no-authz.yaml
  docs/samples/gcp-iap/sklearn-iap-with-authz.yaml
  docs/samples/gcp-iap/virtual-service.yaml
Labels: approved, lgtm, ok-to-test, size/L

#856 fix the wrong prebuild image address
  docs/samples/triton/bert/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#747 Triton naming
  docs/apis/README.md
  docs/predict-api/v2/required_api.md
  docs/samples/azure/README.md
  docs/samples/triton/simple_string/README.md
  docs/samples/triton/simple_string/triton.yaml
  python/kfserving/README.md
  python/kfserving/test/test_azure_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#864 Alibi explainer fix
  python/alibiexplainer.Dockerfile
  python/alibiexplainer/setup.py
  python/pytorch.Dockerfile
Labels: approved, lgtm, size/XS

#865 tabular explainer e2e test
  test/e2e/common/utils.py
  test/e2e/data/income_input.json
  test/e2e/explainer/__init__.py
  test/e2e/explainer/test_tabular_explainer.py
Labels: approved, lgtm, size/L

#875 Updates for Alibi use in v0.3.0 release
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/income/income_explanations.ipynb
  install/v0.3.0/kfserving.yaml
Labels: approved, lgtm, size/S

#879 Fix broken helm istio install in CI
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/M

#876 Record Events when InferenceService goes in and out of readiness
  pkg/apis/serving/v1alpha2/inferenceservice_status.go
  pkg/controller/inferenceservice/controller.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
Labels: approved, lgtm, ok-to-test, size/L

#882 Add requirement.txt to pypi source pacakge
  python/kfserving/MANIFEST.in
  python/kfserving/setup.py
Labels: approved, lgtm, size/XS

#886 Update to CloudEvents V1 protocol
  docs/samples/drift-detection/alibi-detect/cifar10/README.md
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10_drift.ipynb
  docs/samples/outlier-detection/alibi-detect/cifar10/README.md
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10_outlier.ipynb
  go.mod
  go.sum
  pkg/logger/worker.go
Labels: approved, lgtm, size/M

#887 Fix lack of event patching in ClusterRole
  Makefile
  config/default/kustomization.yaml
  config/default/rbac/role.yaml
  pkg/controller/inferenceservice/controller.go
Labels: approved, lgtm, ok-to-test, size/L

#888 Add additional unit tests to event Recorder
  pkg/apis/serving/v1alpha2/inferenceservice_status.go
  pkg/controller/inferenceservice/controller.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
Labels: approved, lgtm, ok-to-test, size/L

#878 A sample for gRPC Server in custom model
  docs/samples/custom/grpc-server/Dockerfile
  docs/samples/custom/grpc-server/README.md
  docs/samples/custom/grpc-server/client/client.go
  docs/samples/custom/grpc-server/grpc-service.yaml
  docs/samples/custom/grpc-server/proto/helloworld.pb.go
  docs/samples/custom/grpc-server/proto/helloworld.proto
  docs/samples/custom/grpc-server/server.go
Labels: approved, lgtm, ok-to-test, size/XL

#893 Move KFServing to minimally require kubernetes 1.15
  Makefile
  config/default/manager/manager.yaml
  config/default/webhook/manifests.yaml
  config/overlays/development/configmap/ko_resolve_logger
  go.mod
  hack/quick_install.sh
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/S

#847 Add batcher module.
  Makefile
  batcher.Dockerfile
  cmd/batcher/main.go
  config/default/configmap/inferenceservice.yaml
  config/overlays/development/configmap/ko_resolve_batcher
  config/overlays/test/configmap/inferenceservice.yaml
  docs/diagrams/batcher.jpg
  docs/samples/batcher/README.md
  docs/samples/batcher/basic/README.md
  docs/samples/batcher/basic/input.json
  docs/samples/batcher/basic/pytorch-batcher.yaml
  go.mod
  go.sum
  hack/image_patch_dev.sh
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/batcher/conf/app.conf
  pkg/batcher/controllers/main_controller.go
  pkg/batcher/routers/router.go
  pkg/batcher/server.go
  pkg/batcher/server_test.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/webhook/admission/pod/batcher_injector.go
  pkg/webhook/admission/pod/batcher_injector_test.go
  pkg/webhook/admission/pod/mutator.go
  python/kfserving/README.md
  python/kfserving/docs/V1alpha2Batcher.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/v1alpha2_batcher.py
  python/kfserving/kfserving/models/v1alpha2_deployment_spec.py
  python/kfserving/kfserving/models/v1alpha2_explainer_spec.py
  python/kfserving/kfserving/models/v1alpha2_predictor_spec.py
  python/kfserving/kfserving/models/v1alpha2_transformer_spec.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_v1alpha2_batcher.py
  release/triggers/latest/batcher.yaml
  release/triggers/tagged/batcher.yaml
  test/e2e/batcher/__init__.py
  test/e2e/batcher/test_batcher.py
  test/scripts/build-batcher.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/XXL

#896 Fix batcher format issue and generate CRD in serving.kubeflow.org_inferenceservices.yaml.
  cmd/batcher/main.go
  config/default/crds/base/serving.kubeflow.org_inferenceservices.yaml
  pkg/batcher/controllers/main_controller.go
  pkg/batcher/routers/router.go
  pkg/batcher/server.go
  pkg/batcher/server_test.go
  pkg/webhook/admission/pod/batcher_injector.go
  pkg/webhook/admission/pod/batcher_injector_test.go
Labels: approved, lgtm, ok-to-test, size/L

#861 Update KFServing roadmap for Q3/Q4
  ROADMAP.md
Labels: approved, lgtm, size/M

#889 Enhance SDK watch API to avoid traceback
  python/kfserving/kfserving/api/kf_serving_watch.py
Labels: approved, lgtm, size/S

#899 Fix Flakey Controller Tests
  pkg/controller/inferenceservice/controller_test.go
Labels: approved, lgtm, ok-to-test, size/S

#897 Update KFServing docs
  README.md
  docs/samples/README.md
  docs/samples/autoscaling/README.md
  docs/samples/bentoml/README.md
  docs/samples/custom-domain/README.md
  docs/samples/custom/hello-world/README.md
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/gcp-iap/README.md
  docs/samples/kafka/README.md
  docs/samples/onnx/README.md
  docs/samples/pytorch/README.md
  docs/samples/rollouts/README.md
  docs/samples/s3/README.md
  docs/samples/sklearn/README.md
  docs/samples/sklearn/perf.yaml
  docs/samples/tensorflow/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/triton/simple_string/README.md
  docs/samples/xgboost/README.md
  hack/quick_install.sh
Labels: approved, lgtm, size/L

#900 Fix Test KFServing Installation in the main README
  README.md
  docs/samples/sklearn/perf.yaml
Labels: approved, lgtm, size/XS

#901 Fix kustomize config to conform to kubebuilder v2 layout
  Makefile
  PROJECT
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/configmap/inferenceservice.yaml
  config/configmap/kustomization.yaml
  config/crd/kustomization.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/default/certmanager/kustomize.yaml
  config/default/certmanager/kustomizeconfig.yaml
  config/default/crds/base/serving.kubeflow.org_inferenceservices.yaml
  config/default/crds/kustomization.yaml
  config/default/crds/patches/crd_status_patch.yaml
  config/default/kustomization.yaml
  config/default/webhook/kustomization.yaml
  config/default/webhook/kustomizeconfig.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/service.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  go.mod
  go.sum
  hack/image_patch_dev.sh
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/testing/envtest_setup.go
Labels: approved, lgtm, size/XXL
