Repository kserve/kserve, pull requests merged in 2020-11, with the labels that each got.

#1175 update v0.4.1 release yaml
  install/v0.4.1/kfserving.yaml
Labels: approved, lgtm, size/XS

#1170 Move KFServing CI to AWS
  config/overlays/test/configmap/inferenceservice.yaml
  config/overlays/test/manager_image_patch.yaml
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  python/kfserving/test/test_storage.py
  python/pytorch-gpu.Dockerfile
  test/e2e/common/utils.py
  test/e2e/explainer/test_tabular_explainer.py
  test/e2e/predictor/test_pytorch.py
  test/e2e/transformer/test_transformer.py
  test/scripts/create-cluster.sh
  test/scripts/delete-cluster.sh
  test/scripts/run-e2e-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/L

#1176 update 0.4.1 yaml
  install/v0.4.1/kfserving.yaml
Labels: approved, lgtm, size/XS

#1165 Improve README
  README.md
Labels: approved, lgtm, size/XS

#1172 Allow unknown fields when unmarshalling istio resources
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#1155 Add support for MLServer in the SKLearn predictor
  config/configmap/inferenceservice.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/v1beta1/sklearn/README.md
  docs/samples/v1beta1/sklearn/iris-input.json
  docs/samples/v1beta1/sklearn/model-settings.json
  docs/samples/v1beta1/sklearn/model.joblib
  docs/samples/v1beta1/sklearn/requirements.txt
  docs/samples/v1beta1/sklearn/sklearn.yaml
  hack/violation_exceptions.list
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/constants/mlserver.go
  python/kfserving/docs/V1beta1AIXExplainerSpec.md
  python/kfserving/docs/V1beta1AlibiExplainerSpec.md
  python/kfserving/docs/V1beta1CustomExplainer.md
  python/kfserving/docs/V1beta1CustomPredictor.md
  python/kfserving/docs/V1beta1CustomTransformer.md
  python/kfserving/docs/V1beta1InferenceService.md
  python/kfserving/docs/V1beta1InferenceServiceStatus.md
  python/kfserving/docs/V1beta1ONNXRuntimeSpec.md
  python/kfserving/docs/V1beta1PredictorExtensionSpec.md
  python/kfserving/docs/V1beta1PredictorProtocols.md
  python/kfserving/docs/V1beta1PredictorsConfig.md
  python/kfserving/docs/V1beta1SKLearnSpec.md
  python/kfserving/docs/V1beta1TFServingSpec.md
  python/kfserving/docs/V1beta1TorchServeSpec.md
  python/kfserving/docs/V1beta1TrainedModelStatus.md
  python/kfserving/docs/V1beta1TritonSpec.md
  python/kfserving/docs/V1beta1XGBoostSpec.md
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/v1beta1_aix_explainer_spec.py
  python/kfserving/kfserving/models/v1beta1_alibi_explainer_spec.py
  python/kfserving/kfserving/models/v1beta1_custom_explainer.py
  python/kfserving/kfserving/models/v1beta1_custom_predictor.py
  python/kfserving/kfserving/models/v1beta1_custom_transformer.py
  python/kfserving/kfserving/models/v1beta1_inference_service_status.py
  python/kfserving/kfserving/models/v1beta1_onnx_runtime_spec.py
  python/kfserving/kfserving/models/v1beta1_predictor_extension_spec.py
  python/kfserving/kfserving/models/v1beta1_predictor_protocols.py
  python/kfserving/kfserving/models/v1beta1_predictors_config.py
  python/kfserving/kfserving/models/v1beta1_sk_learn_spec.py
  python/kfserving/kfserving/models/v1beta1_tf_serving_spec.py
  python/kfserving/kfserving/models/v1beta1_torch_serve_spec.py
  python/kfserving/kfserving/models/v1beta1_trained_model_status.py
  python/kfserving/kfserving/models/v1beta1_triton_spec.py
  python/kfserving/kfserving/models/v1beta1_xg_boost_spec.py
  python/kfserving/test/test_v1beta1_predictor_protocols.py
  test/e2e/common/utils.py
  test/e2e/data/iris_input_v2.json
  test/e2e/predictor/test_sklearn.py
Labels: approved, lgtm, ok-to-test, size/XXL

#1184 update README.md about sample of sklearn for testing the SKLearn Serv…
  docs/samples/sklearn/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1193 Update KFServing SDK Example link. Old link no longer exists
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1194 config: Fix port number of webhook in manager Pod
  config/manager/manager.yaml
  config/webhook/service.yaml
Labels: approved, lgtm, size/XS

#1168 Alibi 0.5.5
  docs/samples/explanation/alibi/imagenet/imagenet.yaml
  docs/samples/explanation/alibi/income/income.yaml
  docs/samples/explanation/alibi/income/income_explanations.ipynb
  docs/samples/explanation/alibi/income/requirements.txt
  docs/samples/explanation/alibi/moviesentiment/movie_review_explanations.ipynb
  python/.pylintrc
  python/alibiexplainer/alibiexplainer/anchor_text.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/setup.py
  python/alibiexplainer/tests/__init__.py
  python/alibiexplainer/tests/test_anchor_images.py
  python/alibiexplainer/tests/test_anchor_tabular.py
Labels: approved, lgtm, size/M

#1185 Feature: Add torchserve custom server bert sample
  docs/samples/custom/torchserve/bert-sample/bert.yaml
  docs/samples/custom/torchserve/bert-sample/hugging-face-bert-sample.md
Labels: approved, lgtm, needs-ok-to-test, size/L

#1141 support PMML server
  Makefile
  config/configmap/inferenceservice.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/pmml/README.md
  docs/samples/pmml/pmml-input.json
  docs/samples/pmml/pmml.yaml
  docs/samples/v1beta1/pmml/pmml.yaml
  go.mod
  go.sum
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/framework_pmml.go
  pkg/apis/serving/v1alpha2/inferenceservice_conversion.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/podspec.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  python/kfserving/docs/V1alpha2InferenceService.md
  python/kfserving/docs/V1alpha2PMMLSpec.md
  python/kfserving/docs/V1alpha2PredictorSpec.md
  python/kfserving/docs/V1beta1PMMLSpec.md
  python/kfserving/docs/V1beta1PredictorSpec.md
  python/kfserving/docs/V1beta1PredictorsConfig.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/knative_status.py
  python/kfserving/kfserving/models/net_url_userinfo.py
  python/kfserving/kfserving/models/v1_time.py
  python/kfserving/kfserving/models/v1alpha2_pmml_spec.py
  python/kfserving/kfserving/models/v1alpha2_predictor_spec.py
  python/kfserving/kfserving/models/v1beta1_pmml_spec.py
  python/kfserving/kfserving/models/v1beta1_predictor_spec.py
  python/kfserving/kfserving/models/v1beta1_predictors_config.py
  python/kfserving/test/test_v1alpha2_pmml_spec.py
  python/kfserving/test/test_v1beta1_pmml_spec.py
  python/pmml.Dockerfile
  python/pmmlserver/Makefile
  python/pmmlserver/README.md
  python/pmmlserver/pmmlserver/__init__.py
  python/pmmlserver/pmmlserver/__main__.py
  python/pmmlserver/pmmlserver/example_model/model/model.pmml
  python/pmmlserver/pmmlserver/model.py
  python/pmmlserver/pmmlserver/test_model.py
  python/pmmlserver/setup.py
  test/e2e/data/pmml_input.json
  test/e2e/predictor/test_pmml.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, ok-to-test, size/XXL

#1156 Feature: Add torchserve custom server
  docs/samples/custom/torchserve/README.md
  docs/samples/custom/torchserve/autoscale.yaml
  docs/samples/custom/torchserve/canary.yaml
  docs/samples/custom/torchserve/docs/autoscaling.md
  docs/samples/custom/torchserve/docs/canary.md
  docs/samples/custom/torchserve/gpu.yaml
  docs/samples/custom/torchserve/torchserve-custom.yaml
  docs/samples/custom/torchserve/torchserve-image/Dockerfile
  docs/samples/custom/torchserve/torchserve-image/README.md
  docs/samples/custom/torchserve/torchserve-image/config.properties
  docs/samples/custom/torchserve/torchserve-image/dockerd-entrypoint.sh
  docs/samples/custom/torchserve/torchserve-image/model-store/.gitignore
Labels: approved, lgtm, ok-to-test, size/L

#1182 Feature: Add torchserve custom server with pv storage
  docs/samples/custom/torchserve/custom-server-with-external-storage.md
  docs/samples/custom/torchserve/pv.yaml
  docs/samples/custom/torchserve/pvc.yaml
  docs/samples/custom/torchserve/pvpod.yaml
  docs/samples/custom/torchserve/torchserve-custom-pv.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#1201 update knative version
  README.md
Labels: approved, lgtm, size/XS

#1198 Publish KFServing 0.5 RC0 release
  .github/workflows/agent-docker-publish.yml
  .github/workflows/pmml-docker-publish.yml
  Makefile
  config/configmap/inferenceservice.yaml
  config/crd/patches/protocol.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  docs/samples/explanation/alibi/income/README.md
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.5.0-rc0/kfserving.yaml
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  python/aixexplainer/setup.py
  python/alibiexplainer/setup.py
  python/alibiexplainer/tests/test_anchor_tabular.py
  python/pmmlserver/setup.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/xgbserver/setup.py
  test/e2e/explainer/test_tabular_explainer.py
Labels: approved, lgtm, size/XXL

#1204 Sync from model config on agent startup
  hack/image_patch_dev.sh
  pkg/agent/storage/s3.go
  pkg/agent/syncer.go
  pkg/agent/watcher.go
  pkg/agent/watcher_test.go
  pkg/apis/serving/v1beta1/predictor_triton.go
Labels: approved, lgtm, size/L

#1195 Create github action for python testing and pypi publishing
  .github/workflows/python-publish.yml
  .github/workflows/python-test.yml
  .gitignore
  hack/boilerplate.sh
  hack/update-openapigen.sh
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha1/trained_model.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  python/aixexplainer/setup.py
  python/kfserving/.gitignore
  python/kfserving/docs/V1alpha1TrainedModel.md
  python/kfserving/docs/V1alpha1TrainedModelList.md
  python/kfserving/docs/V1beta1ONNXRuntimeSpec.md
  python/kfserving/docs/V1beta1PMMLSpec.md
  python/kfserving/docs/V1beta1PredictorExtensionSpec.md
  python/kfserving/docs/V1beta1PredictorsConfig.md
  python/kfserving/docs/V1beta1SKLearnSpec.md
  python/kfserving/docs/V1beta1TFServingSpec.md
  python/kfserving/docs/V1beta1TorchServeSpec.md
  python/kfserving/docs/V1beta1TritonSpec.md
  python/kfserving/docs/V1beta1XGBoostSpec.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/v1alpha1_trained_model.py
  python/kfserving/kfserving/models/v1alpha1_trained_model_list.py
  python/kfserving/kfserving/models/v1beta1_onnx_runtime_spec.py
  python/kfserving/kfserving/models/v1beta1_pmml_spec.py
  python/kfserving/kfserving/models/v1beta1_predictor_extension_spec.py
  python/kfserving/kfserving/models/v1beta1_predictors_config.py
  python/kfserving/kfserving/models/v1beta1_sk_learn_spec.py
  python/kfserving/kfserving/models/v1beta1_tf_serving_spec.py
  python/kfserving/kfserving/models/v1beta1_torch_serve_spec.py
  python/kfserving/kfserving/models/v1beta1_triton_spec.py
  python/kfserving/kfserving/models/v1beta1_xg_boost_spec.py
  python/kfserving/test/azure_credentials.json
  python/kfserving/test/kubeconfig
  python/kfserving/test/test_inference_service_client.py
  python/kfserving/test/test_v1alpha1_trained_model.py
  python/kfserving/test/test_v1alpha1_trained_model_list.py
  python/sklearnserver/sklearnserver/example_models/joblib/model/model.joblib
  python/sklearnserver/sklearnserver/example_models/pickle/model/model.pickle
  python/sklearnserver/sklearnserver/example_models/pkl/model/model.pkl
  test/e2e/credentials/__init__.py
  test/e2e/credentials/aws_credentials
  test/e2e/credentials/azure_credentials.json
  test/e2e/credentials/gcp_credentials.json
  test/e2e/credentials/test_set_creds.py
  test/scripts/run-e2e-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1206 [Docs] Add OpenShift installation guide.
  docs/OPENSHIFT_GUIDE.md
  hack/quick_install.sh
Labels: approved, lgtm, size/M

#1183 Triton V2 protocol docs
  docs/samples/s3/README.md
  docs/samples/triton/bert/README.md
  docs/samples/triton/bert/bert.yaml
  docs/samples/v1beta1/triton/bert/README.md
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/Dockerfile
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/__init__.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/__main__.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/bert_transformer.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/data_processing.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/tokenization.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/setup.py
  docs/samples/v1beta1/triton/bert/bert_v1beta1.yaml
  docs/samples/v1beta1/triton/bert/input.json
  docs/samples/v1beta1/triton/multimodel/README.md
  docs/samples/v1beta1/triton/multimodel/minio.yaml
  docs/samples/v1beta1/triton/multimodel/multi_model_triton.yaml
  docs/samples/v1beta1/triton/multimodel/s3_secret.yaml
  docs/samples/v1beta1/triton/multimodel/trained_model.yaml
  docs/samples/v1beta1/triton/multimodel/trained_model2.yaml
  docs/samples/v1beta1/triton/torchscript/README.md
  docs/samples/v1beta1/triton/torchscript/config.pbtxt
  docs/samples/v1beta1/triton/torchscript/image_transformer_v2/__init__.py
  docs/samples/v1beta1/triton/torchscript/image_transformer_v2/__main__.py
  docs/samples/v1beta1/triton/torchscript/image_transformer_v2/image_transformer_v2.py
  docs/samples/v1beta1/triton/torchscript/input.json
  docs/samples/v1beta1/triton/torchscript/perf.yaml
  docs/samples/v1beta1/triton/torchscript/setup.py
  docs/samples/v1beta1/triton/torchscript/torch_transformer.yaml
  docs/samples/v1beta1/triton/torchscript/torchscript.yaml
  docs/samples/v1beta1/triton/torchscript/transformer.Dockerfile
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XXL

#1220 Fix: Torchserve readme docs
  docs/samples/custom/torchserve/README.md
  docs/samples/custom/torchserve/docs/canary.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1209 AIX explainer readme update
  docs/samples/explanation/aix/mnist/README.md
  docs/samples/explanation/aix/mnist/aix-explanation.png
Labels: approved, lgtm, size/S

#1227 OpenShift Install Instrcutions + AIX360 in main samples
  README.md
  docs/OPENSHIFT_GUIDE.md
  docs/samples/README.md
Labels: approved, lgtm, size/S

#1224 Fix cluster local inference service
  docs/samples/v1beta1/advanced/cluster_local.yaml
  hack/quick_install.sh
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XL
