Repository kserve/kserve, pull requests merged in 2020-02, with the labels that each got.

#650 Add self-signed ca script for development
  Makefile
  config/default/kustomization.yaml
  docs/DEVELOPER_GUIDE.md
  hack/self-signed-ca.sh
Labels: approved, lgtm, size/L

#655 Set default minReplicas to 1 if omitted.
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/inferenceservice_types_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1alpha2/utils.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
Labels: approved, lgtm, size/L

#657 Adds Licenses to images
  Dockerfile
  logger.Dockerfile
  python/alibiexplainer.Dockerfile
  python/pytorch.Dockerfile
  python/sklearn.Dockerfile
  python/storage-initializer.Dockerfile
  python/third_party/library/license.txt
  python/third_party/license_info.csv
  python/third_party/repo.txt
  python/xgb.Dockerfile
  test/scripts/build-kfserving.sh
  test/scripts/build-logger.sh
  third_party/library/license.txt
  third_party/library/license_go.txt
Labels: approved, lgtm, size/XXL

#659 Fix selector error
  docs/samples/accelerators/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#658 Added e2e test for canary rollout
  python/kfserving/kfserving/constants/constants.py
  test/e2e/predictor/test_canary.py
Labels: approved, lgtm, size/M

#656 Improve KFServing main README
  README.md
  docs/DEVELOPER_GUIDE.md
  docs/samples/README.md
  hack/quick_install.sh
Labels: approved, lgtm, size/L

#665 Set max_buffer_size to tornado
  python/kfserving/kfserving/kfserver.py
Labels: approved, lgtm, ok-to-test, size/XS

#661 Add pugangxa as reviewer
  OWNERS
Labels: approved, lgtm, size/XS

#671 Pin test-worker to avoid CI test failure
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#670 Remove knctl as cli since its deprecated
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/M

#669 Update quick_install.sh
  hack/quick_install.sh
Labels: approved, lgtm, ok-to-test, size/XS

#540 Add pytorch GPU image for inference
  config/default/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/pytorch/pytorch_gpu.yaml
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  python/kfserving/kfserving/api/kf_serving_client.py
  python/pytorch-gpu.Dockerfile
  python/pytorchserver/pytorchserver/model.py
  release/triggers/latest/pytorch-gpu.yaml
  release/triggers/tagged/pytorch-gpu.yaml
  test/e2e/data/cifar_input.json
  test/e2e/predictor/test_pytorch.py
  test/scripts/build-python-image.sh
  test/scripts/create-cluster.sh
  test/scripts/run-e2e-tests.sh
  test/scripts/unit-test.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#676 Fix examples links
  docs/samples/README.md
Labels: approved, lgtm, size/M

#672 Rearrange and simply Installation/Testing flow
  README.md
Labels: approved, lgtm, size/M

#680 Stale Webhooks Issue
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/M

#663 Delete isvc-tensorflow inferenceservices after testing
  test/e2e/predictor/test_tensorflow.py
Labels: approved, lgtm, size/XS

#682 Fixed broken link in transformer sample
  docs/samples/transformer/image_transformer/README.md
Labels: approved, lgtm, size/XS

#683 Update KNative and Istio version combination details
  README.md
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/S

#690 Update README.md
  docs/samples/pytorch/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#678 Add custom image sample documentation
  docs/samples/custom/hello-world/Dockerfile
  docs/samples/custom/hello-world/README.md
  docs/samples/custom/hello-world/app.py
  docs/samples/custom/hello-world/custom.yaml
  docs/samples/custom/hello-world/requirements.txt
  docs/samples/custom/kfserving-sdk/Dockerfile
  docs/samples/custom/kfserving-sdk/README.md
  docs/samples/custom/kfserving-sdk/custom.yml
  docs/samples/custom/kfserving-sdk/imagenet_classes.txt
  docs/samples/custom/kfserving-sdk/input.json
  docs/samples/custom/kfserving-sdk/model.py
  docs/samples/custom/kfserving-sdk/requirements.txt
Labels: approved, lgtm, ok-to-test, size/XXL

#637 Introduce parallelism field and make tornado num of workers configurable
  config/default/crds/base/serving.kubeflow.org_inferenceservices.yaml
  install/0.2.2/kfserving.yaml
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_alibi.go
  pkg/apis/serving/v1alpha2/explainer_alibi_test.go
  pkg/apis/serving/v1alpha2/framework_custom.go
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
  pkg/apis/serving/v1alpha2/framework_pytorch.go
  pkg/apis/serving/v1alpha2/framework_pytorch_test.go
  pkg/apis/serving/v1alpha2/framework_scikit.go
  pkg/apis/serving/v1alpha2/framework_scikit_test.go
  pkg/apis/serving/v1alpha2/framework_tensorflow.go
  pkg/apis/serving/v1alpha2/framework_tensorflow_test.go
  pkg/apis/serving/v1alpha2/framework_tensorrt.go
  pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
  pkg/apis/serving/v1alpha2/framework_xgboost.go
  pkg/apis/serving/v1alpha2/framework_xgboost_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/predictor.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/apis/serving/v1alpha2/utils.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/resources/knative/service.go
Labels: approved, lgtm, size/L

#691 add README to rollouts sample
  docs/samples/rollouts/README.md
  docs/samples/rollouts/canary.yaml
  docs/samples/rollouts/input.json
  docs/samples/rollouts/pinned.yaml
  docs/samples/rollouts/promotion.yaml
  docs/samples/rollouts/screenshots/canary.png
  docs/samples/rollouts/screenshots/pinned.png
  docs/samples/rollouts/screenshots/promotion.png
Labels: approved, lgtm, ok-to-test, size/L

#692 Clarify KFServing pod mutator webhook installation requirement
  README.md
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/M

#701 enhance creds if cannot get data secret data key from configmap
  python/kfserving/kfserving/api/creds_utils.py
Labels: approved, lgtm, size/XS

#705 Relax data plane "instances" key validation
  python/kfserving/kfserving/handlers/http.py
Labels: approved, lgtm, size/XS
