Repository kserve/kserve, pull requests merged in 2020-09, with the labels that each got.

#1062 document working k8s version
  README.md
  hack/quick_install.sh
Labels: approved, lgtm, ok-to-test, size/S

#1013 TrainedModel controller
  Makefile
  cmd/manager/main.go
  config/crd/kustomization.yaml
  config/crd/serving.kubeflow.org_trainedmodels.yaml
  config/rbac/role.yaml
  go.sum
  pkg/apis/serving/v1beta1/trained_model.go
  pkg/apis/serving/v1beta1/v1beta1.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/trainedmodel/controller.go
  pkg/controller/v1beta1/trainedmodel/controller_test.go
  pkg/controller/v1beta1/trainedmodel/reconcilers/modelconfig/modelconfig_reconciler.go
  pkg/controller/v1beta1/trainedmodel/sharding/memory/strategy.go
  pkg/controller/v1beta1/trainedmodel/sharding/strategy.go
  pkg/controller/v1beta1/trainedmodel/suite_test.go
  test/scripts/run-e2e-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XL

#979 Add support for generic URI in Storage object
  docs/samples/uri/README.md
  docs/samples/uri/input.json
  docs/samples/uri/sklearn.yaml
  docs/samples/uri/tensorflow.yaml
  pkg/apis/serving/v1alpha2/inferenceservice_validation.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1alpha2/utils.go
  python/kfserving/README.md
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/L

#983 Make KFServer HTTP requests asynchronous
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/alibiexplainer/explainer.py
  python/alibiexplainer/setup.py
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/kfserving/kfmodel.py
  python/kfserving/test/test_server.py
Labels: approved, lgtm, ok-to-test, size/M

#1072 Add the ko prefix to prevent the notice message during building
  config/overlays/development/configmap/ko_resolve_batcher
Labels: approved, lgtm, size/XS

#1069 Fix thread safety issue in KFServer asyncio
  python/alibiexplainer/alibiexplainer/__main__.py
  python/kfserving/kfserving/kfserver.py
Labels: approved, lgtm, ok-to-test, size/S

#1056 Use github action for kfserving controller tests
  .github/workflows/go.yml
  Makefile
  cmd/manager/main.go
  go.sum
  pkg/controller/inferenceservice/controller_test.go
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#1071 Add Peter Salanki as reviewer
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, needs-ok-to-test, size/XS

#1057 Puller streamlining/simplification
  cmd/agent/main.go
  pkg/agent/downloader.go
  pkg/agent/puller.go
  pkg/agent/syncer.go
  pkg/agent/watcher.go
Labels: ok-to-test, size/L

#1078 support generic filename for ONNX runtime model (#1004)
  pkg/apis/serving/v1alpha2/framework_onnx.go
  pkg/apis/serving/v1alpha2/framework_onnx_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1079 Validation check for InferenceService Name
  pkg/apis/serving/v1alpha2/inferenceservice_validation.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1104 update ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1094 Add support for AIX360 explanations
  config/configmap/inferenceservice.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/explanation/aix/mnist/README.md
  docs/samples/explanation/aix/mnist/aix-explainer-v1alpha2.yaml
  docs/samples/explanation/aix/mnist/aix-explainer.yaml
  docs/samples/explanation/aix/mnist/mnist-explanation.png
  docs/samples/explanation/aix/mnist/query_explain.ipynb
  docs/samples/explanation/aix/mnist/query_explain.py
  docs/samples/explanation/aix/mnist/requirements.txt
  docs/samples/explanation/aix/mnist/rfserver/README.md
  docs/samples/explanation/aix/mnist/rfserver/rf.Dockerfile
  docs/samples/explanation/aix/mnist/rfserver/rfmodel.pickle
  docs/samples/explanation/aix/mnist/rfserver/rfserver/__init__.py
  docs/samples/explanation/aix/mnist/rfserver/rfserver/__main__.py
  docs/samples/explanation/aix/mnist/rfserver/rfserver/model.py
  docs/samples/explanation/aix/mnist/rfserver/setup.py
  docs/samples/explanation/aix/mnist/train_rf.py
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha2/configmap.go
  pkg/apis/serving/v1alpha2/explainer.go
  pkg/apis/serving/v1alpha2/explainer_aix360.go
  pkg/apis/serving/v1alpha2/explainer_aix360_test.go
  pkg/apis/serving/v1alpha2/inferenceservice_conversion.go
  pkg/apis/serving/v1alpha2/inferenceservice_types.go
  pkg/apis/serving/v1alpha2/openapi_generated.go
  pkg/apis/serving/v1alpha2/swagger.json
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/explainer.go
  pkg/apis/serving/v1beta1/explainer_aix360.go
  pkg/apis/serving/v1beta1/explainer_aix360_test.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  python/aixexplainer.Dockerfile
  python/aixexplainer/README.md
  python/aixexplainer/aixserver/__init__.py
  python/aixexplainer/aixserver/__main__.py
  python/aixexplainer/aixserver/model.py
  python/aixexplainer/setup.py
  python/kfserving/docs/V1alpha2AIXExplainerSpec.md
  python/kfserving/docs/V1alpha2ExplainerSpec.md
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/models/__init__.py
  python/kfserving/kfserving/models/v1alpha2_aix_explainer_spec.py
  python/kfserving/kfserving/models/v1alpha2_explainer_spec.py
  python/kfserving/test/test_v1alpha2_aix_explainer_spec.py
  test/e2e/common/utils.py
  test/e2e/data/mnist_input.json
  test/e2e/explainer/test_aix_explainer.py
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1106 Set KFServing default worker to 1
  python/kfserving/kfserving/kfserver.py
Labels: approved, lgtm, size/XS
