Repository kserve/kserve, pull requests merged in 2020-04, with the labels that each got.

#743 Configure memory
  Makefile
  config/default/kustomization.yaml
  config/default/manager_resources_patch.yaml
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, ok-to-test, size/M

#757 Allow kfserving-ingressgateway in custom sample notebook
  docs/samples/custom/kfserving-custom-model/kfserving_sdk_custom_image.ipynb
Labels: approved, lgtm, ok-to-test, size/XS

#742 Adds custom domain sample
  docs/samples/custom-domain/README.md
  docs/samples/custom-domain/kfserving-ingress.yaml
Labels: approved, lgtm, ok-to-test, size/L

#761 Errors when running imagenet sample
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/imagenet/imagenet.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#769 Fix miniconda installation in pytorch dockerfile
  python/pytorch.Dockerfile
Labels: approved, lgtm, size/XS

#749 Add trouble shooting for IngressNotConfigured error
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, size/S

#767 Fix adding duplicate volumes
  pkg/controller/inferenceservice/resources/credentials/service_account_credentials.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, lgtm, ok-to-test, size/L

#780 Fix yaml file extension in custom sample
  docs/samples/custom/prebuilt-image/custom.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#782 Fix the link to run_e2e_workflow.py script
  prow_config.yaml
Labels: approved, lgtm, size/XS

#777 fix-775 fix sdk promote missing annotations
  python/kfserving/kfserving/api/kf_serving_client.py
Labels: approved, lgtm, ok-to-test, size/XS

#781 fix missing patch file in config/overlays/development
  config/overlays/development/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#783 Add pointers to GRPC proto specification and Triton extensions
  docs/predict-api/v2/README.md
Labels: approved, lgtm, ok-to-test, size/S

#788 Use public slack link
  CONTRIBUTING.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#704 Updated S3 credential variable names to commonly used en var names
  config/default/configmap/inferenceservice.yaml
  python/kfserving/kfserving/constants/constants.py
Labels: approved, lgtm, ok-to-test, size/S

#787 Fix stale links for kafka event source example
  docs/samples/kafka/README.md
  docs/samples/kafka/kafka-source.yaml
Labels: approved, lgtm, size/M

#667 Relax top level virtual service to allow multiple model names
  docs/README.md
  pkg/apis/serving/v1alpha2/transformer.go
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Labels: approved, lgtm, size/L

#764 Add Outlier Detection and Drift Detection Examples
  docs/samples/drift-detection/alibi-detect/cifar10/README.md
  docs/samples/drift-detection/alibi-detect/cifar10/architecture.png
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10.yaml
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10_drift.ipynb
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10cd.yaml
  docs/samples/drift-detection/alibi-detect/cifar10/message-dumper.yaml
  docs/samples/drift-detection/alibi-detect/cifar10/requirements_notebook.txt
  docs/samples/drift-detection/alibi-detect/cifar10/trigger.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/README.md
  docs/samples/outlier-detection/alibi-detect/cifar10/architecture.png
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10_outlier.ipynb
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10od.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/demo.png
  docs/samples/outlier-detection/alibi-detect/cifar10/message-dumper.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/requirements_notebook.txt
  docs/samples/outlier-detection/alibi-detect/cifar10/trigger.yaml
Labels: approved, lgtm, size/XXL
