Repository kserve/kserve, pull requests merged in 2020-03, with the labels that each got.

#707 Update kfserving-custom-model
  docs/samples/README.md
  docs/samples/custom/kfserving-custom-model/Dockerfile
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/kfserving-custom-model/custom.yml
  docs/samples/custom/kfserving-custom-model/imagenet_classes.txt
  docs/samples/custom/kfserving-custom-model/input.json
  docs/samples/custom/kfserving-custom-model/model.py
  docs/samples/custom/kfserving-custom-model/requirements.txt
  docs/samples/custom/kfserving-sdk/input.json
Labels: approved, lgtm, ok-to-test, size/M

#711 Fix broken link for python client gen script
  hack/python-sdk/client-gen.sh
Labels: approved, lgtm, size/XS

#698 Add example of using a prebuilt image
  docs/samples/README.md
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/custom/prebuilt-image/custom.yml
  docs/samples/custom/prebuilt-image/dog-human.jpg
Labels: approved, lgtm, ok-to-test, size/M

#716 Update example usage in README
  docs/samples/pytorch/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#713 Update pvc example accordingly
  docs/samples/pvc/README.md
Labels: approved, lgtm, size/XS

#699 extra info from logger
  cmd/logger/main.go
  docs/samples/logger/local/README.md
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/inferenceservice/resources/knative/service.go
  pkg/controller/inferenceservice/resources/knative/service_test.go
  pkg/logger/server.go
  pkg/logger/server_test.go
  pkg/logger/types.go
  pkg/logger/worker.go
  pkg/webhook/admission/pod/logger_injector.go
  pkg/webhook/admission/pod/logger_injector_test.go
Labels: approved, lgtm, size/L

#714 Fix quick install to install from release yaml
  hack/quick_install.sh
Labels: approved, lgtm, size/XS

#718 Fix check_sa_exists not checking all service accounts in python library
  python/kfserving/kfserving/api/creds_utils.py
  python/kfserving/test/test_creds_utils.py
Labels: approved, lgtm, ok-to-test, size/S

#717 fix inferenceservice url with hyphenated knative domainTemplate
  Dockerfile
  Makefile
  docs/DEVELOPER_GUIDE.md
  pkg/constants/constants.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Labels: approved, lgtm, ok-to-test, size/M

#709 Predict protocol V2 proposal
  docs/README.md
  docs/predict-api/v2/README.md
  docs/predict-api/v2/required_api.md
Labels: approved, lgtm, ok-to-test, size/XL

#726 Support https
  .gitignore
  Makefile
  config/overlays/development/kustomization.yaml
  pkg/constants/constants.go
  pkg/controller/inferenceservice/controller_test.go
  pkg/controller/inferenceservice/resources/istio/virtualservice.go
  pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Labels: approved, lgtm, ok-to-test, size/M

#724 Point to performance tests
  README.md
Labels: approved, lgtm, size/XS

#700 Cutting v0.3.0 release
  README.md
  config/default/configmap/inferenceservice.yaml
  docs/DEVELOPER_GUIDE.md
  docs/samples/custom/kfserving-custom-model/requirements.txt
  hack/generate-install.sh
  install/v0.3.0/kfserving.yaml
  pkg/constants/constants.go
  python/alibiexplainer/setup.py
  python/kfserving/setup.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/xgbserver/setup.py
  release/RELEASE_PROCESS.md
Labels: approved, lgtm, size/XXL

#728 Fixes 0.3.0 to v0.3.0
  config/default/configmap/inferenceservice.yaml
  install/v0.3.0/kfserving.yaml
Labels: approved, lgtm, size/L

#729 Fix pytorch gpu image tag for the image build trigger
  release/triggers/tagged/pytorch-gpu.yaml
Labels: approved, lgtm, size/XS

#732 Fixes a missing tag in the pytorch gpu cloud builder
  release/triggers/tagged/pytorch-gpu.yaml
Labels: approved, lgtm, size/XS

#735 [Predict Protocol V2] Change type for GRPC string parameter to 'string'
  docs/predict-api/v2/required_api.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#748 Allow kfserving-ingressgateway in samples
  docs/samples/autoscaling/README.md
  docs/samples/custom/hello-world/README.md
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/logger/basic/README.md
  docs/samples/logger/knative-eventing/README.md
  docs/samples/onnx/README.md
  docs/samples/pytorch/README.md
  docs/samples/rollouts/README.md
  docs/samples/s3/README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, size/M

#752 fix typo in kfserving-ingressgateway
  docs/samples/autoscaling/README.md
  docs/samples/custom/hello-world/README.md
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/prebuilt-image/README.md
  docs/samples/explanation/alibi/imagenet/README.md
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/moviesentiment/README.md
  docs/samples/logger/basic/README.md
  docs/samples/logger/knative-eventing/README.md
  docs/samples/onnx/README.md
  docs/samples/pytorch/README.md
  docs/samples/rollouts/README.md
  docs/samples/s3/README.md
  docs/samples/tensorflow/README.md
  docs/samples/tensorrt/README.md
  docs/samples/transformer/image_transformer/README.md
  docs/samples/xgboost/README.md
Labels: approved, lgtm, size/M

#751 Fix MutatingWebhookConfiguration typo
  config/default/webhook/manifests.yaml
  install/v0.3.0/kfserving.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#745 fix(roadmap): Fix the date typo
  ROADMAP.md
Labels: approved, lgtm, size/XS

#723 Add sample deploying custom image using KFServing client sdk
  .gitignore
  docs/samples/custom/kfserving-custom-model/README.md
  docs/samples/custom/kfserving-custom-model/custom.yaml
  docs/samples/custom/kfserving-custom-model/kfserving_sdk_custom_image.ipynb
  docs/samples/custom/kfserving-custom-model/model-server/Dockerfile
  docs/samples/custom/kfserving-custom-model/model-server/imagenet_classes.txt
  docs/samples/custom/kfserving-custom-model/model-server/model.py
  docs/samples/custom/kfserving-custom-model/model-server/requirements.txt
  docs/samples/custom/kfserving-custom-model/requirements.txt
Labels: approved, lgtm, ok-to-test, size/L

#746 Model name should be included in the inference response for GRPC
  docs/predict-api/v2/required_api.md
Labels: approved, lgtm, needs-ok-to-test, size/S
