Repository kserve/kserve, pull requests merged in 2021-02, with the labels that each got.

#1329 Migrate kfserving to new test-infra
  config/overlays/test/configmap/inferenceservice.yaml
  config/overlays/test/manager_image_patch.yaml
  test/e2e/transformer/test_transformer.py
  test/scripts/run-e2e-tests.sh
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/M

#1318 Fix FileExist utility and generate sha for modelspec
  pkg/agent/downloader.go
  pkg/agent/storage/utils.go
  pkg/agent/syncer.go
  pkg/agent/watcher.go
  pkg/agent/watcher_test.go
Labels: approved, lgtm, size/L

#1305 Update k8s libraries to 0.19.2
  docs/samples/v1alpha2/custom/grpc-server/client/client.go
  docs/samples/v1alpha2/custom/grpc-server/server.go
  go.mod
  go.sum
  pkg/apis/serving/v1beta1/podspec.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, ok-to-test, size/XL

#1349 Fix dependency for lightgbm and aix python server
  python/aixexplainer/setup.py
  python/lgbserver/setup.py
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XS

#1352 Updating go version 1.14.2 -> 1.14.14
  Dockerfile
  agent.Dockerfile
  logger.Dockerfile
Labels: approved, lgtm, ok-to-test, size/XS

#1354 Fix broken link
  docs/samples/v1alpha2/onnx/README.md
  docs/samples/v1alpha2/pmml/README.md
  docs/samples/v1alpha2/pytorch/README.md
  docs/samples/v1alpha2/rollouts/README.md
  docs/samples/v1alpha2/sklearn/README.md
  docs/samples/v1alpha2/tensorflow/README.md
  docs/samples/v1alpha2/xgboost/README.md
Labels: approved, lgtm, size/S

#1356 Make port optional in custom spec
  Makefile
Labels: approved, lgtm, size/XS

#1339 Determines if predictor is using MMS by checking inference ConfigMap
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/explainer_aix360.go
  pkg/apis/serving/v1beta1/explainer_aix360_test.go
  pkg/apis/serving/v1beta1/explainer_alibi.go
  pkg/apis/serving/v1beta1/explainer_alibi_test.go
  pkg/apis/serving/v1beta1/explainer_art.go
  pkg/apis/serving/v1beta1/explainer_art_test.go
  pkg/apis/serving/v1beta1/explainer_custom.go
  pkg/apis/serving/v1beta1/explainer_custom_test.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_lightgbm.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/predictor_triton.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/modelconfig/modelconfig_reconciler.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Labels: approved, lgtm, ok-to-test, size/XXL

#1341 Upgrade controller-runtime to v0.7.0
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/agent/storage/s3.go
  pkg/apis/serving/v1alpha1/v1alpha1.go
  pkg/apis/serving/v1alpha2/doc.go
  pkg/apis/serving/v1alpha2/register.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/v1beta1.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1alpha1/trainedmodel/reconcilers/modelconfig/modelconfig_reconciler.go
  pkg/controller/v1alpha1/trainedmodel/suite_test.go
  pkg/controller/v1alpha2/inferenceservice/controller.go
  pkg/controller/v1alpha2/inferenceservice/reconcilers/istio/virtualservice_reconciler.go
  pkg/controller/v1alpha2/inferenceservice/reconcilers/knative/service_reconciler.go
  pkg/controller/v1alpha2/inferenceservice/reconcilers/knative/service_reconciler_test.go
  pkg/controller/v1alpha2/inferenceservice/suite_test.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/modelconfig/modelconfig_reconciler.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  pkg/credentials/service_account_credentials.go
  pkg/logger/handler.go
  pkg/logger/handler_test.go
  pkg/modelconfig/configmap.go
  pkg/modelconfig/configmap_test.go
  pkg/testing/envtest_setup.go
  pkg/webhook/admission/pod/mutator.go
Labels: approved, lgtm, size/L

#1343 [#1159] Support cloud events for KFServing custom framework
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/kfserving/kfmodel.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_server.py
Labels: approved, lgtm, ok-to-test, size/L

#1363 Make kative local gateway configurable
  config/configmap/inferenceservice.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
Labels: approved, lgtm, size/XXL

#1361 Allow any .onnx file name in v1beta1 api
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1315 KFS Release 0.5
  Makefile
  README.md
  ROADMAP.md
  config/configmap/inferenceservice.yaml
  config/crd/patches/protocol.yaml
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  docs/README.md
  docs/diagrams/kfs_architect.png
  docs/samples/autoscaling/README.md
  docs/samples/autoscaling/autoscale.yaml
  docs/samples/autoscaling/autoscale_custom.yaml
  docs/samples/autoscaling/autoscale_gpu.yaml
  docs/samples/v1beta1/custom/torchserve/README.md
  docs/samples/v1beta1/custom/torchserve/bert-sample/hugging-face-bert-sample.md
  docs/samples/v1beta1/custom/torchserve/docs/autoscaling.md
  docs/samples/v1beta1/custom/torchserve/docs/canary.md
  docs/samples/v1beta1/custom/torchserve/docs/metrics.md
  docs/samples/v1beta1/lightgbm/README.md
  docs/samples/v1beta1/pmml/README.md
  docs/samples/v1beta1/rollout/README.md
  docs/samples/v1beta1/tensorflow/README.md
  docs/samples/v1beta1/torchserve/README.md
  docs/samples/v1beta1/torchserve/autoscaling/README.md
  docs/samples/v1beta1/torchserve/bert/README.md
  docs/samples/v1beta1/torchserve/canary/README.md
  docs/samples/v1beta1/torchserve/metrics/README.md
  docs/samples/v1beta1/transformer/torchserve_image_transformer/README.md
  docs/samples/v1beta1/triton/bert/README.md
  docs/samples/v1beta1/triton/torchscript/README.md
  docs/samples/v1beta1/triton/torchscript/torch_transformer.yaml
  docs/samples/v1beta1/triton/torchscript/torchscript_grpc.yaml
  hack/generate-install.sh
  install/v0.5.0/kfserving.yaml
  install/v0.5.0/kfserving_crds.yaml
  python/kfserving/setup.py
Labels: approved, lgtm, size/XXL

#1375 Prevent experimental features from being set by default setting multimodelserver flags to false
  config/configmap/inferenceservice.yaml
  docs/MULTIMODELSERVING_GUIDE.md
  docs/samples/v1beta1/sklearn/multimodel/README.md
  docs/samples/v1beta1/triton/multimodel/README.md
  install/v0.5.0/kfserving.yaml
  install/v0.5.0/kfserving_crds.yaml
Labels: approved, lgtm, ok-to-test, size/L

#1373 add missing input.json to transformer example
  docs/samples/v1beta1/transformer/torchserve_image_transformer/input.json
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1374 Docs/hold application until proxy starts
  docs/samples/storage/s3/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1378 Remove unnecessary "latest" routing tag
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  test/e2e/common/utils.py
  test/e2e/predictor/test_lightgbm.py
  test/e2e/transformer/test_transformer.py
Labels: approved, size/M

#1381 Add Paul as a reviewer for KFServing
  OWNERS
Labels: approved, lgtm, size/XS

#1353 Update KFServing on OpenShift documentation
  docs/OPENSHIFT_GUIDE.md
Labels: approved, lgtm, size/L

#1382 Use custom local gateway for isvc external service
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Labels: approved, lgtm, ok-to-test, size/XS

#1380 Update MMS readme
  docs/MULTIMODELSERVING_GUIDE.md
Labels: approved, lgtm, size/M

#1372 Feature to include headers in http/https service requests (non-MMS)
  docs/samples/storage/uri/README.md
  pkg/credentials/https/https_secret.go
  pkg/credentials/https/https_secret_test.go
  pkg/credentials/service_account_credentials.go
  python/kfserving/kfserving/storage.py
Labels: approved, lgtm, needs-ok-to-test, size/L

#1398 Instruction for calling inference service with magic DNS
  README.md
Labels: approved, size/M

#1400 Avoid overwriting arguments specified on container fields
  pkg/apis/serving/v1alpha2/inferenceservice_conversion.go
  pkg/apis/serving/v1alpha2/inferenceservice_conversion_test.go
  pkg/apis/serving/v1beta1/explainer_aix360.go
  pkg/apis/serving/v1beta1/explainer_aix360_test.go
  pkg/apis/serving/v1beta1/explainer_alibi.go
  pkg/apis/serving/v1beta1/explainer_alibi_test.go
  pkg/apis/serving/v1beta1/explainer_art.go
  pkg/apis/serving/v1beta1/explainer_art_test.go
  pkg/apis/serving/v1beta1/explainer_custom.go
  pkg/apis/serving/v1beta1/predictor_lightgbm.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/XL

#1401 Update kubectl version used in e2e tests
  Makefile
  README.md
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/S

#1388 Re-add crd as base to default kustomization
  Makefile
  config/default/cainjection_conversion_webhook.yaml
  config/default/crd/kustomization.yaml
  config/default/crd/namespace.yaml
  config/default/crd/params.env
  config/default/crd/params.yaml
  config/default/inferenceservice_conversion_webhook.yaml
  config/default/kustomization.yaml
  config/default/params.yaml
  hack/generate-install.sh
Labels: approved, lgtm, size/M

#1396 Bug Fix for CloudEvent data access
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/kfserving/kfmodel.py
  python/kfserving/test/test_server.py
Labels: approved, lgtm, ok-to-test, size/L

#1394 Trained Model Validation Webhook + Memory in trained model immutable
  Makefile
  cmd/manager/main.go
  config/crd/serving.kubeflow.org_trainedmodels.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/manifests.yaml
  install/v0.5.0/kfserving.yaml
  install/v0.5.0/kfserving_kubeflow.yaml
  pkg/apis/serving/v1alpha1/trained_model.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1403 patch inferenceservice annotations to kfserving routing virtualservice
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1402 Validate the parent inference service is ready in trained model controller
  pkg/apis/serving/v1alpha1/trained_model_status.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1alpha1/trainedmodel/controller_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1407 Validation for storage uri in webhook
  pkg/agent/storage/provider.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
  pkg/apis/serving/v1beta1/component.go
Labels: approved, lgtm, size/M

#1409 Update Multi-Model Serving Doc
  docs/MULTIMODELSERVING_GUIDE.md
  docs/samples/v1beta1/sklearn/v1/multimodel/README.md
  docs/samples/v1beta1/triton/multimodel/README.md
Labels: approved, lgtm, size/XS

#1411 Defined recorder in test suite
  pkg/controller/v1alpha1/trainedmodel/suite_test.go
Labels: approved, lgtm, size/XS
