Repository kserve/kserve, pull requests merged in 2021-07, with the labels that each got.

#1637 Parallel inference support
  docs/samples/v1beta1/custom/custom_model/README.md
  docs/samples/v1beta1/custom/custom_model/custom.yaml
  docs/samples/v1beta1/custom/custom_model/input.json
  docs/samples/v1beta1/custom/custom_model/parallel_inference.png
  python/custom_model.Dockerfile
  python/custom_model/Procfile
  python/custom_model/model.py
  python/custom_model/model_remote.py
  python/custom_model/requirements.txt
  python/kfserving/kfserving/handlers/http.py
  python/kfserving/kfserving/kfmodel.py
  python/kfserving/kfserving/kfmodel_repository.py
  python/kfserving/kfserving/kfserver.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_server.py
  python/xgb.Dockerfile
  test/e2e/predictor/test_paddle.py
Labels: approved, lgtm, size/L

#1697 Update 0.6 installation doc
  README.md
  docs/samples/v1alpha2/transformer/image_transformer/setup.py
  hack/quick_install.sh
  python/aiffairness/setup.py
  python/aixexplainer/setup.py
  python/alibiexplainer/setup.py
  python/artexplainer/setup.py
  python/lgbserver/setup.py
  python/paddleserver/setup.py
  python/pmmlserver/setup.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/xgbserver/setup.py
Labels: approved, size/M

#1682 Append "--no-cache-dir" to "pip install" in Dockerfiles
  docs/samples/explanation/aix/mnist/rfserver/rf.Dockerfile
  docs/samples/explanation/art/mnist/sklearnserver/sklearn.Dockerfile
  docs/samples/kafka/transformer.Dockerfile
  docs/samples/v1alpha2/custom/customized-urls/Dockerfile
  docs/samples/v1alpha2/transformer/image_transformer/transformer.Dockerfile
  docs/samples/v1alpha2/triton/bert/bert_tokenizer/Dockerfile
  docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer.Dockerfile
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/Dockerfile
  docs/samples/v1beta1/triton/torchscript/transformer.Dockerfile
  python/aiffairness.Dockerfile
  python/aixexplainer.Dockerfile
  python/alibiexplainer.Dockerfile
  python/artexplainer.Dockerfile
  python/lgb.Dockerfile
  python/pmml.Dockerfile
  python/pytorch-gpu.Dockerfile
  python/pytorch.Dockerfile
  python/sklearn.Dockerfile
  python/storage-initializer.Dockerfile
  python/xgb.Dockerfile
Labels: approved, lgtm, ok-to-test, size/M

#1508 1320 add raw demployment ability in kfserving
  Makefile
  config/configmap/inferenceservice.yaml
  config/rbac/role.yaml
  hack/quick_install.sh
  pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/trainedmodel/suite_test.go
  pkg/controller/v1alpha2/inferenceservice/reconcilers/knative/suite_test.go
  pkg/controller/v1alpha2/inferenceservice/suite_test.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  pkg/testing/envtest_setup.go
  python/kfserving/kfserving/api/kf_serving_client.py
  test/e2e/common/utils.py
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/transformer/test_raw_transformer.py
Labels: approved, lgtm, size/XXL

#1674 Fix file paths and urls for deployment smoke test
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/S

#1715 Use index instead of element when searching for a volume
  pkg/utils/utils.go
Labels: approved, lgtm, ok-to-test, size/XS

#1718 `ContainsString` and `Includes` utils are duplicates
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/utils/utils.go
Labels: approved, lgtm, ok-to-test, size/S

#1721 Make canary name match tensorflow.yaml
  docs/samples/v1beta1/tensorflow/canary.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1696 sklearnserver: add safeguard if multiple model files are present
  python/sklearnserver/sklearnserver/example_models/multi/model/model.joblib
  python/sklearnserver/sklearnserver/example_models/multi/model/model.pkl
  python/sklearnserver/sklearnserver/model.py
  python/sklearnserver/sklearnserver/test_model.py
Labels: approved, lgtm, ok-to-test, size/M

#1592 Update Azure Blob to 12.1.0
  docs/samples/storage/azure/README.md
  python/kfserving/kfserving/storage.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_azure_storage.py
Labels: approved, lgtm, ok-to-test, size/L

#1738 Feature: Upgrade torchserve to 0.4.1
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/README.md
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Labels: approved, lgtm, ok-to-test, size/M
