Repository kserve/kserve, pull requests merged in 2021-09, with the labels that each got.

#1780 Fix AWS_REGION and add AWS_CA_BUNDLE to s3_secrets.go
  pkg/credentials/s3/s3_secret.go
  python/kfserving/kfserving/api/creds_utils.py
Labels: lgtm, approved, size/S, ok-to-test

#1790 Upgrade Feast transformer for v0.12.1
  docs/samples/v1beta1/transformer/feast/README.md
  docs/samples/v1beta1/transformer/feast/driver_transformer.Dockerfile
  docs/samples/v1beta1/transformer/feast/driver_transformer.yaml
  docs/samples/v1beta1/transformer/feast/driver_transformer/__main__.py
  docs/samples/v1beta1/transformer/feast/driver_transformer/driver_transformer.py
  docs/samples/v1beta1/transformer/feast/setup.py
Labels: lgtm, approved, size/M, ok-to-test

#1807 add wikimedia in the list of adopters
  ADOPTERS.md
Labels: size/XS, lgtm, approved

#1831 Update doc pointers to KServe website
  README.md
  docs/DEVELOPER_GUIDE.md
  docs/README.md
  docs/apis/v1beta1/README.md
  hack/python-sdk/client-gen.sh
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  python/kserve/README.md
  python/kserve/docs/KFServingClient.md
Labels: approved

#1832 (GKE): Update documentation about calling inference service endpoing behind IAP. Fix https://github.com/kubeflow/gcp-blueprints/issues/324
  docs/samples/gcp-iap/README.md
  docs/samples/gcp-iap/iap_request_auth.py
  docs/samples/gcp-iap/make-prediction-auth.sh
  docs/samples/gcp-iap/make-prediction.sh
  docs/samples/gcp-iap/sklearn-iap-no-authz.yaml
  docs/samples/gcp-iap/sklearn-iap-with-authz.yaml
  docs/samples/gcp-iap/virtual-service.yaml
Labels: lgtm, approved, ok-to-test
