Repository kserve/kserve, pull requests merged in 2021-10, with the labels that each got.

#1840 Update Triton to 21.09. Remove caffe2 from supported frameworks
  config/configmap/inferenceservice.yaml
Labels: lgtm, approved, ok-to-test

#1845 Azure Blob Upgrade Bug Fix #1750
  python/kserve/kserve/storage.py
  python/kserve/test/test_azure_storage.py
Labels: lgtm, approved

#1830 add hpa for raw deployment
  config/rbac/role.yaml
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
Labels: lgtm, approved

#1847 Update KServe main README to redirect to website
  ADOPTERS.md
  README.md
Labels: approved

#1855 Allow unknown fields in InferenceService status
  config/crd/serving.kserve.io_inferenceservices.yaml
  pkg/apis/serving/v1beta1/inference_service.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#1854 fix-1852: when minReplicas is nil, make the controller crash.
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
Labels: lgtm, approved

#1836 adding tgz/zip support for all storages
  python/kserve/kserve/storage.py
  python/kserve/test/test_storage.py
Labels: lgtm, approved

#1851 Do not reconcile if `modelmesh` annotation set as true.
  pkg/apis/serving/v1beta1/configmap.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
Labels: lgtm, approved

#1856 Fix old ./Adopters.md Link in README
  README.md
Labels: lgtm, approved, ok-to-test

#1834 Migration job
  hack/kserve_migration/Dockerfile
  hack/kserve_migration/kserve_migration.sh
  hack/kserve_migration/kserve_migration_job.yaml
Labels: lgtm, approved

#1883 storage.py: add more logging and an error condition for s3
  python/kserve/kserve/storage.py
  python/kserve/test/test_s3_storage.py
Labels: lgtm, approved, ok-to-test
