Repository kserve/kserve, pull requests merged in 2021-09, with the labels that each got.

#40 Kserve error fix
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  python/kserve/kserve/__init__.py
  python/kserve/requirements.txt
  python/kserve/test/skip_test_inference_service_client.py
  python/kserve/test/test_inference_service_client.py
  test/e2e/batcher/test_batcher.py
  test/e2e/credentials/test_set_creds.py
  test/e2e/explainer/test_aix_explainer.py
  test/e2e/explainer/test_art_explainer.py
  test/e2e/explainer/test_tabular_explainer.py
  test/e2e/logger/test_logger.py
  test/e2e/predictor/test_paddle.py
  test/e2e/predictor/test_pytorch.py
  test/e2e/predictor/test_triton.py
  test/e2e/transformer/test_transformer.py
Labels: approved, lgtm

#42 Fixed error with e2e due to kfserving reference in test overlay
  config/overlays/test/manager_image_patch.yaml
  hack/quick_install.sh
  install/v0.7.0-rc0/kserve.yaml
  install/v0.7.0-rc0/kserve_kubeflow.yaml
  test/e2e/common/utils.py
Labels: approved, lgtm

#44 fix image-transformer built image tag
  config/overlays/test/configmap/inferenceservice.yaml
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm

#46 Generate 0.7.0 release candidate and update roadmap/release process
  README.md
  ROADMAP.md
  config/configmap/inferenceservice.yaml
  docs/samples/v1beta1/transformer/torchserve_image_transformer/setup.py
  hack/self-signed-ca.sh
  install/v0.7.0-rc0/kserve.yaml
  install/v0.7.0-rc0/kserve_kubeflow.yaml
  python/kserve/kserve/__init__.py
  release/RELEASE_PROCESS.md
  test/README.md
Labels: approved, lgtm

#48 Cherrypick KFServing #1780
  pkg/credentials/s3/s3_secret.go
  python/kserve/kserve/api/creds_utils.py
Labels: approved

#57 add default deployment and fix startup without knative to master branch
  cmd/manager/main.go
  config/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/transformer/test_raw_transformer.py
Labels: approved, lgtm

#58 Update kserve layer diagram
  README.md
  docs/diagrams/kfserving.png
  docs/diagrams/kserve.png
Labels: approved, lgtm

#59 update diag
  docs/diagrams/kserve.png
Labels: approved, lgtm

#60 Adding kfs_architect.drawio and changing kfs_architect.png's "KFserving" name to "KServe"
  docs/diagrams/kfs_architect.drawio
  docs/diagrams/kfs_architect.png
Labels: approved, lgtm, ok-to-test

#66 add Nick Hill as a reviewer
  OWNERS
Labels: approved, lgtm
