Repository kserve/kserve, pull requests merged in 2021-06, with the labels that each got.

#1649 Feature: Upgrade torchserve-kfs version
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Labels: approved, lgtm, size/M

#1646 ingress reconciler compability with istio 1.10
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
Labels: approved, lgtm, size/M

#1632 Corrected links to Iter8 KFServing extensions
  README.md
  docs/samples/metrics-and-monitoring/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1650 Fixes storage initializer image patch script
  Makefile
  hack/storageInitializer_patch_dev.sh
Labels: approved, lgtm, ok-to-test, size/S

#1636 add the component label in payload logging
  cmd/agent/main.go
  pkg/logger/handler.go
  pkg/logger/handler_test.go
  pkg/logger/types.go
  pkg/logger/worker.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
Labels: approved, lgtm, size/S

#1640 supports anonymous S3 connect
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_s3_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#1609 relax .tar.gz files Content-Type check
  pkg/agent/storage/https.go
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#1661 Improvements to self-signed-ca.sh
  hack/self-signed-ca.sh
Labels: approved, lgtm, ok-to-test, size/S

#1668 feat(bug): retry kfserving installation. Fixes #1613
  hack/quick_install.sh
Labels: approved, lgtm, size/XS

#1675 Fix an example on KO_DOCKER_REPO in the dev guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1680 Updated Kafka event source url in samples
  docs/samples/kafka/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1673 extend zip content type check when download zip use uri
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/S

#1686 Correct Tensorflow sample's URL in the Dev Guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1687 Limit number of asyncio workers in custom transformers
  python/kfserving/kfserving/kfserver.py
  python/kfserving/kfserving/utils/utils.py
  python/kfserving/requirements.txt
Labels: approved, lgtm, ok-to-test, size/M

#1670 feat(bug): fix broken mypy test
  python/sklearnserver/sklearnserver/__main__.py
Labels: approved, lgtm, size/XS

#1647 Add feast example
  docs/samples/v1beta1/transformer/feast/README.md
  docs/samples/v1beta1/transformer/feast/driver-input.json
  docs/samples/v1beta1/transformer/feast/driver_transformer.Dockerfile
  docs/samples/v1beta1/transformer/feast/driver_transformer.yaml
  docs/samples/v1beta1/transformer/feast/driver_transformer/__init__.py
  docs/samples/v1beta1/transformer/feast/driver_transformer/__main__.py
  docs/samples/v1beta1/transformer/feast/driver_transformer/driver_transformer.py
  docs/samples/v1beta1/transformer/feast/setup.py
Labels: approved, lgtm, ok-to-test, size/L

#1692 Generate v0.6.0 release
  config/configmap/inferenceservice.yaml
  config/default/params.env
  config/overlays/kubeflow/params.env
  config/overlays/test/configmap/inferenceservice.yaml
  config/web-app/deployment.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.6.0/kfserving.yaml
  install/v0.6.0/kfserving_kubeflow.yaml
  python/kfserving/setup.py
Labels: approved, lgtm, size/XXL

#1693 Correct link to the tensorflow sample
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, ok-to-test, size/XS
