Repository kserve/kserve, pull requests merged in 2021-08, with the labels that each got.

#1752 Enable tag based routing
  docs/samples/v1beta1/rollout/README.md
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
Labels: lgtm, approved, size/L

#1757 Update broken url to the MULTIMODELSERVING_GUIDE.md
  docs/samples/multimodelserving/benchmark/BENCHMARK.md
Labels: size/XS, lgtm, approved

#1755 Ignore istio dir downloaded by hack install
  .gitignore
Labels: size/XS, lgtm, approved, needs-ok-to-test

#1763 Pin image tags in release-0.6 branch
  config/configmap/inferenceservice.yaml
  config/default/manager_image_patch.yaml
  config/web-app/deployment.yaml
Labels: lgtm, approved, size/M

#1770 prevent nested directories in s3 to be created as file inside model directory /mnt/models
  pkg/agent/storage/gcs.go
  pkg/agent/storage/s3.go
Labels: lgtm, approved, size/S, ok-to-test

#1772 Upgrade ray[serve] to version 1.5.0, allowing kfserving to be installed on python3.9
  python/kfserving/kfserving/kfserver.py
  python/kfserving/requirements.txt
  python/kfserving/setup.py
Labels: lgtm, approved, size/S, ok-to-test

#1777 Generate v0.6.1 release
  config/configmap/inferenceservice.yaml
  config/default/manager_image_patch.yaml
  config/web-app/deployment.yaml
  hack/generate-install.sh
  install/v0.6.1/kfserving.yaml
  install/v0.6.1/kfserving_kubeflow.yaml
Labels: lgtm, approved, size/XXL

#1779 Fix parallel inference example with Ray 1.5
  python/custom_model/model_remote.py
  python/kfserving/kfserving/kfserver.py
Labels: size/XS, approved
