Repository kserve/kserve, pull requests merged in 2021-04, with the labels that each got.

#1516 Cherry pick #1509 #1484
  cmd/agent/main.go
  docs/samples/batcher/basic/batcher_v1beta1.yaml
  go.mod
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/batcher/handler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
Labels: approved, lgtm, size/L

#1429 Watcher should not be started until models downloaded in MMS
  cmd/agent/main.go
  pkg/agent/puller.go
  pkg/agent/watcher.go
  pkg/agent/watcher_test.go
Labels: approved, lgtm, ok-to-test, size/L

#1518 Default agent path /ko-app/agent
  agent.Dockerfile
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
Labels: approved, lgtm, size/S

#1521 Update S3 example doc
  docs/samples/storage/s3/README.md
  docs/samples/storage/s3/s3_secret.yaml
  docs/samples/storage/s3/tensorflow_s3.yaml
Labels: approved, size/L

#1525 reconcile ingress routing virtualservice when annotations/labels are updated
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Labels: approved, lgtm, ok-to-test, size/M

#1526 Update logger samples for newer eventing versions
  docs/samples/logger/basic/README.md
  docs/samples/logger/basic/logger_demo.ipynb
  docs/samples/logger/basic/message-dumper.yaml
  docs/samples/logger/basic/sklearn-logging.yaml
  docs/samples/logger/knative-eventing/README.md
  docs/samples/logger/knative-eventing/broker.yaml
  docs/samples/logger/knative-eventing/logger_demo.ipynb
  docs/samples/logger/knative-eventing/message-dumper.yaml
  docs/samples/logger/knative-eventing/sklearn-logging.yaml
  docs/samples/logger/knative-eventing/trigger.yaml
Labels: approved, lgtm, size/L

#1458 update supported Istio and KNative versions
  README.md
Labels: approved, lgtm, size/XS

#1472 Change storage-init to use boto3
  python/kfserving/kfserving/storage.py
  python/kfserving/requirements.txt
  python/kfserving/test/test_s3_storage.py
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/L

#1527 Cherrypick #1525 to release-0.5
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Labels: approved, ok-to-test, size/M

#1528 bump knative 0.22
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XS

#1511 Add a GH action for the ui
  .github/workflows/web-app-docker-publish.yml
Labels: approved, lgtm, size/M

#1522 Adds condition for Trained Model to check if isvc predictor supports MMS
  pkg/apis/serving/v1alpha1/trained_model_status.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1alpha1/trainedmodel/controller_test.go
Labels: approved, lgtm, size/L

#1532 Cherry Pick #1513
  python/xgbserver/xgbserver/model.py
Labels: approved, lgtm, ok-to-test, size/XS

#1510 Introducing HTTPS protocol for MMS
  pkg/agent/downloader.go
  pkg/agent/storage/https.go
  pkg/agent/storage/provider.go
  pkg/agent/storage/utils.go
  pkg/agent/watcher_test.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
Labels: approved, lgtm, size/L

#1541 fix(web-app): Fix Grafana detection due to HEAD request
  web-app/frontend/src/app/pages/server-info/server-info.component.ts
Labels: approved, lgtm, size/S

#1544 Remove application cr from kubeflow overlay
  config/overlays/kubeflow/application.yaml
  config/overlays/kubeflow/kustomization.yaml
Labels: approved, lgtm, size/M

#1552 Fix broken link to ingress info in README
  docs/samples/v1beta1/sklearn/v1/README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1539 fix(bug): Added mutext for downloader providers. Fixes #1531
  cmd/agent/main.go
  pkg/agent/downloader.go
  pkg/agent/puller.go
  pkg/agent/watcher_test.go
Labels: approved, lgtm, size/M

#1549 Prevents /mnt/models/<model name> from being converted into a file
  pkg/agent/storage/gcs.go
  pkg/agent/storage/s3.go
  pkg/agent/watcher_test.go
Labels: approved, lgtm, size/S

#1538 Added annotation to use anonymous credentials for s3
  docs/samples/storage/s3/README.md
  docs/samples/storage/s3/s3_secret.yaml
  pkg/agent/storage/utils.go
  pkg/credentials/s3/s3_secret.go
  pkg/credentials/s3/s3_secret_test.go
Labels: approved, lgtm, size/L

#1512 Add manifests for the web app
  config/configmap/inferenceservice.yaml
  config/default/kustomization.yaml
  config/default/params.env
  config/default/params.yaml
  config/overlays/kubeflow/cluster-role.yaml
  config/overlays/kubeflow/kustomization.yaml
  config/overlays/kubeflow/params.env
  config/overlays/kubeflow/params.yaml
  config/overlays/kubeflow/patches/namespace.yaml
  config/overlays/kubeflow/patches/statefulset.yaml
  config/overlays/kubeflow/patches/web-app-sidecar.yaml
  config/overlays/kubeflow/patches/web-app-vsvc.yaml
  config/overlays/kubeflow/web-app-authorization-policy.yaml
  config/web-app/deployment.yaml
  config/web-app/istio.yaml
  config/web-app/kustomization.yaml
  config/web-app/rbac.yaml
  config/web-app/service.yaml
Labels: approved, lgtm, size/L

#1556 Generate 0.6.0 RC release manifests
  README.md
  hack/generate-install.sh
  install/v0.6.0-rc0/kfserving.yaml
  install/v0.6.0-rc0/kfserving_kubeflow.yaml
  python/kfserving/setup.py
Labels: approved, lgtm, size/XXL

#1434 Add Spark model inference example with export pmml file
  docs/samples/v1beta1/spark/DecisionTreeIris.pmml
  docs/samples/v1beta1/spark/README.md
  docs/samples/v1beta1/spark/deployment.yaml
  docs/samples/v1beta1/spark/iris.csv
  docs/samples/v1beta1/spark/pmml-input.json
  docs/samples/v1beta1/spark/spark_pmml.yaml
  docs/samples/v1beta1/spark/sparkml.py
Labels: approved, size/L

#1567 Fix python lint in the spark pmml example
  docs/samples/v1beta1/spark/sparkml.py
Labels: approved, lgtm, size/S

#1570 accept configmap violation
  hack/violation_exceptions.list
Labels: approved, lgtm, size/XS

#1564 Update quick install to use Istio 1.9.0
  hack/quick_install.sh
Labels: approved, lgtm, size/S

#1571 Update the README of the web app
  web-app/README.md
Labels: approved, lgtm, size/M
