Repository kserve/kserve, pull requests merged in 2021-03, with the labels that each got.

#1414 Check if isvc.Status.Default is not nil before trying to access pointer
  pkg/controller/v1alpha2/inferenceservice/controller_test.go
Labels: approved, lgtm, size/XS

#1412 reorg multi-model serving doc
  docs/MULTIMODELSERVING_GUIDE.md
  docs/samples/multimodelserving/sklearn/README.md
  docs/samples/multimodelserving/sklearn/inferenceservice.yaml
  docs/samples/multimodelserving/sklearn/trainedmodels.yaml
  docs/samples/multimodelserving/triton/README.md
  docs/samples/multimodelserving/triton/minio.yaml
  docs/samples/multimodelserving/triton/multi_model_triton.yaml
  docs/samples/multimodelserving/triton/s3_secret.yaml
  docs/samples/multimodelserving/triton/trained_model.yaml
  docs/samples/multimodelserving/triton/trained_model2.yaml
Labels: approved, lgtm, size/S

#1410 make v0.5.1 release
  hack/generate-install.sh
  install/v0.5.1/kfserving.yaml
  python/aixexplainer/setup.py
  python/alibiexplainer/setup.py
  python/artexplainer/setup.py
  python/kfserving/setup.py
  python/lgbserver/setup.py
  python/pmmlserver/setup.py
  python/pytorchserver/setup.py
  python/sklearnserver/setup.py
  python/xgbserver/setup.py
Labels: approved, lgtm, size/XXL

#1423 Update Torchserve transformer doc
  docs/samples/v1beta1/transformer/torchserve_image_transformer/README.md
  docs/samples/v1beta1/transformer/torchserve_image_transformer/image_transformer/__main__.py
  docs/samples/v1beta1/transformer/torchserve_image_transformer/setup.py
  docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer.Dockerfile
  docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer.yaml
Labels: approved, size/M

#1418 Add support for bias detection using AIF360
  docs/samples/explanation/aif/germancredit/README.md
  docs/samples/explanation/aif/germancredit/bias-v1alpha1.yaml
  docs/samples/explanation/aif/germancredit/bias.yaml
  docs/samples/explanation/aif/germancredit/get_logs.sh
  docs/samples/explanation/aif/germancredit/input.json
  docs/samples/explanation/aif/germancredit/json_from_logs.py
  docs/samples/explanation/aif/germancredit/message-dumper.yaml
  docs/samples/explanation/aif/germancredit/query_bias.py
  docs/samples/explanation/aif/germancredit/server/Dockerfile
  docs/samples/explanation/aif/germancredit/server/README.md
  docs/samples/explanation/aif/germancredit/server/model.py
  docs/samples/explanation/aif/germancredit/server/requirements.txt
  docs/samples/explanation/aif/germancredit/simulate_predicts.py
  python/aiffairness.Dockerfile
  python/aiffairness/README.md
  python/aiffairness/aifserver/__init__.py
  python/aiffairness/aifserver/__main__.py
  python/aiffairness/aifserver/model.py
  python/aiffairness/setup.py
Labels: approved, lgtm, size/XL

#1431 Fix PyPI link
  python/kfserving/setup.py
Labels: approved, lgtm, size/XS

#1432 Add requirement to use PodTemplate fields
  README.md
Labels: approved, lgtm, size/XS

#1441 Update and fix link in README regarding podspec
  README.md
Labels: approved, lgtm, size/XS

#1413 Added validation for framework in the trained model controller
  config/overlays/test/configmap/inferenceservice.yaml
  docs/DEVELOPER_GUIDE.md
  pkg/apis/serving/v1alpha1/trained_model_status.go
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/predictor.go
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_lightgbm.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/predictor_triton.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1alpha1/trainedmodel/controller_test.go
Labels: approved, lgtm, size/XXL

#1444 Fix sklearn links in readme
  docs/samples/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1443 update monitoring pointers
  README.md
Labels: approved, lgtm, size/XS

#1395 speed-up alibi-explainer image build
  python/alibiexplainer/setup.py
Labels: approved, lgtm, size/XS

#1449 Fix broken links to SKLearn Server README
  docs/samples/v1alpha2/sklearn/README.md
  docs/samples/v1beta1/sklearn/v1/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1334 support knative 0.19+
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/DEVELOPER_GUIDE.md
  hack/violation_exceptions.list
  pkg/constants/constants.go
  pkg/controller/v1alpha2/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
  test/e2e/logger/test_logger.py
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, ok-to-test, size/L

#1450 Add kubeflow install yaml for v0.5.1
  hack/generate-install.sh
  install/v0.5.1/kfserving_kubeflow.yaml
Labels: approved, lgtm, size/XXL

#1454 fix broken image-net downloader
  python/alibiexplainer/tests/persian_cat.json
  python/alibiexplainer/tests/test_anchor_images.py
Labels: approved, lgtm, size/XXL

#1455 Add Theo in reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#1452 Update tm name regex
  pkg/apis/serving/v1alpha1/trainedmodel_webhook.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
Labels: approved, lgtm, size/S

#1456 Fix link to inferenceservice configmap
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1405 Improve PMMLServer predict performance
  docs/samples/v1beta1/pmml/README.md
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  python/pmml.Dockerfile
  python/pmmlserver/pmmlserver/model.py
  python/pmmlserver/pmmlserver/test_model.py
  python/pmmlserver/setup.py
  test/e2e/predictor/test_pmml.py
Labels: approved, lgtm, ok-to-test, size/L

#1465 Pin image tags in release-0.5 branch
  config/configmap/inferenceservice.yaml
  config/default/manager_image_patch.yaml
Labels: approved, lgtm, size/M

#1464 Update README.md version to 0.5.1
  README.md
Labels: approved, lgtm, size/S

#1463 Fix storage initializer fails to download tar.gz and zip from uri with query params
  python/kfserving/kfserving/storage.py
  python/kfserving/test/test_storage.py
Labels: approved, lgtm, ok-to-test, size/M

#1471 Update pipelines sample code
  docs/samples/pipelines/README.md
  docs/samples/pipelines/kfs-pipeline.ipynb
  docs/samples/pipelines/sample-custom-model.py
  docs/samples/pipelines/sample-tf-pipeline.py
Labels: approved, lgtm, size/L

#1484 Resolve knative service diff to prevent dup revision
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
Labels: approved, lgtm, size/XS

#1486 Add Serverless Practitioners Summit 2020 Presentation
  docs/PRESENTATIONS.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1487 Cherry-pick of 'Update kubeflow overlay (#1424)' into release-0.5
  config/overlays/kubeflow/cluster-role.yaml
  config/overlays/kubeflow/kustomization.yaml
  config/overlays/kubeflow/namespace-patch.yaml
  config/overlays/kubeflow/statefulset-patch.yaml
Labels: approved, lgtm, size/M

#1478 Fix wrong name for kfserving-monitoring namespace
  docs/samples/metrics-and-monitoring/prometheus-operator/namespace.yaml
Labels: approved, lgtm, size/XS

#1494 add wait condition for cert-manager webhook
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/XS

#1493 Allow custom predictor to set protocol
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/constants/constants.go
Labels: approved, lgtm, size/M

#1498 Update pipelines documentation
  docs/samples/pipelines/README.md
  docs/samples/pipelines/kfs-pipeline-v1alpha2.ipynb
  docs/samples/pipelines/kfs-pipeline.ipynb
  docs/samples/pipelines/sample-custom-model.py
Labels: approved, lgtm, size/L

#1470 Add Multi Model Server support for custom spec
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1509 Add readiness check to model agent
  cmd/agent/main.go
  docs/samples/batcher/basic/batcher_v1beta1.yaml
  go.mod
  pkg/batcher/handler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
Labels: approved, lgtm, size/L

#1482 bump e2e tests to k8s-1.19, istio-1.8.2, knative-0.21
  test/scripts/create-cluster.sh
  test/scripts/run-e2e-tests.sh
Labels: approved, lgtm, size/S

#1446 Validate trained model memory based on parent inference service
  pkg/apis/serving/v1alpha1/trained_model.go
  pkg/apis/serving/v1alpha1/trained_model_status.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1alpha1/trainedmodel/controller_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  test/e2e/predictor/test_multi_model_serving.py
Labels: approved, lgtm, size/XL

#1513 [xgboostserver] Convert list input to numpy array before creating DMatrix
  python/xgbserver/xgbserver/model.py
Labels: approved, lgtm, ok-to-test, size/XS
