Repository kserve/kserve, pull requests merged in 2021-01, with the labels that each got.

#1267 Add v1beta1 canary example and improve status print
  config/crd/serving.kubeflow.org_inferenceservices.yaml
  docs/apis/v1beta1/README.md
  docs/samples/v1beta1/rollout/README.md
  docs/samples/v1beta1/rollout/canary.png
  docs/samples/v1beta1/rollout/canary.yaml
  docs/samples/v1beta1/rollout/default.yaml
  docs/samples/v1beta1/rollout/pinned.yaml
  docs/samples/v1beta1/rollout/promotion.yaml
  hack/violation_exceptions.list
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
Labels: approved, size/XL

#1277 Use ModelClassName to differentiate kfserver or torchserve imp for v1 protocol
  docs/apis/v1beta1/README.md
  docs/samples/v1beta1/torchserve/autoscaling/README.md
  docs/samples/v1beta1/torchserve/autoscaling/autoscaling.yaml
  docs/samples/v1beta1/torchserve/bert/bert.yaml
  docs/samples/v1beta1/torchserve/canary/README.md
  docs/samples/v1beta1/torchserve/canary/canary.yaml
  docs/samples/v1beta1/torchserve/gpu.yaml
  docs/samples/v1beta1/torchserve/metrics/README.md
  docs/samples/v1beta1/torchserve/metrics/metrics.yaml
  docs/samples/v1beta1/torchserve/torchserve.yaml
  docs/samples/v1beta1/torchserve/transformer.yaml
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/swagger.json
  test/e2e/predictor/test_torchserve.py
Labels: approved, size/L

#1262 Remove redundant code in ONNX InferenceService sample
  docs/samples/v1alpha2/onnx/mosaic-onnx.ipynb
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1281 Fix model puller flag and logging conflicts
  cmd/agent/main.go
  docs/samples/v1beta1/triton/multimodel/s3_secret.yaml
  pkg/agent/downloader.go
  pkg/agent/puller.go
  pkg/agent/syncer.go
  pkg/agent/watcher.go
  pkg/agent/watcher_test.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/constants/constants.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
  test/e2e/predictor/test_torchserve.py
Labels: approved, lgtm, size/L

#1276 Prometheus based metrics and monitoring for KFServing models
  docs/samples/metrics-and-monitoring/README.md
  docs/samples/metrics-and-monitoring/prometheus-operator/kustomization.yaml
  docs/samples/metrics-and-monitoring/prometheus-operator/namespace.yaml
  docs/samples/metrics-and-monitoring/prometheus/clusterrole.yaml
  docs/samples/metrics-and-monitoring/prometheus/clusterrolebinding.yaml
  docs/samples/metrics-and-monitoring/prometheus/kfserving-service-monitor.yaml
  docs/samples/metrics-and-monitoring/prometheus/kustomization.yaml
  docs/samples/metrics-and-monitoring/prometheus/prometheus.yaml
  docs/samples/metrics-and-monitoring/prometheus/serviceaccount.yaml
  docs/samples/metrics-and-monitoring/requestcount.png
  docs/samples/metrics-and-monitoring/requestlatency.png
Labels: approved, lgtm, ok-to-test, size/L

#1278 Add jagadeeshi2i to reviewer
  config/configmap/inferenceservice.yaml
Labels: approved, size/S

#1287 Merge batcher to model agent
  .github/workflows/batcher-docker-publisher.yml
  Makefile
  cmd/agent/main.go
  cmd/batcher/main.go
  config/configmap/inferenceservice.yaml
  docs/samples/batcher/basic/batcher_v1beta1.yaml
  docs/samples/batcher/basic/pytorch-batcher.yaml
  hack/image_patch_dev.sh
  pkg/batcher/conf/app.conf
  pkg/batcher/controllers/main_controller.go
  pkg/batcher/handler.go
  pkg/batcher/handler_test.go
  pkg/batcher/routers/router.go
  pkg/batcher/server.go
  pkg/batcher/server_test.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
  pkg/webhook/admission/pod/batcher_injector.go
  pkg/webhook/admission/pod/mutator.go
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XXL

#1288 Add the missing input file for v1beta1 rollout example
  docs/samples/v1beta1/rollout/input.json
Labels: approved, size/S

#1289 Publish final 0.5 RC release candidate 0.5.0-rc2
  config/configmap/inferenceservice.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.5.0-rc2/kfserving.yaml
Labels: approved, lgtm, size/XXL

#1291 Fix readme to correct sklearn perf.yaml location
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1282 Update KFSERVING_DEBUG_GUIDE.md
  docs/KFSERVING_DEBUG_GUIDE.md
Labels: approved, lgtm, ok-to-test, size/XS

#1292 Update developer guide with compatible yq version 3.*
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1284 Workaround for kustomize bug triggered in metrics and monitoring instructions
  docs/samples/metrics-and-monitoring/README.md
  docs/samples/metrics-and-monitoring/prometheus/clusterrolebinding.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1290 Add MMS support for Scikit-Learn and XGBoost V2
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  docs/samples/v1beta1/sklearn/README.md
  docs/samples/v1beta1/sklearn/requirements.txt
  docs/samples/v1beta1/xgboost/README.md
  docs/samples/v1beta1/xgboost/requirements.txt
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/constants/mlserver.go
Labels: approved, lgtm, size/L

#1301 Fix transformer image build path
  test/workflows/components/workflows.libsonnet
Labels: approved, lgtm, size/XS

#1105 Add GCS support and tests
  cmd/agent/main.go
  go.mod
  go.sum
  pkg/agent/downloader.go
  pkg/agent/mocks/gcsmock.go
  pkg/agent/mocks/s3mock.go
  pkg/agent/storage/gcs.go
  pkg/agent/storage/provider.go
  pkg/agent/watcher_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#1299 Update OpenShift documentation
  docs/OPENSHIFT_GUIDE.md
Labels: approved, lgtm, size/XS

#1303 Fix isvc_watch for traffic status spec and remove version argument
  docs/samples/client/kfserving_sdk_v1beta1_sample.ipynb
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/api/kf_serving_watch.py
  python/kfserving/kfserving/constants/constants.py
  test/e2e/explainer/test_art_explainer.py
  test/e2e/predictor/test_canary.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_torchserve.py
  test/e2e/predictor/test_xgboost.py
Labels: approved, lgtm, size/L

#1254 Reference local copy of predict v2 grpc proto file
  docs/predict-api/v2/README.md
  docs/predict-api/v2/grpc_predict_v2.proto
Labels: approved, lgtm, ok-to-test, size/L

#1313 Add nil conversion for v1beta1 -> v1alpha2 explainer spec
  pkg/apis/serving/v1alpha2/inferenceservice_conversion.go
  pkg/apis/serving/v1alpha2/inferenceservice_conversion_test.go
Labels: approved, lgtm, size/L

#1306 Support for gcs access without credentials and multi-model serving e2e test with sklearn/xgboost examples + docs
  cmd/agent/main.go
  docs/MULTIMODELSERVING_GUIDE.md
  docs/diagrams/mms-design.png
  docs/samples/v1beta1/sklearn/multimodel/README.md
  docs/samples/v1beta1/sklearn/multimodel/inferenceservice.yaml
  docs/samples/v1beta1/sklearn/multimodel/trainedmodels.yaml
  go.mod
  pkg/agent/downloader.go
  pkg/agent/storage/gcs.go
  pkg/agent/storage/utils.go
  pkg/agent/watcher_test.go
  pkg/apis/serving/v1alpha1/trained_model.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  python/kfserving/kfserving/__init__.py
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/constants/constants.py
  test/e2e/common/utils.py
  test/e2e/predictor/test_multi_model_serving.py
Labels: approved, lgtm, ok-to-test, size/XL

#1316 Convert canary e2e test to use v1beta1 and add reject canary spec on v1alpha2
  docs/samples/client/kfserving_sdk_v1alpha2_sample.ipynb
  pkg/agent/mocks/gcsmock.go
  pkg/agent/storage/provider.go
  pkg/apis/serving/v1alpha2/inferenceservice_conversion.go
  pkg/apis/serving/v1alpha2/inferenceservice_validation.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/test/test_inference_service_client.py
  test/e2e/predictor/test_canary.py
  test/e2e/predictor/test_sklearn.py
Labels: approved, lgtm, size/L

#1312 Adds Adopters.MD, adding Halodoc ID to the list
  ADOPTERS.md
Labels: approved, lgtm, ok-to-test, size/XS

#1322 Add E2E tests for MMS with the V2 protocol
  python/kfserving/kfserving/api/kf_serving_client.py
  test/e2e/predictor/test_multi_model_serving.py
Labels: approved, lgtm, size/L

#1323 Add OpenAPI schema for V2 dataplane
  docs/predict-api/v2/rest_predict_v2.yaml
Labels: approved, lgtm, size/L

#1319 Url and Address Url set in TrainedModel Status using InferenceService Status
  config/crd/serving.kubeflow.org_trainedmodels.yaml
  pkg/apis/serving/v1alpha1/trained_model_status.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
  pkg/controller/v1alpha1/trainedmodel/controller_test.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#1330 Add Tensorflow v1beta1 gRPC example
  docs/samples/v1beta1/tensorflow/README.md
  docs/samples/v1beta1/tensorflow/canary.yaml
  docs/samples/v1beta1/tensorflow/grpc.yaml
  docs/samples/v1beta1/tensorflow/grpc_client.py
  docs/samples/v1beta1/tensorflow/input.json
  docs/samples/v1beta1/tensorflow/tensorflow.yaml
  docs/samples/v1beta1/triton/torchscript/README.md
  docs/samples/v1beta1/triton/torchscript/torch_transformer.yaml
Labels: approved, size/L
