Repository kserve/kserve, pull requests merged in 2021-05, with the labels that each got.

#1584 Docs update
  docs/apis/v1beta1/README.md
  hack/violation_exceptions.list
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
Labels: approved, lgtm, size/XL

#1586 Update Go version requirement in developer's guide
  docs/DEVELOPER_GUIDE.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1573 mwa(front): Don't hardcode the base-url
  web-app/frontend/package.json
Labels: approved, lgtm, size/XS

#1554 Added benchmark for multi-model serving
  docs/MULTIMODELSERVING_GUIDE.md
  docs/samples/multimodelserving/benchmark/BENCHMARK.md
  docs/samples/multimodelserving/benchmark/plots/bert_10_qps_gpu.png
  docs/samples/multimodelserving/benchmark/plots/bert_20_qps_gpu.png
  docs/samples/multimodelserving/benchmark/plots/bert_30_qps_gpu.png
  docs/samples/multimodelserving/benchmark/plots/bert_40_qps_gpu.png
  docs/samples/multimodelserving/benchmark/plots/bert_5_qps_gpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_100_qps_cpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_150_qps_cpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_200_qps_cpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_250_qps_cpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_25_qps_cpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_500_qps_cpu.png
  docs/samples/multimodelserving/benchmark/plots/simple_string_50_qps_cpu.png
Labels: approved, lgtm, size/L

#1588 fix(docs): update broken link in sklearn predictor README
  python/sklearnserver/README.md
Labels: approved, lgtm, size/XS

#1587 fix(docstring): fix docstring for XGB predictor.
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/swagger.json
Labels: approved, lgtm, size/XS

#1568 [Predict Protocol V2] Fix rest_predict_v2.yaml definition
  docs/predict-api/v2/rest_predict_v2.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1598 Increase timeout for tabular explainer e2e test
  test/e2e/explainer/test_tabular_explainer.py
Labels: approved, lgtm, size/XS

#1566 Fix explainer_url to use explainer_host
  docs/samples/v1beta1/transformer/torchserve_image_transformer/README.md
  python/kfserving/kfserving/kfmodel.py
Labels: approved, lgtm, ok-to-test, size/XS

#1583 docs: fixes gsutil command in the End to end kafka inference example
  docs/samples/kafka/README.md
  docs/samples/kafka/setup.py
Labels: approved, lgtm, size/XS

#1555 Update OpenShift documentation
  docs/OPENSHIFT_GUIDE.md
Labels: approved, lgtm, size/L

#1602 Fix torchserve v1beta1 examples for enabling KFServing inference protocol
  docs/samples/v1beta1/torchserve/README.md
  docs/samples/v1beta1/torchserve/bert/config.properties
  docs/samples/v1beta1/torchserve/config.properties
Labels: approved, size/S

#1597 add logger in explainer and transformer
  pkg/controller/v1beta1/inferenceservice/components/component.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
Labels: approved, lgtm, size/L

#1603 fix certificate unknown authority error using self-sign-ca scripts
  hack/self-signed-ca.sh
Labels: approved, lgtm, ok-to-test, size/S

#1599 fix(python): regenerate python part based upon current master
  pkg/agent/mocks/gcsmock.go
  pkg/agent/mocks/s3mock.go
  pkg/agent/storage/gcs.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  python/kfserving/docs/V1alpha1ModelSpec.md
  python/kfserving/docs/V1alpha1TrainedModelSpec.md
  python/kfserving/docs/V1beta1CustomExplainer.md
  python/kfserving/docs/V1beta1CustomPredictor.md
  python/kfserving/docs/V1beta1CustomTransformer.md
  python/kfserving/docs/V1beta1ExplainerSpec.md
  python/kfserving/docs/V1beta1IngressConfig.md
  python/kfserving/docs/V1beta1PodSpec.md
  python/kfserving/docs/V1beta1PredictorConfig.md
  python/kfserving/docs/V1beta1PredictorSpec.md
  python/kfserving/docs/V1beta1TransformerSpec.md
  python/kfserving/kfserving/models/v1alpha1_model_spec.py
  python/kfserving/kfserving/models/v1beta1_custom_explainer.py
  python/kfserving/kfserving/models/v1beta1_custom_predictor.py
  python/kfserving/kfserving/models/v1beta1_custom_transformer.py
  python/kfserving/kfserving/models/v1beta1_explainer_spec.py
  python/kfserving/kfserving/models/v1beta1_ingress_config.py
  python/kfserving/kfserving/models/v1beta1_pod_spec.py
  python/kfserving/kfserving/models/v1beta1_predictor_config.py
  python/kfserving/kfserving/models/v1beta1_predictor_spec.py
  python/kfserving/kfserving/models/v1beta1_transformer_spec.py
  python/kfserving/test/test_v1alpha1_model_spec.py
  python/kfserving/test/test_v1beta1_inference_services_config.py
  python/kfserving/test/test_v1beta1_predictor_config.py
  python/kfserving/test/test_v1beta1_predictor_protocols.py
  python/kfserving/test/test_v1beta1_predictors_config.py
Labels: approved, lgtm, size/XL

#1616 Update path in README to be consistent with code
  docs/samples/logger/knative-eventing/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#1622 Update all e2e tests to v1beta1
  python/kfserving/docs/KFServingClient.md
  python/kfserving/kfserving/api/kf_serving_client.py
  python/kfserving/kfserving/constants/constants.py
  test/e2e/batcher/test_batcher.py
  test/e2e/explainer/test_aix_explainer.py
  test/e2e/explainer/test_art_explainer.py
  test/e2e/explainer/test_tabular_explainer.py
  test/e2e/logger/test_logger.py
  test/e2e/predictor/test_lightgbm.py
  test/e2e/predictor/test_pmml.py
  test/e2e/predictor/test_pytorch.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_tensorflow.py
  test/e2e/predictor/test_torchserve.py
  test/e2e/predictor/test_triton.py
  test/e2e/predictor/test_xgboost.py
  test/e2e/transformer/test_transformer.py
  test/scripts/build-agent.sh
  test/scripts/build-batcher.sh
  test/scripts/build-custom-bert-transformer.sh
  test/scripts/build-custom-image-transformer.sh
  test/scripts/build-kfserving.sh
  test/scripts/build-logger.sh
  test/scripts/build-python-image.sh
Labels: approved, lgtm, size/XL

#1623 Update MMS docs for 0.6 release
  config/configmap/inferenceservice.yaml
  docs/MULTIMODELSERVING_GUIDE.md
  docs/diagrams/model_agent.png
  docs/samples/README.md
  docs/samples/multimodelserving/benchmark/BENCHMARK.md
  docs/samples/multimodelserving/sklearn/README.md
  docs/samples/multimodelserving/sklearn/inferenceservice.yaml
  docs/samples/multimodelserving/triton/README.md
  docs/samples/multimodelserving/triton/multi_model_triton.yaml
  docs/samples/multimodelserving/triton/perf.yaml
  docs/samples/multimodelserving/triton/trained_model.yaml
  docs/samples/multimodelserving/triton/trained_model2.yaml
Labels: approved, lgtm, size/XXL

#1633 Fix broken url
  docs/samples/v1beta1/sklearn/v2/README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS
