Repository kserve/kserve, pull requests merged in 2022-06, with the labels that each got.

#2206 chore: Update E2E tests to use GH Actions
  .github/workflows/e2e-test.yml
  config/overlays/test/configmap/inferenceservice.yaml
  config/overlays/test/manager_image_patch.yaml
  config/overlays/test/minio/minio-deployment.yaml
  config/overlays/test/runtimes/kustomization.yaml
  test/e2e/batcher/test_batcher.py
  test/e2e/batcher/test_batcher_custom_port.py
  test/e2e/batcher/test_raw_batcher.py
  test/e2e/explainer/test_aix_explainer.py
  test/e2e/explainer/test_art_explainer.py
  test/e2e/explainer/test_tabular_explainer.py
  test/e2e/logger/test_logger.py
  test/e2e/logger/test_raw_logger.py
  test/e2e/predictor/test_canary.py
  test/e2e/predictor/test_lightgbm.py
  test/e2e/predictor/test_mlflow.py
  test/e2e/predictor/test_multi_model_serving.py
  test/e2e/predictor/test_paddle.py
  test/e2e/predictor/test_pmml.py
  test/e2e/predictor/test_pytorch.py
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_tensorflow.py
  test/e2e/predictor/test_torchserve.py
  test/e2e/predictor/test_triton.py
  test/e2e/predictor/test_xgboost.py
  test/e2e/storagespec/test_s3_storagespec.py
  test/e2e/transformer/test_raw_transformer.py
  test/e2e/transformer/test_transformer.py
  test/overlays/istio/kustomization.yaml
  test/overlays/istio/requests_patch.yaml
  test/overlays/knative/kustomization.yaml
  test/overlays/knative/requests_patch.yaml
  test/scripts/aws/create-cluster.sh
  test/scripts/aws/delete-cluster.sh
  test/scripts/aws/post-e2e-tests.sh
  test/scripts/aws/run-e2e-tests.sh
  test/scripts/gh-actions/build-images.sh
  test/scripts/gh-actions/run-e2e-tests.sh
  test/scripts/gh-actions/setup-deps.sh
  test/scripts/gh-actions/setup-kserve.sh
  test/scripts/unit-test.sh
Labels: lgtm, approved

#2215 Update deprecated gcs bucket
  docs/samples/v1beta1/triton/bert/README.md
  docs/samples/v1beta1/triton/bert/bert_v1beta1.yaml
  test/benchmark/README.md
  test/benchmark/tf_flowers.yaml
  test/benchmark/tf_flowers_hpa.yaml
  test/e2e/predictor/test_canary.py
  test/e2e/predictor/test_pytorch.py
  test/e2e/predictor/test_xgboost.py
  tools/tf2openapi/generator/generate_test.go
Labels: approved

#2204 Update Feast transformer to support ModelMesh
  docs/samples/v1beta1/transformer/feast/README.md
  docs/samples/v1beta1/transformer/feast/driver_transformer/__main__.py
  docs/samples/v1beta1/transformer/feast/driver_transformer/driver_transformer.py
  docs/samples/v1beta1/transformer/feast/driver_transformer_modelmesh.yaml
Labels: lgtm, approved

#1910 Initial inference graph API implementation
  Makefile
  cmd/manager/main.go
  cmd/router/main.go
  cmd/router/main_test.go
  config/configmap/inferenceservice.yaml
  config/crd/kustomization.yaml
  config/crd/serving.kserve.io_inferencegraphs.yaml
  config/default/webhookcainjection_patch.yaml
  config/overlays/development/configmap/ko_resolve_router
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  docs/samples/graph/README.md
  docs/samples/graph/ensemble.yaml
  docs/samples/graph/ensembleNode.png
  docs/samples/graph/graph.png
  docs/samples/graph/sequence.yaml
  docs/samples/graph/singleNode.png
  docs/samples/graph/splitter.yaml
  docs/samples/graph/splitterNode.png
  docs/samples/graph/switch.yaml
  docs/samples/graph/switchNode.png
  go.mod
  go.sum
  hack/image_patch_dev.sh
  hack/violation_exceptions.list
  manifests/charts/templates/webhookconfiguration.yaml
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/apis/serving/v1alpha1/inference_graph_validation.go
  pkg/apis/serving/v1alpha1/v1alpha1.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
  router.Dockerfile
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2202 Allow InferenceService url scheme to be configurable
  config/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
Labels: lgtm, approved

#2077 Support webhdfs in storageURI and storage spec
  docs/samples/storage/hdfs/README.md
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/explainer_alibi_test.go
  pkg/apis/serving/v1beta1/explainer_custom_test.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_paddle_test.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
  pkg/controller/v1beta1/inferenceservice/components/component.go
  pkg/credentials/hdfs/hdfs_secret.go
  pkg/credentials/hdfs/hdfs_secret_test.go
  pkg/credentials/service_account_credentials.go
  pkg/credentials/service_account_credentials_test.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  python/kserve/kserve/storage.py
  python/kserve/test/test_storage.py
  python/storage-initializer.Dockerfile
Labels: lgtm, approved

#2214 Bump torchserve version
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  config/runtimes/kustomization.yaml
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Labels: lgtm, approved

#2216 Update python dep for kserve sdk
  .github/workflows/python-test.yml
  python/kserve/requirements.txt
  python/kserve/setup.py
  test/workflows/app.yaml
  test/workflows/components/params.libsonnet
  test/workflows/components/workflows.jsonnet
  test/workflows/components/workflows.libsonnet
  test/workflows/environments/base.libsonnet
  test/workflows/environments/releasing/main.jsonnet
  test/workflows/environments/releasing/params.libsonnet
  test/workflows/lib/v1.7.0/k.libsonnet
  test/workflows/lib/v1.7.0/k8s.libsonnet
  test/workflows/lib/v1.7.0/swagger.json
Labels: lgtm, approved

#2032 Add install script for KServe and ModelMesh
  hack/install_kserve_mm.sh
Labels: lgtm, approved

#2189 Publish helm chart as release asset
  .github/workflows/helm-publish.yml
  charts/kserve/Chart.yaml
  charts/kserve/crds/serving.kserve.io_clusterservingruntimes.yaml
  charts/kserve/crds/serving.kserve.io_inferenceservices.yaml
  charts/kserve/crds/serving.kserve.io_predictor.yaml
  charts/kserve/crds/serving.kserve.io_servingruntime.yaml
  charts/kserve/crds/serving.kserve.io_trainedmodels.yaml
  charts/kserve/templates/certificate.yaml
  charts/kserve/templates/clusterrole.yaml
  charts/kserve/templates/clusterrolebinding.yaml
  charts/kserve/templates/clusterservingruntimes.yaml
  charts/kserve/templates/configmap.yaml
  charts/kserve/templates/deployment.yaml
  charts/kserve/templates/role.yaml
  charts/kserve/templates/rolebinding.yaml
  charts/kserve/templates/service.yaml
  charts/kserve/templates/serviceaccount.yaml
  charts/kserve/templates/servingruntimes.yaml
  charts/kserve/templates/webhookconfiguration.yaml
  charts/kserve/values.yaml
  hack/generate-install.sh
Labels: lgtm, approved, ok-to-test

#2223 update graph sample
  docs/samples/graph/README.md
  docs/samples/graph/bgtest/Dockerfile
  docs/samples/graph/bgtest/README.md
  docs/samples/graph/bgtest/bgtest/go.mod
  docs/samples/graph/bgtest/bgtest/go.sum
  docs/samples/graph/bgtest/bgtest/main.go
  docs/samples/graph/ensemble.yaml
  docs/samples/graph/graph.png
  docs/samples/graph/images/ensembleNode.png
  docs/samples/graph/images/graph.png
  docs/samples/graph/images/sequence.png
  docs/samples/graph/images/splitterNode.png
  docs/samples/graph/images/switchNode.png
  docs/samples/graph/iris-input.json
  docs/samples/graph/singleNode.png
  docs/samples/graph/switch.yaml
Labels: lgtm, approved

#2229 manifest for release v0.9.0-rc0
  charts/kserve/Chart.yaml
  charts/kserve/crds/serving.kserve.io_clusterservingruntimes.yaml
  charts/kserve/crds/serving.kserve.io_inferencegraphs.yaml
  charts/kserve/crds/serving.kserve.io_inferenceservices.yaml
  charts/kserve/values.yaml
  hack/generate-install.sh
  install/v0.9.0-rc0/kserve-runtimes.yaml
  install/v0.9.0-rc0/kserve.yaml
  install/v0.9.0-rc0/kserve_kubeflow.yaml
Labels: lgtm, approved

#2082 Added target and metric to components
  config/crd/serving.kserve.io_inferenceservices.yaml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/credentials/service_account_credentials_test.go
  python/kserve/docs/V1alpha1BuiltInAdapter.md
  python/kserve/docs/V1alpha1ServingRuntimePodSpec.md
  python/kserve/docs/V1alpha1ServingRuntimeSpec.md
  python/kserve/docs/V1beta1ComponentExtensionSpec.md
  python/kserve/docs/V1beta1ExplainerSpec.md
  python/kserve/docs/V1beta1PredictorSpec.md
  python/kserve/docs/V1beta1TransformerSpec.md
  python/kserve/kserve/models/v1alpha1_built_in_adapter.py
  python/kserve/kserve/models/v1alpha1_serving_runtime_pod_spec.py
  python/kserve/kserve/models/v1alpha1_serving_runtime_spec.py
  python/kserve/kserve/models/v1beta1_component_extension_spec.py
  python/kserve/kserve/models/v1beta1_explainer_spec.py
  python/kserve/kserve/models/v1beta1_predictor_spec.py
  python/kserve/kserve/models/v1beta1_transformer_spec.py
  test/crds/serving.kserve.io_inferenceservices.yaml
  test/e2e/predictor/test_autoscaling.py
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm, approved

#2243 Update 0.9.0-rc0 release manifest and github actions
  .github/workflows/router-docker-publish.yml
  charts/kserve/crds/serving.kserve.io_inferenceservices.yaml
  charts/kserve/crds/serving.kserve.io_servingruntime.yaml
  charts/kserve/templates/clusterrole.yaml
  charts/kserve/templates/configmap.yaml
  charts/kserve/templates/deployment.yaml
  charts/kserve/templates/webhookconfiguration.yaml
  charts/kserve/values.yaml
  install/v0.9.0-rc0/kserve-runtimes.yaml
  install/v0.9.0-rc0/kserve.yaml
  install/v0.9.0-rc0/kserve_kubeflow.yaml
  pkg/agent/watcher_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
Labels: lgtm, approved

#2235 chore: Update e2e k8s version to 1.22
  .github/workflows/e2e-test.yml
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm, approved

#2259 Update quick install dependencies
  hack/python-sdk/README.md
  hack/quick_install.sh
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm, approved

#2271 Update art explainer readme bash script
  docs/samples/explanation/art/mnist/README.md
Labels: lgtm, approved

#2262 mlserver version upgrade and handle storagespec in defaults
  charts/kserve/values.yaml
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  config/runtimes/kustomization.yaml
  pkg/apis/serving/v1beta1/inference_service_defaults.go
Labels: lgtm, approved

#2279 fix: hpa scale up failed, when using rawdeployment
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
Labels: lgtm, approved, cherrypick-approved

#2286 Literal $ in URL for v2 inference protocol doc
  docs/predict-api/v2/required_api.md
Labels: lgtm, approved

#2288 fix: Prevent all predictor defaulting with MM
  pkg/apis/serving/v1beta1/inference_service_defaults.go
Labels: lgtm, approved

#2296 chore: Update leader-election-role name
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
Labels: lgtm, approved

#2298 Cherrypick: chore: Update leader-election-role name (#2296)
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  install/v0.8.0/kserve.yaml
  install/v0.8.0/kserve_kubeflow.yaml
Labels: lgtm, approved
