Repository kserve/kserve, pull requests merged in 2022-10, with the labels that each got.

#2440 add labels and annotations to ServingRuntimePodSpec
  config/crd/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/serving.kserve.io_servingruntimes.yaml
  pkg/apis/serving/v1alpha1/servingruntime_types.go
  pkg/apis/serving/v1alpha1/servingruntime_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/utils/utils_test.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2446 Update quick install to use Istio 1.15
  hack/quick_install.sh
Labels: approved

#2459 adding prometheus port configs for aggregating metrics in queue proxy
  config/runtimes/kserve-lgbserver.yaml
  config/runtimes/kserve-mlserver.yaml
  config/runtimes/kserve-paddleserver.yaml
  config/runtimes/kserve-pmmlserver.yaml
  config/runtimes/kserve-sklearnserver.yaml
  config/runtimes/kserve-tensorflow-serving.yaml
  config/runtimes/kserve-torchserve.yaml
  config/runtimes/kserve-tritonserver.yaml
  config/runtimes/kserve-xgbserver.yaml
  pkg/constants/constants.go
  pkg/webhook/admission/pod/metrics_aggregate_injector.go
  pkg/webhook/admission/pod/metrics_aggregate_injector_test.go
  pkg/webhook/admission/pod/mutator.go
Labels: lgtm, approved

#2418 Retrieve SAS token
  python/kserve/kserve/storage.py
Labels: lgtm, approved

#2351 Code coverage
  .cov-ignore
  .github/workflows/go.yml
  Makefile
  README.md
  coverage.sh
  pkg/agent/downloader_test.go
  pkg/agent/storage/utils_test.go
  pkg/agent/watcher_test.go
  pkg/apis/serving/v1alpha1/inference_graph_validation.go
  pkg/apis/serving/v1alpha1/inference_graph_validation_test.go
  pkg/apis/serving/v1alpha1/servingruntime_types_test.go
  pkg/apis/serving/v1alpha1/trained_model_status_test.go
  pkg/apis/serving/v1alpha1/trained_model_test.go
  pkg/apis/serving/v1beta1/component_test.go
  pkg/apis/serving/v1beta1/configmap_test.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/apis/serving/v1beta1/inference_service_status_test.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_model_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_paddle_test.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/batcher/handler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  pkg/credentials/service_account_credentials_test.go
  pkg/modelconfig/configmap_test.go
  pkg/utils/utils_test.go
  pkg/webhook/admission/pod/agent_injector_test.go
  pkg/webhook/admission/pod/batcher_injector_test.go
  pkg/webhook/admission/pod/mutator_test.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  python/kserve/test/test_creds_utils.py
Labels: lgtm, approved

#2443 Add ImagePullSecrets to ServingRuntimePodSpec
  config/crd/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/serving.kserve.io_servingruntimes.yaml
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha1/servingruntime_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2472 Update CIFAR-10 Outlier Detector sample
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10_outlier.ipynb
Labels: lgtm, approved

#2101 Fix cluster local label InferenceService
  docs/samples/v1beta1/advanced/cluster_local.yaml
Labels: lgtm, approved, needs-ok-to-test

#2355 Add an example of Lime text explainer from AIX360 toolkit
  docs/samples/explanation/aix/Fetch_20newsgroups/README.md
  docs/samples/explanation/aix/Fetch_20newsgroups/aix-explainer.yaml
  docs/samples/explanation/aix/Fetch_20newsgroups/aix-explanation.jpeg
  docs/samples/explanation/aix/Fetch_20newsgroups/query_explain.py
  docs/samples/explanation/aix/Fetch_20newsgroups/train_rf.py
  python/aixexplainer/README.md
  python/aixexplainer/aixserver/model.py
Labels: lgtm, approved

#2480 Updated yq version (v4.28.1)
  .github/workflows/go.yml
  Makefile
  hack/kserve_migration/Dockerfile
  hack/kserve_migration/kserve_migration.sh
  test/scripts/aws/run-e2e-tests.sh
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm, approved

#2481 Supports more authentication approaches on Azure in Storage Initializer - Build fix
  python/kserve/test/test_creds_utils.py
Labels: lgtm, approved

#2396 Propagating IG headers to it's nodes.
  cmd/router/main.go
  cmd/router/main_test.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
Labels: lgtm, approved, hacktoberfest

#2475 Restoring init container support.
  Makefile
  config/crd/serving.kserve.io_inferenceservices.yaml
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved, hacktoberfest, hacktoberfest-accepted

#2492 Update KServe generated client code
  Makefile
  go.mod
  pkg/apis/serving/v1alpha1/inference_graph_validation_test.go
  pkg/apis/serving/v1alpha1/trained_model_status_test.go
  pkg/apis/serving/v1alpha1/trained_model_test.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/clientv1alpha1/clientset/versioned/fake/register.go
  pkg/clientv1alpha1/clientset/versioned/scheme/register.go
  pkg/webhook/admission/pod/mutator_test.go
  python/kserve/docs/V1alpha1InferenceRouter.md
  python/kserve/docs/V1alpha1ServingRuntimePodSpec.md
  python/kserve/docs/V1alpha1ServingRuntimeSpec.md
  python/kserve/docs/V1beta1InferenceServicesConfig.md
  python/kserve/kserve/models/__init__.py
  python/kserve/kserve/models/v1alpha1_serving_runtime_pod_spec.py
  python/kserve/kserve/models/v1alpha1_serving_runtime_spec.py
  python/kserve/kserve/models/v1beta1_inference_services_config.py
  python/kserve/test/test_dataplane.py
  python/kserve/test/test_model_repository_extension.py
  python/kserve/test/test_v1beta1_inference_services_config.py
Labels: approved
