Repository kserve/kserve, pull requests merged in 2022-02, with the labels that each got.

#2021 Fix AIX explainer example pip dependency
  docs/samples/explanation/aix/mnist/aix-explainer-v1alpha2.yaml
  docs/samples/explanation/aix/mnist/requirements.txt
  docs/samples/explanation/aix/mnist/rfserver/rf.Dockerfile
  docs/samples/explanation/aix/mnist/rfserver/setup.py
Labels: approved

#2028 Update Feast transformer
  docs/samples/v1beta1/transformer/feast/README.md
  docs/samples/v1beta1/transformer/feast/driver_transformer.yaml
Labels: lgtm, approved

#1905 Made changes to use probe port injected from agent injector
  cmd/agent/main.go
  pkg/webhook/admission/pod/agent_injector.go
  test/e2e/batcher/test_batcher_custom_port.py
  test/e2e/common/utils.py
  test/e2e/data/iris_batch_input.json
Labels: lgtm, approved

#1988 Support extracting archive with directories
  pkg/agent/storage/https.go
Labels: lgtm, approved, ok-to-test

#2030 added torchserve defaults in mutator
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  test/e2e/predictor/test_torchserve.py
Labels: lgtm, approved

#2016 Fix status condition names
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/openapi_generated.go
Labels: lgtm, approved

#2033 Update lightgbm version
  config/overlays/test/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/constants/constants.go
  python/lgbserver/setup.py
Labels: lgtm, approved

#2008 update helm chart for release v0.8.0
  hack/generate-install.sh
  manifests/charts/Chart.yaml
  manifests/charts/crds/serving.kserve.io_clusterservingruntimes.yaml
  manifests/charts/crds/serving.kserve.io_inferenceservices.yaml
  manifests/charts/crds/serving.kserve.io_predictor.yaml
  manifests/charts/crds/serving.kserve.io_servingruntime.yaml
  manifests/charts/templates/clusterrole.yaml
  manifests/charts/templates/clusterrolebinding.yaml
  manifests/charts/templates/clusterservingruntimes.yaml
  manifests/charts/templates/configmap.yaml
  manifests/charts/templates/role.yaml
  manifests/charts/templates/rolebinding.yaml
  manifests/charts/templates/servingruntimes.yaml
  manifests/charts/values.yaml
Labels: lgtm, approved

#2040 Fix canary rollout falling back to prev rolledout version
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  test/e2e/predictor/test_lightgbm.py
Labels: approved

#2034 add mlflow support
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/constants/constants.go
  test/e2e/data/mlflow_input_v2.json
  test/e2e/predictor/test_lightgbm.py
  test/e2e/predictor/test_mlflow.py
Labels: lgtm, approved

#2044 restore predictor images in isvc configmap
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  install/v0.8.0/kserve.yaml
Labels: lgtm, approved

#2043 TorchServe Kserve v2 bert explain
  docs/samples/v1beta1/torchserve/v2/bert/README.md
  docs/samples/v1beta1/torchserve/v2/bert/sequence_classification/Transformer_kserve_handler.py
  docs/samples/v1beta1/torchserve/v2/bert/sequence_classification/bytes/bert_v2.json
Labels: lgtm, approved, needs-ok-to-test

#2050 kserve kubeflow yaml issue fix
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  install/v0.8.0/kserve_kubeflow.yaml
Labels: lgtm, approved

#2049 Add ingress class name configuration
  config/configmap/inferenceservice.yaml
  config/overlays/test/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/transformer/test_raw_transformer.py
  test/scripts/run-e2e-tests.sh
Labels: lgtm, approved, ok-to-test

#2053 Add rbac for servingruntimes in kubeflow overlay
  config/overlays/kubeflow/cluster-role.yaml
Labels: lgtm, approved

#2062 mod: Upgrade to ginkgo v2
  go.mod
  go.sum
  pkg/agent/agent_suite_test.go
  pkg/agent/watcher_test.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/controller/v1alpha1/trainedmodel/controller_test.go
  pkg/controller/v1alpha1/trainedmodel/suite_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
Labels: lgtm, approved, ok-to-test

#2064 Cherrypick: Add rbac for servingruntimes in kubeflow overlay (#2053)
  config/overlays/kubeflow/cluster-role.yaml
Labels: lgtm, approved
