Repository kserve/kserve, pull requests merged in 2022-03, with the labels that each got.

#2071 runtimes installation issue fix
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.8.0/kserve-runtimes.yaml
  install/v0.8.0/kserve.yaml
Labels: lgtm, approved

#2073 cherry-pick: runtimes installation issue fix (#2071)
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.8.0/kserve-runtimes.yaml
  install/v0.8.0/kserve.yaml
Labels: approved

#2076 chore: fix the required K8s version comments
  config/default/cainjection_conversion_webhook.yaml
  config/default/inferenceservice_conversion_webhook.yaml
Labels: lgtm, approved, ok-to-test

#2074 fix: replace image tag
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
Labels: lgtm, approved, ok-to-test

#2092 upgrade alibi version to 0.6.4
  python/alibiexplainer/setup.py
Labels: lgtm, approved

#2091 Fix triton + torchscript guidelines to be executable
  docs/samples/v1beta1/triton/torchscript/README.md
  docs/samples/v1beta1/triton/torchscript/image.json
Labels: lgtm, approved, needs-ok-to-test

#2103 Upgrade kserve python dep
  python/kserve/requirements.txt
  python/lgbserver/setup.py
  test/e2e/common/utils.py
Labels: lgtm, approved

#2072 fix: configmap url in sklearn example
  docs/samples/v1beta1/sklearn/v1/README.md
Labels: lgtm, approved, needs-ok-to-test

#2084 feat: Add ModelMesh related status fields to isvc
  config/crd/serving.kserve.io_inferenceservices.yaml
  go.mod
  go.sum
  hack/violation_exceptions.list
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2112 allow more fields in servingruntime container spec
  Makefile
  config/crd/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/serving.kserve.io_servingruntimes.yaml
  pkg/apis/serving/v1alpha1/servingruntime_types.go
  pkg/apis/serving/v1alpha1/servingruntime_types_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/predictor_model_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2121 Fix status RestURL type
  hack/violation_exceptions.list
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2110 Move ComponentExtensionSpec validation to own test file
  pkg/apis/serving/v1beta1/component_test.go
  pkg/apis/serving/v1beta1/explainer_alibi_test.go
  pkg/apis/serving/v1beta1/explainer_custom_test.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_paddle_test.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_sklearn_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/predictor_xgboost_test.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
Labels: lgtm, approved
