Repository kserve/kserve, pull requests merged in 2023-03, with the labels that each got.

#2718 Use fork for multiprocessing mode
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/rest/server.py
Labels: approved, release-0.10

#2726 Fix knative installation failure in e2e test
  .github/workflows/e2e-test.yml
  python/kserve/setup.py
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm, approved

#2724 Update OWNERS
  OWNERS
Labels: approved

#2711 Adding podaffinity and resourcerequirments to IG Spec
  config/crd/serving.kserve.io_inferencegraphs.yaml
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller_test.go
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
  pkg/controller/v1alpha1/inferencegraph/suite_test.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved, release-0.10

#2466 Feat: adds huggingface bloom example to torchserve
  docs/samples/v1beta1/torchserve/v1/bloom/README.md
  docs/samples/v1beta1/torchserve/v1/bloom/bloom-560m.yaml
  docs/samples/v1beta1/torchserve/v1/bloom/config.properties
  docs/samples/v1beta1/torchserve/v1/bloom/pvc-pod.yml
  docs/samples/v1beta1/torchserve/v1/bloom/sample_text.txt
  docs/samples/v1beta1/torchserve/v1/bloom/storageclass.yaml
Labels: lgtm, approved

#2735 Upgrading cherry pick action to v1.0.9
  .github/workflows/cherry-pick.yml
Labels: lgtm, approved, release-0.10

#2736 Creating new manifests for v0.10.1
  charts/kserve-crd/Chart.yaml
  charts/kserve-crd/templates/serving.kserve.io_inferencegraphs.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.10.1/kserve-runtimes.yaml
  install/v0.10.1/kserve.yaml
  install/v0.10.1/kserve_kubeflow.yaml
  python/VERSION
Labels: lgtm, approved, release-0.10

#2739 Cherry-pick: Creating new manifests for v0.10.1 (#2736)
  charts/kserve-crd/Chart.yaml
  charts/kserve-crd/templates/serving.kserve.io_inferencegraphs.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.10.1/kserve-runtimes.yaml
  install/v0.10.1/kserve.yaml
  install/v0.10.1/kserve_kubeflow.yaml
  python/VERSION
Labels: lgtm, approved

#2700 Make storage dependency as an optional dependency
  .github/workflows/python-test.yml
  python/alibiexplainer.Dockerfile
  python/alibiexplainer/alibiexplainer/__main__.py
  python/alibiexplainer/setup.py
  python/alibiexplainer/tests/test_anchor_images.py
  python/alibiexplainer/tests/test_anchor_tabular.py
  python/kserve/README.md
  python/kserve/kserve/__init__.py
  python/kserve/kserve/storage/__init__.py
  python/kserve/kserve/storage/requirements.txt
  python/kserve/kserve/storage/storage.py
  python/kserve/kserve/storage/test/test_azure_storage.py
  python/kserve/kserve/storage/test/test_s3_storage.py
  python/kserve/kserve/storage/test/test_storage.py
  python/kserve/requirements.txt
  python/kserve/setup.py
  python/lgb.Dockerfile
  python/lgbserver/lgbserver/model.py
  python/lgbserver/setup.py
  python/paddle.Dockerfile
  python/paddleserver/paddleserver/model.py
  python/paddleserver/setup.py
  python/pmml.Dockerfile
  python/pmmlserver/pmmlserver/model.py
  python/pmmlserver/setup.py
  python/sklearn.Dockerfile
  python/sklearnserver/setup.py
  python/sklearnserver/sklearnserver/model.py
  python/storage-initializer.Dockerfile
  python/storage-initializer/scripts/initializer-entrypoint
  python/xgb.Dockerfile
  python/xgbserver/setup.py
  python/xgbserver/xgbserver/model.py
Labels: lgtm, approved

#2754 adjust order of types to default to float,int
  python/kserve/kserve/protocol/rest/v2_datamodels.py
Labels: lgtm, approved

#2752 Iter8 canary and performance testing samples
  docs/samples/canary-testing/.gitignore
  docs/samples/canary-testing/README.md
  docs/samples/canary-testing/canary.png
  docs/samples/canary-testing/report.png
  docs/samples/performance-testing/.gitignore
  docs/samples/performance-testing/README.md
  docs/samples/performance-testing/grpc-report.png
  docs/samples/performance-testing/grpc.md
  docs/samples/performance-testing/grpc.png
  docs/samples/performance-testing/http-report.png
  docs/samples/performance-testing/http.png
Labels: lgtm, approved

#2765 Fix running out of disk space in e2e
  python/custom_transformer/requirements.txt
Labels: lgtm, approved

#2774 fix trained model ready status
  docs/samples/multimodelserving/triton/README.md
  pkg/apis/serving/v1alpha1/trained_model_status.go
  pkg/controller/v1alpha1/trainedmodel/controller.go
Labels: lgtm, approved

#2772 fix missing ingress config options in helm chart
  charts/kserve-resources/templates/configmap.yaml
  charts/kserve-resources/values.yaml
Labels: lgtm, approved

#2738 Support Direct VolumeMount for PVC
  config/configmap/inferenceservice.yaml
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: lgtm, approved

#2697 Updating Knative Serving and Istio to their latest version
  hack/quick_install.sh
Labels: lgtm, approved

#2777 model_server.py: fix documentation for enable_latency_logging
  python/kserve/kserve/model_server.py
Labels: lgtm, approved
