Repository kserve/kserve, pull requests merged in 2023-04, with the labels that each got.

#2321 Allow multiple containers in ServingRuntime
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
Labels: lgtm, approved

#2783 Fix formatting and controller tests
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/path.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/path_test.go
Labels: approved

#2666 Parametrized docker builds
  Makefile
  python/aiffairness.Dockerfile
  python/aixexplainer.Dockerfile
  python/alibiexplainer.Dockerfile
  python/artexplainer.Dockerfile
  python/custom_model.Dockerfile
  python/custom_model_grpc.Dockerfile
  python/custom_transformer.Dockerfile
  python/custom_transformer_grpc.Dockerfile
  python/lgb.Dockerfile
  python/paddle.Dockerfile
  python/pmml.Dockerfile
  python/sklearn.Dockerfile
  python/storage-initializer.Dockerfile
  python/xgb.Dockerfile
Labels: lgtm, approved

#2655 Implement v2/open inference endpoints for OOTB python model servers
  .github/workflows/e2e-test.yml
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/kserve/protocol/rest/server.py
  python/kserve/kserve/utils/utils.py
  python/kserve/requirements.txt
  python/kserve/test/test_server.py
  python/lgbserver/lgbserver/example_model/model/model.bst
  python/lgbserver/lgbserver/model.py
  python/lgbserver/lgbserver/test_model.py
  python/paddleserver/paddleserver/model.py
  python/pmmlserver/pmmlserver/model.py
  python/pmmlserver/pmmlserver/test_model.py
  python/sklearnserver/sklearnserver/model.py
  python/xgbserver/xgbserver/model.py
  test/e2e/batcher/test_raw_batcher.py
  test/e2e/data/iris_input_v2_grpc.json
  test/e2e/data/jay-v2-grpc.json
  test/e2e/data/jay-v2.json
  test/e2e/data/pmml-input-v2.json
  test/e2e/helm/test_model_mesh_sklearn.py
  test/e2e/logger/test_raw_logger.py
  test/e2e/predictor/test_autoscaling.py
  test/e2e/predictor/test_canary.py
  test/e2e/predictor/test_lightgbm.py
  test/e2e/predictor/test_multi_model_serving.py
  test/e2e/predictor/test_paddle.py
  test/e2e/predictor/test_pmml.py
  test/e2e/predictor/test_pytorch.py
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_tensorflow.py
  test/e2e/predictor/test_torchserve.py
  test/e2e/predictor/test_triton.py
  test/e2e/predictor/test_xgboost.py
  test/e2e/pytest.ini
Labels: lgtm, approved

#2787 Fix Cifar10 drift detection example's InferenceService
  docs/samples/drift-detection/alibi-detect/cifar10/cifar10_drift.ipynb
Labels: lgtm, approved

#2792 Update tutorial of inference logging with Knative Eventing
  docs/samples/logger/knative-eventing/README.md
Labels: lgtm, approved

#2791 Fix minimum k8s version in quick install
  hack/quick_install.sh
Labels: lgtm, approved

#2794 Handle file exist scenario for local storage
  python/kserve/kserve/storage/storage.py
Labels: lgtm, approved

#2508 Remove "default" suffix from generated component name - updated
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/explainer_aix360.go
  pkg/apis/serving/v1beta1/explainer_aix360_test.go
  pkg/apis/serving/v1beta1/explainer_alibi.go
  pkg/apis/serving/v1beta1/explainer_alibi_test.go
  pkg/apis/serving/v1beta1/explainer_art.go
  pkg/apis/serving/v1beta1/explainer_art_test.go
  pkg/apis/serving/v1beta1/explainer_custom.go
  pkg/apis/serving/v1beta1/explainer_custom_test.go
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_lightgbm.go
  pkg/apis/serving/v1beta1/predictor_model.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_paddle.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_sklearn.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_triton.go
  pkg/apis/serving/v1beta1/predictor_xgboost.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
Labels: lgtm, approved

#2773 Add disable ingress feature for raw deployment
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
Labels: lgtm, approved

#2797 pass parameter in rest v2 infer
  python/kserve/kserve/protocol/rest/v2_endpoints.py
Labels: lgtm, approved

#2789 Support mixed input type for kserve python runtimes
  python/kserve/kserve/protocol/infer_type.py
  python/kserve/kserve/protocol/rest/v2_endpoints.py
  python/kserve/kserve/utils/utils.py
  python/kserve/test/test_server.py
  python/lgbserver/lgbserver/model.py
  python/lgbserver/lgbserver/test_model.py
  python/paddleserver/paddleserver/model.py
  python/pmmlserver/pmmlserver/model.py
  python/pmmlserver/pmmlserver/test_model.py
  python/sklearnserver/sklearnserver/example_models/joblib/model/model.joblib
  python/sklearnserver/sklearnserver/example_models/pickle/model/model.pickle
  python/sklearnserver/sklearnserver/example_models/pkl/model/model.pkl
  python/sklearnserver/sklearnserver/model.py
  python/sklearnserver/sklearnserver/test_model.py
  python/xgbserver/xgbserver/model.py
  test/e2e/common/utils.py
  test/e2e/data/jay-v2.json
  test/e2e/data/pmml-input-v2.json
  test/e2e/data/pmml_input_v2_grpc.json
  test/e2e/data/sklearn_mixed.json
  test/e2e/data/sklearn_mixed_v2.json
  test/e2e/predictor/test_autoscaling.py
  test/e2e/predictor/test_lightgbm.py
  test/e2e/predictor/test_pmml.py
  test/e2e/predictor/test_sklearn.py
  test/e2e/predictor/test_xgboost.py
Labels: lgtm, approved, kserve/sdk

#2627 Make deployment scheduling behaviour configurable
  charts/kserve-resources/templates/deployment.yaml
  charts/kserve-resources/values.yaml
Labels: lgtm, approved

#2824 Point S3 example README.md to KServe website
  docs/samples/storage/s3/README.md
Labels: approved

#2811 fix(samples): Update AIX examples to use custom explainer spec
  docs/samples/explanation/aix/Fetch_20newsgroups/aix-explainer.yaml
  docs/samples/explanation/aix/mnist/aix-explainer.yaml
Labels: lgtm, approved

#2559 Adding doc for release process v2
  release/RELEASE_PROCESS.md
  release/RELEASE_PROCESS_v2.md
Labels: lgtm, approved

#2815 Loosen tritonclient and azure storage blob dependencies
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_transformer/poetry.lock
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/xgbserver/poetry.lock
Labels: lgtm, approved

#2836 Add Triton FasterTransformer example
  docs/samples/v1beta1/triton/fastertransformer/README.md
  docs/samples/v1beta1/triton/fastertransformer/transformer/Dockerfile
  docs/samples/v1beta1/triton/fastertransformer/transformer/requirements.txt
  docs/samples/v1beta1/triton/fastertransformer/transformer/transformer.py
Labels: lgtm, approved

#2819 Add KServe Fluid example on LLMs
  docs/samples/README.md
  docs/samples/fluid/README.md
  docs/samples/fluid/alluxio.yaml
  docs/samples/fluid/dataload.yaml
  docs/samples/fluid/docker/Dockerfile
  docs/samples/fluid/docker/models.py
  docs/samples/fluid/docker/requirements.txt
  docs/samples/fluid/download_model.py
  docs/samples/fluid/fluid-isvc.yaml
  docs/samples/fluid/jindo.yaml
  docs/samples/fluid/kserve-isvc.yaml
  docs/samples/fluid/s3creds.yaml
Labels: lgtm, approved

#2841 Upgrade kustomization.yaml to support kustomize 5.0
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/configmap/kustomization.yaml
  config/crd/kustomization.yaml
  config/default/isvc_mutatingwebhook_cainjection_patch.yaml
  config/default/isvc_validatingwebhook_cainjection_patch.yaml
  config/default/kustomization.yaml
  config/default/params.yaml
  config/default/trainedmodel_mutatingwebhook_cainjection_patch.yaml
  config/default/trainedmodel_validatingwebhook_cainjection_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/overlays/dev-image-config/kustomization.yaml
  config/overlays/development/kustomization.yaml
  config/overlays/kubeflow/kustomization.yaml
  config/overlays/test/kustomization.yaml
  config/overlays/test/runtimes/kustomization.yaml
  config/rbac/kustomization.yaml
  config/runtimes/kustomization.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  test/overlays/istio/istio_ingressgateway_patch.yaml
  test/overlays/istio/istiod_deployment_patch.yaml
  test/overlays/istio/kustomization.yaml
  test/overlays/knative/activator_deployment_patch.yaml
  test/overlays/knative/autoscaler_deployment_patch.yaml
  test/overlays/knative/controller_deployment_patch.yaml
  test/overlays/knative/domain_mapping_deployment_patch.yaml
  test/overlays/knative/domainmapping_webhook_patch.yaml
  test/overlays/knative/kustomization.yaml
  test/overlays/knative/net_istio_controller_deployment_patch.yaml
  test/overlays/knative/net_istio_webhook_patch.yaml
  test/overlays/knative/requests_patch.yaml
  test/overlays/knative/webhook_deployment_patch.yaml
Labels: lgtm, approved

#2839 Add RBAC for inferencegraphs/finalizers
  charts/kserve-resources/templates/clusterrole.yaml
  config/rbac/role.yaml
Labels: lgtm, approved

#2704 Extract modelmesh part in helm chart
  charts/kserve-resources/templates/certificate.yaml
  charts/kserve-resources/templates/clusterrole.yaml
  charts/kserve-resources/templates/clusterrolebinding.yaml
  charts/kserve-resources/templates/clusterservingruntimes.yaml
  charts/kserve-resources/templates/configmap.yaml
  charts/kserve-resources/templates/deployment.yaml
  charts/kserve-resources/templates/modelmesh/clusterrole.yaml
  charts/kserve-resources/templates/modelmesh/clusterrolebinding.yaml
  charts/kserve-resources/templates/modelmesh/clusterservingruntimes.yaml
  charts/kserve-resources/templates/modelmesh/configmap.yaml
  charts/kserve-resources/templates/modelmesh/deployment.yaml
  charts/kserve-resources/templates/modelmesh/networkpolicy.yaml
  charts/kserve-resources/templates/modelmesh/role.yaml
  charts/kserve-resources/templates/modelmesh/rolebinding.yaml
  charts/kserve-resources/templates/modelmesh/serviceaccount.yaml
  charts/kserve-resources/templates/role.yaml
  charts/kserve-resources/templates/rolebinding.yaml
  charts/kserve-resources/templates/service.yaml
  charts/kserve-resources/templates/serviceaccount.yaml
  charts/kserve-resources/templates/webhookconfiguration.yaml
  charts/kserve-resources/values.yaml
Labels: lgtm, approved

#2845 chown python virtual env path to runtime user
  python/aiffairness.Dockerfile
  python/aixexplainer.Dockerfile
  python/alibiexplainer.Dockerfile
  python/artexplainer.Dockerfile
  python/custom_model.Dockerfile
  python/custom_model_grpc.Dockerfile
  python/custom_transformer.Dockerfile
  python/custom_transformer_grpc.Dockerfile
  python/lgb.Dockerfile
  python/paddle.Dockerfile
  python/pmml.Dockerfile
  python/sklearn.Dockerfile
  python/storage-initializer.Dockerfile
  python/xgb.Dockerfile
Labels: lgtm, approved

#2858 Fix inferencegraphs/finalizers rbac
  pkg/controller/v1alpha1/inferencegraph/controller.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2848 Use buildkit for building docker images
  .github/workflows/agent-docker-publish.yml
  .github/workflows/alibiexplainer-docker-publish.yml
  .github/workflows/artexplainer-docker-publish.yml
  .github/workflows/custom-model-grpc-publish.yml
  .github/workflows/kserve-controller-docker-publish.yml
  .github/workflows/lightgbm-docker-publish.yml
  .github/workflows/paddle-docker-publish.yml
  .github/workflows/pmml-docker-publish.yml
  .github/workflows/qpext-docker-publish.yml
  .github/workflows/router-docker-publish.yml
  .github/workflows/sklearnserver-docker-publish.yml
  .github/workflows/storage-initializer-docker-publisher.yml
  .github/workflows/tf2openapi-docker-publisher.yml
  .github/workflows/transformer-docker-publish.yml
  .github/workflows/xgbserver-docker-publisher.yml
  Makefile
  test/scripts/gh-actions/build-images.sh
  test/scripts/gh-actions/build-qpext-image.sh
  test/scripts/gh-actions/build-server-runtimes.sh
Labels: lgtm, approved

#2835 Add support for k8s 1.26
  .github/actions/minikube-setup/action.yml
  .github/workflows/e2e-test.yml
  Makefile
  hack/python-sdk/update_release_version.sh
  hack/python-sdk/update_release_version_helper.py
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_transformer/poetry.lock
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/xgbserver/poetry.lock
  test/e2e/qpext/test_qpext.py
  test/scripts/gh-actions/run-e2e-tests.sh
  test/scripts/gh-actions/run-qpext-test.sh
  test/scripts/gh-actions/setup-deps.sh
  test/scripts/gh-actions/setup-kserve.sh
Labels: lgtm, approved

#2860 Bump the Go version for the builder image
  Dockerfile
  agent.Dockerfile
  docs/samples/graph/bgtest/Dockerfile
  qpext/qpext.Dockerfile
  router.Dockerfile
Labels: lgtm, approved

#2864 Point KServe example readme to website
  docs/samples/README.md
Labels: approved
