Repository kserve/kserve, pull requests merged in 2023-11, with the labels that each got.

#3213 chore: Add new PR reviewers and approvers
  OWNERS
Labels: lgtm, approved, kind/process

#3204 Added async with postprocess method.
  docs/samples/kafka/image_transformer/image_transformer.py
  python/kserve/kserve/model.py
Labels: lgtm, approved

#3184 Remove the redundant python lint check in CI environment
  .github/workflows/python-test.yml
Labels: lgtm, approved

#3182 Move pmml worker validation to runtime
  .github/workflows/e2e-test.yml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  python/kserve/kserve/errors.py
  python/pmmlserver/pmmlserver/__main__.py
  test/e2e/predictor/test_autoscaling.py
  test/e2e/predictor/test_triton.py
  test/scripts/gh-actions/status-check.sh
Labels: lgtm, approved

#3217 Bump torchserve version to 0.9.0
  charts/kserve-resources/values.yaml
  config/runtimes/kustomization.yaml
Labels: lgtm, approved

#3203 CVE-2023-44487 - qpext
  qpext/go.mod
  qpext/go.sum
Labels: lgtm, approved

#3075 Allow ray >=2.7,<3
  .github/workflows/python-test.yml
  Makefile
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/alibiexplainer/pyproject.toml
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_transformer/poetry.lock
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/xgbserver/poetry.lock
Labels: lgtm, approved

#3226 Fix lightgbm model input conversion when input is list of lists
  python/kserve/kserve/utils/utils.py
  python/lgbserver/lgbserver/test_model.py
  test/e2e/data/iris_input_v4.json
  test/e2e/predictor/test_lightgbm.py
Labels: lgtm, approved, cherrypicked

#3229 [release-0.11] Fix lightgbm model input conversion when input is list of lists
  .github/workflows/python-test.yml
  python/kserve/kserve/utils/utils.py
  python/lgbserver/lgbserver/test_model.py
  test/e2e/data/iris_input_v4.json
  test/e2e/predictor/test_lightgbm.py
Labels: lgtm, approved

#3232 [release-0.11]Fix runtime not found for triton due to wrong default protocolVersion
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  test/e2e/predictor/test_triton.py
Labels: lgtm, approved, cherrypicked

#3233 [release-0.11]Fix mlserver runtime priority for sklearn
  charts/kserve-resources/templates/clusterservingruntimes.yaml
  config/runtimes/kserve-mlserver.yaml
Labels: lgtm, approved

#3242 [release-0.11] Cherry-picks related to CVE-2023-44487
  go.mod
  go.sum
  qpext/go.mod
  qpext/go.sum
Labels: lgtm, approved

#3202 CVE-2023-44487
  agent.Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved

#3244 Version bump to 0.11.2
  charts/kserve-crd/Chart.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.11.2/kserve-runtimes.yaml
  install/v0.11.2/kserve.yaml
  install/v0.11.2/kserve_kubeflow.yaml
  python/VERSION
  python/aiffairness/poetry.lock
  python/aiffairness/pyproject.toml
  python/alibiexplainer/poetry.lock
  python/alibiexplainer/pyproject.toml
  python/artexplainer/poetry.lock
  python/artexplainer/pyproject.toml
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/lgbserver/pyproject.toml
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/sklearnserver/pyproject.toml
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/error_404_isvc/pyproject.toml
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/pyproject.toml
  python/xgbserver/poetry.lock
  python/xgbserver/pyproject.toml
Labels: lgtm, approved

#3245 Sanitize a command line argument in agent
  cmd/agent/main.go
Labels: lgtm, approved

#3249 [WIP] Merge master into CA bundle collaboration branch
  .github/workflows/e2e-test.yml
  .github/workflows/python-test.yml
  Makefile
  OWNERS
  agent.Dockerfile
  charts/kserve-resources/values.yaml
  cmd/agent/main.go
  config/runtimes/kustomization.yaml
  docs/samples/kafka/image_transformer/image_transformer.py
  go.mod
  go.sum
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/alibiexplainer/pyproject.toml
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_transformer/poetry.lock
  python/kserve/kserve/errors.py
  python/kserve/kserve/model.py
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/kserve/utils/utils.py
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/lgbserver/test_model.py
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/pmmlserver/__main__.py
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/xgbserver/poetry.lock
  qpext/go.mod
  qpext/go.sum
  test/e2e/data/iris_input_v4.json
  test/e2e/predictor/test_autoscaling.py
  test/e2e/predictor/test_lightgbm.py
  test/e2e/predictor/test_triton.py
  test/scripts/gh-actions/status-check.sh
Labels: do-not-merge/work-in-progress

#3253 Pin version of python to 3.11
  .github/workflows/python-publish.yml
Labels: lgtm, approved

#3181 Validation added for ensuring same model format has same priority for runtime
  charts/kserve-resources/templates/clusterservingruntimes.yaml
  config/runtimes/kserve-mlserver.yaml
  pkg/webhook/admission/servingruntime/servingruntime_webhook.go
  pkg/webhook/admission/servingruntime/servingruntime_webhook_test.go
Labels: lgtm, approved

#3079 Fix: Unexpected Panic in Inference graph when it fails to create http request
  cmd/router/main.go
  cmd/router/main_test.go
Labels: lgtm, approved

#3219 Add default clusterstoragecontainer cr into resources
  Makefile
  config/clusterresources/kustomization.yaml
  config/overlays/test/clusterresources/kustomization.yaml
  config/storagecontainers/configuration.yaml
  config/storagecontainers/default.yaml
  config/storagecontainers/kustomization.yaml
  docs/OPENSHIFT_GUIDE.md
  hack/generate-install.sh
  hack/quick_install.sh
  test/scripts/aws/run-e2e-tests.sh
  test/scripts/gh-actions/update-test-overlays.sh
Labels: lgtm, approved

#3267 Support verify variable with storage-config json style (fix-3263)
  python/kserve/kserve/storage/storage.py
Labels: lgtm, approved

#3266 Update qpext docs on image patch
  qpext/README.md
Labels: lgtm, approved

#3246 Added 3.11 support for paddle in workflow.
  .github/workflows/python-test.yml
Labels: lgtm, approved
