Repository kserve/kserve, pull requests merged in 2023-06, with the labels that each got.

#2933 Python 3.11 support
  .github/workflows/python-test.yml
  python/aiffairness/poetry.lock
  python/aiffairness/pyproject.toml
  python/alibiexplainer/poetry.lock
  python/artexplainer/poetry.lock
  python/artexplainer/pyproject.toml
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/lgbserver/pyproject.toml
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/sklearnserver/pyproject.toml
  python/xgbserver/poetry.lock
  python/xgbserver/pyproject.toml
Labels: lgtm, approved

#2966 Update alibi explainer storage uri
  docs/samples/explanation/alibi/cifar10/README.md
  docs/samples/explanation/alibi/cifar10/cifar10.yaml
  docs/samples/explanation/alibi/cifar10/requirements.txt
  docs/samples/explanation/alibi/income/README.md
  docs/samples/explanation/alibi/income/income.yaml
  docs/samples/explanation/alibi/income/requirements.txt
  docs/samples/explanation/alibi/moviesentiment/README.md
Labels: lgtm, approved

#2956 Updated storageUri for paddle example and e2e test.
  docs/samples/v1beta1/paddle/paddle.yaml
  test/e2e/predictor/test_paddle.py
Labels: lgtm, approved

#2929 Decode avro cloud event
  docs/samples/kafka/image_transformer/image_transformer.py
  docs/samples/v1beta1/transformer/feast/driver_transformer/driver_transformer/driver_transformer.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/bert_transformer.py
  python/kserve/kserve/model.py
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/test/test_server.py
Labels: lgtm, approved

#2968 Fix incorrect log message in transformer reconciliation
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
Labels: lgtm, approved

#2916 Reconcile when rollout duration is changed
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
Labels: lgtm, approved

#2925 Support setting labels and annotations on the component level
  config/crd/serving.kserve.io_inferenceservices.yaml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2924 Load Kubeconfig from python dict
  python/kserve/kserve/api/kserve_client.py
  python/kserve/test/test_kubeconfig_dict.py
Labels: lgtm, approved, kserve/sdk

#2991 Fix kourier e2e test
  .github/workflows/e2e-test.yml
Labels: lgtm, approved

#2977 fix IngressReady condition
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Labels: lgtm, approved

#2972 chore: Free up disk space on E2E test GHA runner node
  .github/actions/minikube-setup/action.yml
  .github/workflows/e2e-test.yml
  test/e2e/predictor/test_triton.py
Labels: lgtm, approved, area/testing

#2998 Fix e2e workflow syntax typo that broke e2e tests
  .github/workflows/e2e-test.yml
Labels: lgtm, approved

#3000 Use standard socket for single process
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/rest/server.py
Labels: lgtm, approved

#2980 Bump torchserve version to 0.8.0
  charts/kserve-resources/values.yaml
  config/runtimes/kustomization.yaml
Labels: lgtm, approved

#3005 Fix params while loading kube config from dict
  python/kserve/kserve/api/kserve_client.py
Labels: lgtm, approved

#2999 Fix 0.10.1 cherry-pick merge issue
  .github/actions/minikube-setup/action.yml
  .github/workflows/e2e-test.yml
  .github/workflows/python-test.yml
  charts/kserve-crd/Chart.yaml
  charts/kserve-resources/values.yaml
  python/VERSION
  python/custom_model.Dockerfile
  python/custom_model/requirements.txt
  python/custom_model_grpc.Dockerfile
  python/custom_transformer.Dockerfile
  python/custom_transformer/requirements.txt
  python/custom_transformer_grpc.Dockerfile
  python/kserve/kserve/model.py
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/rest/server.py
  test/scripts/gh-actions/build-server-runtimes.sh
Labels: lgtm, approved

#3006 Add python 3.11 support for alibi explainer
  .github/workflows/python-test.yml
  python/alibiexplainer/poetry.lock
  python/alibiexplainer/pyproject.toml
Labels: lgtm, approved

#3004 Enable Triton e2e test
  .github/workflows/e2e-test.yml
  python/custom_transformer/model.py
  test/e2e/data/cifar10_input_v2.json
  test/e2e/predictor/test_pytorch.py
  test/e2e/predictor/test_triton.py
Labels: lgtm, approved

#2992 Bump triton server version to 23.05-py3
  charts/kserve-resources/values.yaml
  config/runtimes/kustomization.yaml
Labels: lgtm, approved

#2969 Update ModelMesh version to v0.11.0-rc0
  charts/kserve-resources/templates/modelmesh/certificate.yaml
  charts/kserve-resources/templates/modelmesh/clusterrole.yaml
  charts/kserve-resources/templates/modelmesh/clusterservingruntimes.yaml
  charts/kserve-resources/templates/modelmesh/deployment.yaml
  charts/kserve-resources/templates/modelmesh/networkpolicy.yaml
  charts/kserve-resources/templates/modelmesh/service.yaml
  charts/kserve-resources/templates/modelmesh/webhookconfiguration.yaml
  charts/kserve-resources/values.yaml
  hack/install_kserve_mm.sh
  test/e2e/helm/test_model_mesh_sklearn.py
  test/scripts/gh-actions/setup-kserve-helm.sh
  test/scripts/gh-actions/setup-modelmesh-dep.sh
Labels: lgtm, approved

#3017 Fix a typo docs/samples/metrics-and-monitoring/README.md
  docs/samples/metrics-and-monitoring/README.md
Labels: lgtm, approved
