Repository kserve/kserve, pull requests merged in 2023-08, with the labels that each got.

#3059 release: Update defaultModelMeshVersion to v0.11.0
  charts/kserve-resources/values.yaml
Labels: lgtm, approved, release-0.11

#3064 chore: Rename ModelMesh validating webhook
  charts/kserve-resources/templates/modelmesh/webhookconfiguration.yaml
Labels: lgtm, approved

#3061 Release v0.11.0
  .gitignore
  charts/kserve-crd/Chart.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.11.0/kserve-runtimes.yaml
  install/v0.11.0/kserve.yaml
  install/v0.11.0/kserve_kubeflow.yaml
  python/VERSION
  python/aiffairness/pyproject.toml
  python/alibiexplainer/pyproject.toml
  python/artexplainer/pyproject.toml
  python/custom_model/pyproject.toml
  python/custom_transformer/pyproject.toml
  python/kserve/pyproject.toml
  python/lgbserver/pyproject.toml
  python/paddleserver/pyproject.toml
  python/pmmlserver/pyproject.toml
  python/sklearnserver/pyproject.toml
  python/xgbserver/pyproject.toml
Labels: lgtm, approved

#3066 Update poetry lock files
  hack/python-release.sh
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_transformer/poetry.lock
  python/kserve/poetry.lock
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/xgbserver/poetry.lock
Labels: approved

#3070 [docker] reduction in the number of layers for controller image
  Dockerfile
Labels: lgtm, approved

#3072 Update indirect dependency golang.org/x/net/html
  go.mod
  go.sum
  qpext/go.mod
  qpext/go.sum
Labels: lgtm, approved

#3083 Fix kubeflow overlay kustomization
  config/overlays/kubeflow/kustomization.yaml
  hack/generate-install.sh
  install/v0.11.0/kserve_kubeflow.yaml
Labels: lgtm, approved

#3089 Check sys platform before using SIGQUIT - fix windows development
  python/kserve/kserve/model_server.py
Labels: lgtm, approved

#2984 Use knative operator for installing knative in e2e tests
  .github/actions/kserve-dep-setup/action.yml
  .github/actions/minikube-setup/action.yml
  .github/workflows/e2e-test.yml
  test/e2e/predictor/test_triton.py
  test/overlays/knative/default/activator_deployment_patch.yaml
  test/overlays/knative/default/autoscaler_deployment_patch.yaml
  test/overlays/knative/default/controller_deployment_patch.yaml
  test/overlays/knative/default/domain_mapping_deployment_patch.yaml
  test/overlays/knative/default/domainmapping_webhook_patch.yaml
  test/overlays/knative/default/kustomization.yaml
  test/overlays/knative/default/webhook_deployment_patch.yaml
  test/overlays/knative/knative-serving-istio.yaml
  test/overlays/knative/knative-serving-kourier.yaml
  test/overlays/knative/overlays/istio/kustomization.yaml
  test/overlays/knative/overlays/istio/net_istio_controller_deployment_patch.yaml
  test/overlays/knative/overlays/istio/net_istio_webhook_patch.yaml
  test/overlays/knative/overlays/kourier/kustomization.yaml
  test/overlays/knative/overlays/kourier/net_kourier_controller_deployment_patch.yaml
  test/overlays/knative/overlays/kourier/net_kourier_gateway_deployment_patch.yaml
  test/scripts/gh-actions/install-knative-operator.sh
  test/scripts/gh-actions/setup-deps.sh
  test/scripts/gh-actions/setup-kourier.sh
  test/scripts/gh-actions/status-check.sh
Labels: lgtm, approved

#3077 Upgrade k8s to 1.27, istio 1.8 in test environment
  .github/actions/minikube-setup/action.yml
  test/scripts/gh-actions/setup-deps.sh
Labels: lgtm, approved

#3060 Introduce Storage container CRD
  charts/kserve-crd/templates/serving.kserve.io_clusterstoragecontainers.yaml
  charts/kserve-resources/templates/clusterrole.yaml
  charts/kserve-resources/templates/clusterstoragecontainer.yaml
  config/crd/kustomization.yaml
  config/crd/serving.kserve.io_clusterstoragecontainers.yaml
  config/rbac/role.yaml
  hack/generate-install.sh
  pkg/apis/serving/v1alpha1/storage_container_types.go
  pkg/apis/serving/v1alpha1/storage_container_types_test.go
  pkg/apis/serving/v1alpha1/v1alpha1.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/webhook/admission/pod/mutator.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  pkg/webhook/admission/pod/suite_test.go
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2963 List Models v2 REST API
  python/kserve/kserve/protocol/rest/server.py
  python/kserve/kserve/protocol/rest/v2_datamodels.py
  python/kserve/kserve/protocol/rest/v2_endpoints.py
  python/kserve/test/test_server.py
Labels: lgtm, approved
