Repository kserve/kserve, pull requests merged in 2023-05, with the labels that each got.

#2782 python: allow to override the UvicornServer's default log config
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/rest/server.py
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
Labels: lgtm, approved

#2855 Update the OpenShift guide to version 4.12 and use OpenShift Serverless
  docs/OPENSHIFT_GUIDE.md
  docs/openshift/cert-manager/operator.yaml
  docs/openshift/networkpolicies.yaml
  docs/openshift/serverless/gateways.yaml
  docs/openshift/serverless/knativeserving-istio.yaml
  docs/openshift/serverless/knativeserving-kourier.yaml
  docs/openshift/serverless/operator.yaml
  docs/openshift/service-mesh/namespace.yaml
  docs/openshift/service-mesh/operators.yaml
  docs/openshift/service-mesh/peer-authentication.yaml
  docs/openshift/service-mesh/smcp.yaml
  docs/openshift/service-mesh/smmr.yaml
Labels: lgtm, approved

#2869 Implement dynamic versioning using poetry plugin
  .github/workflows/e2e-test.yml
  .github/workflows/python-publish.yml
  .github/workflows/python-test.yml
  python/aiffairness.Dockerfile
  python/aiffairness/Makefile
  python/aiffairness/pyproject.toml
  python/aixexplainer.Dockerfile
  python/alibiexplainer.Dockerfile
  python/alibiexplainer/Makefile
  python/alibiexplainer/pyproject.toml
  python/artexplainer.Dockerfile
  python/artexplainer/Makefile
  python/artexplainer/pyproject.toml
  python/custom_model.Dockerfile
  python/custom_model/Makefile
  python/custom_model/pyproject.toml
  python/custom_model_grpc.Dockerfile
  python/custom_transformer.Dockerfile
  python/custom_transformer/Makefile
  python/custom_transformer/pyproject.toml
  python/custom_transformer_grpc.Dockerfile
  python/kserve/Makefile
  python/kserve/pyproject.toml
  python/lgb.Dockerfile
  python/lgbserver/Makefile
  python/lgbserver/pyproject.toml
  python/paddle.Dockerfile
  python/paddleserver/Makefile
  python/paddleserver/pyproject.toml
  python/plugin/poetry-version-plugin/LICENSE
  python/plugin/poetry-version-plugin/README.md
  python/plugin/poetry-version-plugin/debug.py
  python/plugin/poetry-version-plugin/mypy.ini
  python/plugin/poetry-version-plugin/poetry_version_plugin/__init__.py
  python/plugin/poetry-version-plugin/poetry_version_plugin/plugin.py
  python/plugin/poetry-version-plugin/pyproject.toml
  python/pmml.Dockerfile
  python/pmmlserver/Makefile
  python/pmmlserver/pyproject.toml
  python/sklearn.Dockerfile
  python/sklearnserver/Makefile
  python/sklearnserver/pyproject.toml
  python/storage-initializer.Dockerfile
  python/xgb.Dockerfile
  python/xgbserver/Makefile
  python/xgbserver/pyproject.toml
  test/scripts/gh-actions/setup-kserve-helm.sh
  test/scripts/gh-actions/setup-kserve.sh
Labels: lgtm, approved

#2877 add json mimetype header for IG response
  cmd/router/main.go
Labels: lgtm, approved

#2873 Add support for collocation of transformer and predictor
  docs/samples/v1beta1/transformer/collocation/README.md
  docs/samples/v1beta1/transformer/collocation/collocation.yaml
  docs/samples/v1beta1/transformer/collocation/input.json
  pkg/constants/constants.go
  pkg/webhook/admission/pod/agent_injector.go
  pkg/webhook/admission/pod/agent_injector_test.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: lgtm, approved

#2832 Added support for python 3.10 and removed python 3.7 references
  .github/workflows/python-test.yml
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/alibiexplainer/pyproject.toml
  python/alibiexplainer/tests/test_anchor_images.py
  python/alibiexplainer/tests/test_anchor_tabular.py
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_transformer/poetry.lock
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/xgbserver/poetry.lock
  test/e2e/explainer/test_tabular_explainer.py
Labels: lgtm, approved

#2892 Fix github workflow on release-0.10
  .github/workflows/python-test.yml
Labels: lgtm, approved

#2889 Cleanup aix explainer
  python/aiffairness/pyproject.toml
  python/aixexplainer.Dockerfile
  python/kserve/README.md
  python/kserve/docs/V1beta1AIXExplainerSpec.md
Labels: lgtm, approved

#2890 Break down the Serving and net-istio artifact downloads into their own release trains
  hack/quick_install.sh
Labels: lgtm, approved

#2886 Do not create GRPCServer when grpc is not enabled
  python/kserve/kserve/model_server.py
Labels: lgtm, approved

#2887 Storage Initializer: Support virtual path style in S3
  python/kserve/kserve/storage/storage.py
  python/kserve/kserve/storage/test/test_s3_storage.py
Labels: lgtm, approved

#2881 Move cloud event decode logic from preprocess to decode method
  python/aiffairness/poetry.lock
  python/alibiexplainer/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_transformer/poetry.lock
  python/kserve/kserve/model.py
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/kserve/protocol/infer_type.py
  python/kserve/kserve/protocol/rest/server.py
  python/kserve/kserve/utils/utils.py
  python/kserve/poetry.lock
  python/kserve/test/test_dataplane.py
  python/kserve/test/test_server.py
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/xgbserver/poetry.lock
Labels: lgtm, approved

#2524 Added support to accept the request body/payload in any format (not just json)
  python/kserve/kserve/protocol/dataplane.py
Labels: lgtm, approved

#2907 Update the data plane link
  docs/README.md
Labels: lgtm, approved

#2910 Upgrade mlserver version to 1.3.2
  charts/kserve-resources/values.yaml
  config/runtimes/kustomization.yaml
Labels: lgtm, approved

#2899 Poetry plugin should update pyproject.toml
  hack/python-release.sh
  python/plugin/poetry-version-plugin/poetry_version_plugin/plugin.py
  release/RELEASE_PROCESS_v2.md
Labels: lgtm, approved

#2911 Allow using SSL between transformer and predictor/explainer
  docs/samples/v1beta1/transformer/torchserve_image_transformer/README.md
  python/custom_transformer/model.py
  python/kserve/kserve/model.py
Labels: lgtm, approved

#2914 Go 1.20 upgrade
  .github/workflows/e2e-test.yml
  .github/workflows/go.yml
  Dockerfile
  agent.Dockerfile
  go.mod
  go.sum
  pkg/apis/serving/v1beta1/podspec.go
  qpext/go.mod
  qpext/go.sum
  qpext/qpext.Dockerfile
  router.Dockerfile
  tools/tf2openapi/Dockerfile
  tools/tf2openapi/cmd/e2e_test.go
  tools/tf2openapi/generator/generate_test.go
  tools/tf2openapi/generator/tensorflow_serving_protocol.go
  tools/tf2openapi/types/tfmetagraph_test.go
  tools/tf2openapi/types/tfsavedmodel_test.go
  tools/tf2openapi/types/tfsignaturedef.go
  tools/tf2openapi/types/tfsignaturedef_test.go
Labels: lgtm, approved

#2905 Add poetry lockfile consistency check to CI environment
  .github/workflows/e2e-test.yml
  .github/workflows/python-publish.yml
  .github/workflows/python-test.yml
  test/scripts/gh-actions/check-poetry-lockfile.sh
  test/scripts/gh-actions/setup-kserve-helm.sh
  test/scripts/gh-actions/setup-kserve.sh
  test/scripts/gh-actions/setup-poetry.sh
Labels: lgtm, approved

#2876 Make postprocess interface consistent with V2 protocol
  python/kserve/kserve/model.py
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/kserve/protocol/grpc/servicer.py
  python/kserve/kserve/protocol/infer_type.py
  python/kserve/kserve/protocol/rest/v1_endpoints.py
  python/kserve/kserve/protocol/rest/v2_endpoints.py
  python/kserve/test/test_dataplane.py
Labels: lgtm, approved

#2920 Update makefile
  Makefile
  hack/model_server_patch_dev.sh
  hack/serving_runtime_image_patch.sh
Labels: lgtm, approved

#2884 Add a KServe module level logger
  python/kserve/kserve/logging.py
  python/kserve/kserve/model.py
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/grpc/server.py
  python/kserve/kserve/protocol/rest/server.py
Labels: lgtm, approved, cherrypick-approved, cherrypicked, release-0.10

#2875 Make status.address.url consistent across installations
  pkg/apis/serving/v1beta1/predictor_custom.go
  pkg/apis/serving/v1beta1/predictor_custom_test.go
  pkg/apis/serving/v1beta1/predictor_lightgbm.go
  pkg/apis/serving/v1beta1/predictor_lightgbm_test.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime.go
  pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
  pkg/apis/serving/v1beta1/predictor_paddle.go
  pkg/apis/serving/v1beta1/predictor_paddle_test.go
  pkg/apis/serving/v1beta1/predictor_pmml.go
  pkg/apis/serving/v1beta1/predictor_pmml_test.go
  pkg/apis/serving/v1beta1/predictor_tfserving.go
  pkg/apis/serving/v1beta1/predictor_tfserving_test.go
  pkg/apis/serving/v1beta1/predictor_torchserve.go
  pkg/apis/serving/v1beta1/predictor_torchserve_test.go
  pkg/apis/serving/v1beta1/predictor_triton.go
  pkg/apis/serving/v1beta1/predictor_triton_test.go
  pkg/apis/serving/v1beta1/transformer_custom.go
  pkg/apis/serving/v1beta1/transformer_custom_test.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  test/e2e/graph/test_inference_graph.py
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/predictor/test_xgboost.py
Labels: lgtm, approved

#2896 Remove the watch for Pod UPDATE event in webhook to support fluid
  pkg/webhook/admission/pod/storage_initializer_injector.go
Labels: lgtm, approved

#2893 Created a new RC release version for version 0.11.0
  charts/kserve-crd/Chart.yaml
  charts/kserve-crd/templates/serving.kserve.io_inferenceservices.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.11.0-rc0/kserve-runtimes.yaml
  install/v0.11.0-rc0/kserve.yaml
  install/v0.11.0-rc0/kserve_kubeflow.yaml
  python/VERSION
  python/aiffairness/pyproject.toml
  python/alibiexplainer/pyproject.toml
  python/artexplainer/pyproject.toml
  python/custom_model/pyproject.toml
  python/custom_transformer/pyproject.toml
  python/kserve/pyproject.toml
  python/lgbserver/pyproject.toml
  python/paddleserver/pyproject.toml
  python/pmmlserver/pyproject.toml
  python/sklearnserver/pyproject.toml
  python/xgbserver/pyproject.toml
  release/RELEASE_PROCESS_v2.md
Labels: lgtm, approved

#2932 Replace unmaintained satori/go.uuid package
  go.mod
  go.sum
  pkg/batcher/handler.go
Labels: lgtm, approved

#2940 Cherry-pick: Add a KServe module level logger (#2884)
  python/kserve/kserve/errors.py
  python/kserve/kserve/logging.py
  python/kserve/kserve/model.py
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/grpc/server.py
  python/kserve/kserve/protocol/rest/server.py
Labels: lgtm, approved

#2939 Log exception stack for python runtimes
  python/kserve/kserve/errors.py
Labels: approved

#2912 Upgrade controller gen version to 0.12.0
  Makefile
  config/crd/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/serving.kserve.io_inferencegraphs.yaml
  config/crd/serving.kserve.io_inferenceservices.yaml
  config/crd/serving.kserve.io_servingruntimes.yaml
  config/crd/serving.kserve.io_trainedmodels.yaml
  config/rbac/role.yaml
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#2917 Checked model readiness before attempting inference.
  python/alibiexplainer/alibiexplainer/explainer.py
  python/kserve/kserve/protocol/rest/v1_endpoints.py
  python/kserve/kserve/protocol/rest/v2_endpoints.py
  python/kserve/test/test_server.py
Labels: lgtm, approved
