Repository kserve/kserve, pull requests merged in 2023-02, with the labels that each got.

#2673 Loosen protobuf and numpy dependency
  python/kserve/kserve/api/watch.py
  python/kserve/requirements.txt
Labels: lgtm, approved

#2609 Update quick install script to add Cluster Autoscaler and istiod memory leakage fix fields
  hack/quick_install.sh
Labels: lgtm, approved

#2357 Feature kandrio path based
  .github/workflows/e2e-test.yml
  cmd/manager/main.go
  config/overlays/test/configmap/inferenceservice-ingress.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/path.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/path_test.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  test/e2e/common/utils.py
Labels: lgtm, approved

#2684 Cherry-pick: Loosen protobuf and numpy dependency (#2673)
  python/kserve/kserve/api/watch.py
  python/kserve/requirements.txt
Labels: lgtm, approved, cherrypick-approved, cherrypicked

#2687 Fixing the dockerfile to run as non-root user
  agent.Dockerfile
  router.Dockerfile
  tools/tf2openapi/Dockerfile
Labels: lgtm, approved

#2679 Allowing setting minReplicas for IG router.
  cmd/router/main.go
  cmd/router/main_test.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
Labels: lgtm, approved

#2702 disable modelmesh helm e2e test
  test/e2e/helm/test_model_mesh_sklearn.py
Labels: lgtm, approved

#2699 Support parameters in InferInput and InferOutput
  python/kserve/kserve/protocol/infer_type.py
Labels: lgtm, approved

#2707 Add cherry pick github action
  .github/workflows/cherry-pick.yml
Labels: lgtm, approved

#2713 update kserve model method signatures in docs
  docs/samples/explanation/aif/germancredit/server/model.py
  docs/samples/explanation/aix/mnist/rfserver/rfserver/model.py
  docs/samples/kafka/image_transformer/image_transformer.py
  docs/samples/v1beta1/transformer/feast/driver_transformer/driver_transformer.py
  docs/samples/v1beta1/transformer/feast/setup.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/bert_transformer_v2/bert_transformer.py
  docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/setup.py
Labels: lgtm, approved

#2709 Add check for adding gpu tag suffix when image field is specified
  pkg/controller/v1beta1/inferenceservice/utils/utils.go
  pkg/utils/utils.go
Labels: lgtm, approved, release-0.10

#2716 Adding token for cherry-pick action.
  .github/workflows/cherry-pick.yml
Labels: lgtm, approved

#2701 update outlier detection example
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10_outlier.ipynb
  docs/samples/outlier-detection/alibi-detect/cifar10/cifar10od.yaml
  docs/samples/outlier-detection/alibi-detect/cifar10/requirements_notebook.txt
Labels: lgtm, approved
