Repository kserve/kserve, pull requests merged in 2023-10, with the labels that each got.

#3163 Removing update op from pod-mutator webhook
  charts/kserve-resources/templates/webhookconfiguration.yaml
  config/webhook/manifests.yaml
  pkg/webhook/admission/pod/mutator.go
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#3164 Fix quick install script
  hack/quick_install.sh
Labels: lgtm, approved

#3165 Fix self-signed-ca installation
  Makefile
  config/default/kustomization.yaml
  config/overlays/kubeflow/kustomization.yaml
  hack/self-signed-ca.sh
Labels: lgtm, approved, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#3172 Add S3_VERIFY_SSL to storage.py for S3
  python/kserve/kserve/storage/storage.py
Labels: lgtm, approved

#3086 Allow disabling creation of the HPA in raw deployment mode
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/constants/constants.go
  pkg/controller/v1beta1/inferenceservice/components/explainer.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/autoscaler/autoscaler_reconciler_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
Labels: lgtm, approved

#3167 Restrict workflow concurrency
  .github/workflows/agent-docker-publish.yml
  .github/workflows/alibiexplainer-docker-publish.yml
  .github/workflows/artexplainer-docker-publish.yml
  .github/workflows/cherry-pick.yml
  .github/workflows/custom-model-grpc-publish.yml
  .github/workflows/e2e-test.yml
  .github/workflows/go.yml
  .github/workflows/helm-publish.yml
  .github/workflows/kserve-controller-docker-publish.yml
  .github/workflows/lightgbm-docker-publish.yml
  .github/workflows/paddle-docker-publish.yml
  .github/workflows/pmml-docker-publish.yml
  .github/workflows/python-publish.yml
  .github/workflows/python-test.yml
  .github/workflows/qpext-docker-publish.yml
  .github/workflows/router-docker-publish.yml
  .github/workflows/scheduled-image-scan.yml
  .github/workflows/sklearnserver-docker-publish.yml
  .github/workflows/storage-initializer-docker-publisher.yml
  .github/workflows/tf2openapi-docker-publisher.yml
  .github/workflows/transformer-docker-publish.yml
  .github/workflows/xgbserver-docker-publisher.yml
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#3158 Refractor v1 vs. v2 endpoint unit tests in kserve/test/test_server.py…
  python/kserve/test/test_server.py
Labels: lgtm, approved

#3177 Fix runtime not found for triton due to wrong default protocolVersion
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  test/e2e/predictor/test_triton.py
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#3174 Make ModelServer to stop correctly when using more than 1 worker
  python/kserve/kserve/model_server.py
Labels: lgtm, approved

#3173 Added custom request timeout for inferencegraph.
  config/crd/serving.kserve.io_inferencegraphs.yaml
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/openapi_generated.go
  pkg/apis/serving/v1beta1/swagger.json
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
  python/kserve/docs/V1alpha1InferenceGraphSpec.md
  python/kserve/kserve/models/v1alpha1_inference_graph_spec.py
  test/crds/serving.kserve.io_inferenceservices.yaml
Labels: lgtm, approved

#3190 Fix serving runtime webhook cert namespace for kubeflow installation
  config/overlays/kubeflow/kustomization.yaml
  install/v0.11.1/kserve_kubeflow.yaml
Labels: lgtm, approved

#3188 Fix serving runtime webhook cert namespace for kubeflow installation
  config/default/kustomization.yaml
  config/overlays/kubeflow/kustomization.yaml
  install/v0.11.1/kserve_kubeflow.yaml
Labels: lgtm, approved

#3170 Add go security scan for PRs and set it up to run on a regular schedule
  .github/workflows/scheduled-go-security-scan.yml
  .github/workflows/scheduled-image-scan.yml
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#3194 RawDeployment support for Inference Graph
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
Labels: lgtm, approved

#3198 Revert "RawDeployment support for Inference Graph"
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/inferencegraph/controller.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig.go
  pkg/controller/v1alpha1/inferencegraph/raw_ig_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
Labels: lgtm, approved

#3189 Verify codegen in CI
  .github/workflows/verify-codegen.yml
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, hacktoberfest, hacktoberfest2023

#3130 Fix knative config-defaults values overrided by kserve
  pkg/controller/v1alpha1/inferencegraph/controller_test.go
  pkg/controller/v1alpha1/inferencegraph/knative_reconciler.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/raw/raw_kube_reconciler.go
Labels: lgtm, approved

#3209 Fix qpext metrics port
  pkg/constants/constants.go
Labels: lgtm, approved

#3210 [release-0.11] Fix qpext metrics port (#3209)
  pkg/constants/constants.go
Labels: lgtm, approved

#3214 docs: fix some typos
  docs/samples/explanation/aix/Fetch_20newsgroups/README.md
  docs/samples/fluid/docker/models.py
  docs/samples/graph/README.md
  docs/samples/v1beta1/torchserve/v2/bert/sequence_classification/Transformer_kserve_handler.py
Labels: lgtm, approved
