Repository kserve/kserve, pull requests merged in 2024-10, with the labels that each got.

#3860 Cluster local model controller
  .github/workflows/e2e-test.yml
  .github/workflows/kserve-localmodel-controller-docker-publish.yml
  .gitignore
  Makefile
  charts/kserve-crd/templates/serving.kserve.io_clusterlocalmodels.yaml
  charts/kserve-crd/templates/serving.kserve.io_localmodelnodegroups.yaml
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/clusterrole.yaml
  charts/kserve-resources/templates/configmap.yaml
  charts/kserve-resources/templates/localmodel/deployment.yaml
  charts/kserve-resources/templates/localmodel/namespace.yaml
  charts/kserve-resources/templates/localmodel/role.yaml
  charts/kserve-resources/templates/localmodel/role_binding.yaml
  charts/kserve-resources/templates/localmodel/service_account.yaml
  charts/kserve-resources/values.yaml
  cmd/localmodel/main.go
  config/configmap/inferenceservice.yaml
  config/crd/full/kustomization.yaml
  config/crd/kustomization.yaml
  config/crd/minimal/kustomization.yaml
  config/default/kustomization.yaml
  config/default/localmodel_manager_image_patch.yaml
  config/localmodels/kustomization.yaml
  config/localmodels/manager.yaml
  config/overlays/development/kustomization.yaml
  config/overlays/test/kustomization.yaml
  config/overlays/test/localmodel_manager_image_patch.yaml
  config/rbac/kustomization.yaml
  config/rbac/localmodel/role.yaml
  config/rbac/localmodel/role_binding.yaml
  config/rbac/localmodel/service_account.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/image_patch_dev.sh
  localmodel.Dockerfile
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/localmodel/controller.go
  pkg/controller/v1alpha1/localmodel/controller_test.go
  pkg/controller/v1alpha1/localmodel/suite_test.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  python/kserve/docs/V1beta1LocalModelConfig.md
  python/kserve/kserve/models/__init__.py
  python/kserve/kserve/models/v1beta1_local_model_config.py
  python/kserve/test/test_v1beta1_local_model_config.py
  test/crds/serving.kserve.io_inferenceservices.yaml
  test/scripts/aws/run-e2e-tests.sh
  test/scripts/gh-actions/build-images.sh
  test/scripts/gh-actions/update-test-overlays.sh
Labels: lgtm, approved

#3970 Prepare for 0.14.0-rc1release and automate sync process
  Makefile
  charts/kserve-crd-minimal/Chart.yaml
  charts/kserve-crd-minimal/README.md
  charts/kserve-crd/Chart.yaml
  charts/kserve-crd/README.md
  charts/kserve-crd/templates/serving.kserve.io_clusterlocalmodels.yaml
  charts/kserve-crd/templates/serving.kserve.io_clusterservingruntimes.yaml
  charts/kserve-crd/templates/serving.kserve.io_clusterstoragecontainers.yaml
  charts/kserve-crd/templates/serving.kserve.io_inferencegraphs.yaml
  charts/kserve-crd/templates/serving.kserve.io_inferenceservices.yaml
  charts/kserve-crd/templates/serving.kserve.io_localmodelnodegroups.yaml
  charts/kserve-crd/templates/serving.kserve.io_servingruntimes.yaml
  charts/kserve-crd/templates/serving.kserve.io_trainedmodels.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/addressable_resolver_role.yaml
  charts/kserve-resources/templates/clusterrole.yaml
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.14.0-rc1/kserve-cluster-resources.yaml
  install/v0.14.0-rc1/kserve.yaml
  install/v0.14.0-rc1/kserve_kubeflow.yaml
  python/VERSION
  python/aiffairness/poetry.lock
  python/aiffairness/pyproject.toml
  python/artexplainer/poetry.lock
  python/artexplainer/pyproject.toml
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_tokenizer/poetry.lock
  python/custom_tokenizer/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/lgbserver/pyproject.toml
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/sklearnserver/pyproject.toml
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/error_404_isvc/pyproject.toml
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/pyproject.toml
  python/xgbserver/poetry.lock
  python/xgbserver/pyproject.toml
  release/RELEASE_PROCESS_v2.md
Labels: lgtm, approved

#3924 Fix update-openapigen.sh that can be executed from kserve dir
  go.sum
  hack/update-openapigen.sh
Labels: approved

#3645 Add python 3.12 support and remove python 3.8 support
  .github/workflows/python-test.yml
  python/aiffairness/poetry.lock
  python/aiffairness/pyproject.toml
  python/artexplainer/poetry.lock
  python/artexplainer/pyproject.toml
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_tokenizer/poetry.lock
  python/custom_tokenizer/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/kserve/test/test_inference_client.py
  python/lgbserver/poetry.lock
  python/lgbserver/pyproject.toml
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/sklearnserver/pyproject.toml
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/error_404_isvc/pyproject.toml
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/pyproject.toml
  python/xgbserver/poetry.lock
  python/xgbserver/pyproject.toml
  test/e2e/qpext/test_qpext.py
Labels: lgtm, approved

#3670 Fix Kubernetes Doc Links
  pkg/apis/serving/v1beta1/component.go
Labels: lgtm, approved

#3981 Fix kserve local testing env
  pkg/controller/v1alpha1/inferencegraph/suite_test.go
  pkg/controller/v1alpha1/localmodel/suite_test.go
  pkg/controller/v1alpha1/trainedmodel/suite_test.go
  pkg/controller/v1beta1/inferenceservice/suite_test.go
  pkg/credentials/credentials_suite_test.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  pkg/testing/envtest_setup.go
  pkg/webhook/admission/pod/suite_test.go
  python/kserve/docs/V1beta1ComponentExtensionSpec.md
  python/kserve/docs/V1beta1ExplainerSpec.md
  python/kserve/docs/V1beta1PredictorSpec.md
  python/kserve/docs/V1beta1TransformerSpec.md
  python/kserve/kserve/models/v1beta1_component_extension_spec.py
  python/kserve/kserve/models/v1beta1_explainer_spec.py
  python/kserve/kserve/models/v1beta1_predictor_spec.py
  python/kserve/kserve/models/v1beta1_transformer_spec.py
Labels: lgtm

#3979 Add a flag for automount serviceaccount token
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/configmap.yaml
  charts/kserve-resources/values.yaml
  config/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/controller/v1alpha1/localmodel/controller_test.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  python/kserve/docs/V1beta1SecurityConfig.md
  python/kserve/kserve/models/__init__.py
  python/kserve/kserve/models/v1beta1_security_config.py
  python/kserve/test/test_v1beta1_security_config.py
Labels: lgtm, approved

#3985 Do not set security context on the storage initializer from user container
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/clusterstoragecontainer.yaml
  charts/kserve-resources/values.yaml
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: lgtm

#3669 Fix: Headers passing for v1/v2 endpoints
  python/custom_model/model.py
  python/custom_transformer/model.py
  python/huggingfaceserver/tests/test_model.py
  python/kserve/kserve/inference_client.py
  python/kserve/kserve/model.py
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/kserve/protocol/rest/v1_endpoints.py
  python/kserve/kserve/protocol/rest/v2_endpoints.py
  python/kserve/test/test_dataplane.py
  test/e2e/predictor/test_response_headers.py
Labels: approved

#3774 Torchserve security update
  docs/samples/v1beta1/torchserve/v1/gpu.yaml
  docs/samples/v1beta1/torchserve/v1/torchserve.yaml
  docs/samples/v1beta1/torchserve/v2/mnist.yaml
  docs/samples/v1beta1/torchserve/v2/mnist_gpu.yaml
Labels: lgtm, hold

#3994 Pin ubuntu 22.04 for minikube setup action
  .github/workflows/e2e-test.yml
Labels: lgtm, approved

#3988 KServe 0.14 Release
  charts/kserve-crd-minimal/Chart.yaml
  charts/kserve-crd-minimal/README.md
  charts/kserve-crd/Chart.yaml
  charts/kserve-crd/README.md
  charts/kserve-crd/templates/serving.kserve.io_clusterservingruntimes.yaml
  charts/kserve-crd/templates/serving.kserve.io_inferenceservices.yaml
  charts/kserve-crd/templates/serving.kserve.io_servingruntimes.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/README.md
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.14.0/kserve-cluster-resources.yaml
  install/v0.14.0/kserve.yaml
  install/v0.14.0/kserve_kubeflow.yaml
  python/VERSION
  python/aiffairness/poetry.lock
  python/aiffairness/pyproject.toml
  python/artexplainer/poetry.lock
  python/artexplainer/pyproject.toml
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_tokenizer/poetry.lock
  python/custom_tokenizer/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/lgbserver/pyproject.toml
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/sklearnserver/pyproject.toml
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/error_404_isvc/pyproject.toml
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/pyproject.toml
  python/xgbserver/poetry.lock
  python/xgbserver/pyproject.toml
Labels: lgtm

#4001 bump to vllm0.6.3
  python/huggingface_server.Dockerfile
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
Labels: lgtm

#4000 Feature: Add hf transfer
  pkg/credentials/hf/hf_secret.go
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
Labels: lgtm, approved

#4005 Update quick install script
  hack/quick_install.sh
Labels: lgtm, approved

#4008 Reduce E2Es dependency on CI environment (2)
  .github/workflows/e2e-test.yml
  test/e2e/common/utils.py
  test/e2e/custom/test_custom_model_grpc.py
  test/e2e/custom/test_ray.py
  test/e2e/predictor/test_grpc.py
  test/e2e/predictor/test_raw_deployment.py
  test/e2e/predictor/test_response_headers.py
Labels: lgtm, approved

#4015 Allow GCS to download single file
  python/kserve/kserve/storage/storage.py
  python/kserve/kserve/storage/test/test_gcs_storage.py
  python/storage-initializer/scripts/model.joblib
  test/e2e/predictor/test_xgboost.py
Labels: lgtm
