Repository kserve/kserve, pull requests merged in 2024-12, with the labels that each got.

#3993 introduce the prepare-for-release.sh script
  Makefile
  docs/samples/explanation/alibi/alibiexplainer/pyproject.toml
  hack/prepare-for-release.sh
  release/RELEASE_PROCESS_v2.md
Labels: lgtm, approved

#4098 Storage containers typo fix for Huggingface Storage type
  charts/kserve-resources/templates/clusterstoragecontainer.yaml
  config/storagecontainers/default.yaml
Labels: lgtm, approved

#4099 Support datetime object serialization in v1/v2 response
  python/kserve/kserve/protocol/infer_type.py
  python/kserve/kserve/protocol/rest/v1_endpoints.py
  python/kserve/kserve/utils/numpy_codec.py
  python/kserve/test/test_server.py
Labels: lgtm

#4093 Replace klog with klog/v2
  cmd/spec-gen/main.go
  go.mod
  go.sum
  pkg/webhook/admission/pod/suite_test.go
Labels: lgtm, approved

#4066 Add exception handling and logging for grpc server
  python/aiffairness/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_tokenizer/poetry.lock
  python/custom_transformer/poetry.lock
  python/huggingfaceserver/poetry.lock
  python/kserve/kserve/protocol/grpc/interceptors.py
  python/kserve/kserve/protocol/grpc/server.py
  python/kserve/kserve/protocol/grpc/servicer.py
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/xgbserver/poetry.lock
Labels: lgtm, approved

#4105 Update ClusterLocalModel to LocalModelCache
  Makefile
  charts/kserve-crd-minimal/templates/serving.kserve.io_localmodelcaches.yaml
  charts/kserve-crd/templates/serving.kserve.io_localmodelcaches.yaml
  charts/kserve-resources/templates/clusterrole.yaml
  charts/kserve-resources/templates/localmodel/role.yaml
  config/crd/full/kustomization.yaml
  config/crd/full/serving.kserve.io_localmodelcaches.yaml
  config/crd/kustomization.yaml
  config/crd/minimal/kustomization.yaml
  config/crd/minimal/serving.kserve.io_localmodelcaches.yaml
  config/rbac/localmodel/role.yaml
  config/rbac/role.yaml
  hack/generate-install.sh
  pkg/apis/serving/v1alpha1/local_model_cache_status.go
  pkg/apis/serving/v1alpha1/local_model_cache_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/clusterlocalmodel.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_clusterlocalmodel.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_localmodelcache.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/localmodelcache.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/serving/v1alpha1/interface.go
  pkg/client/informers/externalversions/serving/v1alpha1/localmodelcache.go
  pkg/client/listers/serving/v1alpha1/clusterlocalmodel.go
  pkg/client/listers/serving/v1alpha1/expansion_generated.go
  pkg/client/listers/serving/v1alpha1/localmodelcache.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/localmodel/controller.go
  pkg/controller/v1alpha1/localmodel/controller_test.go
  pkg/controller/v1alpha1/localmodelnode/controller.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  python/kserve/docs/V1alpha1LocalModelCache.md
  python/kserve/docs/V1alpha1LocalModelCacheList.md
  python/kserve/docs/V1alpha1LocalModelCacheSpec.md
  python/kserve/kserve/models/__init__.py
  python/kserve/kserve/models/v1alpha1_local_model_cache.py
  python/kserve/kserve/models/v1alpha1_local_model_cache_list.py
  python/kserve/kserve/models/v1alpha1_local_model_cache_spec.py
  python/kserve/test/test_v1alpha1_local_model_cache.py
  python/kserve/test/test_v1alpha1_local_model_cache_list.py
  python/kserve/test/test_v1alpha1_local_model_cache_spec.py
  test/crds/serving.kserve.io_inferenceservices.yaml
  test/crds/serving.kserve.io_localmodelcaches.yaml
Labels: lgtm, approved

#4106 Fix LocalModelCache controller reconciles deleted resource
  .github/workflows/e2e-test.yml
  pkg/controller/v1alpha1/localmodel/controller.go
  pkg/controller/v1alpha1/localmodel/controller_test.go
Labels: approved

#4003 Fix InferenceService state when Predictor pod in CrashLoopBackOff
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/apis/serving/v1beta1/inference_service_status_test.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
Labels: lgtm

#4102 LocalModelCache Admission Webhook
  charts/kserve-resources/templates/webhookconfiguration.yaml
  cmd/manager/main.go
  config/default/kustomization.yaml
  config/default/localmodelcache_validatingwebhook_cainjection_patch.yaml
  config/webhook/manifests.yaml
  go.sum
  hack/self-signed-ca.sh
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler_test.go
  pkg/webhook/admission/localmodelcache/local_model_cache_validation.go
  pkg/webhook/admission/localmodelcache/local_model_cache_validation_test.go
Labels: lgtm, approved

#4111 Add namespace to localmodel and localmodelnode ServiceAccount helm chart
  charts/kserve-resources/templates/localmodel/service_account.yaml
  charts/kserve-resources/templates/localmodelnode/service_account.yaml
Labels: lgtm, approved

#4123 [release-0.14]Support datetime object serialization for v1/v2 response
  go.sum
  python/kserve/kserve/protocol/infer_type.py
  python/kserve/kserve/protocol/rest/v1_endpoints.py
  python/kserve/kserve/utils/numpy_codec.py
  python/kserve/test/test_server.py
Labels: lgtm

#4055 Update max_model_len calculation and fixup encoder pooling
  python/huggingfaceserver/huggingfaceserver/utils.py
Labels: lgtm, approved

#4072 chore: use patch instead of update for finalizer changes
  go.sum
  pkg/controller/v1beta1/inferenceservice/controller.go
Labels: lgtm

#4131 Fix isvc role localmodelcache permission
  charts/kserve-resources/templates/clusterrole.yaml
  config/overlays/kubeflow/kustomization.yaml
  config/rbac/role.yaml
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/controller/v1beta1/inferenceservice/controller.go
Labels: lgtm, approved

#4095 Detect missing models and redownload models
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/configmap.yaml
  charts/kserve-resources/values.yaml
  config/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/controller/v1alpha1/localmodelnode/controller.go
  pkg/controller/v1alpha1/localmodelnode/controller_test.go
  pkg/controller/v1alpha1/localmodelnode/file_utils.go
  pkg/controller/v1alpha1/localmodelnode/suite_test.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  python/kserve/docs/V1beta1LocalModelConfig.md
  python/kserve/kserve/models/v1beta1_local_model_config.py
Labels: lgtm, approved

#4134 Allow multiple node groups in the model cache CR
  config/crd/full/serving.kserve.io_localmodelcaches.yaml
  hack/violation_exceptions.list
  pkg/apis/serving/v1alpha1/local_model_cache_types.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serving/v1beta1/inference_service_defaults_test.go
  pkg/controller/v1alpha1/localmodel/controller.go
  pkg/controller/v1alpha1/localmodel/controller_test.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  pkg/webhook/admission/localmodelcache/local_model_cache_validation_test.go
  python/kserve/docs/V1alpha1LocalModelCacheSpec.md
  python/kserve/kserve/models/v1alpha1_local_model_cache_spec.py
  python/kserve/test/test_v1alpha1_local_model_cache.py
  python/kserve/test/test_v1alpha1_local_model_cache_list.py
  python/kserve/test/test_v1alpha1_local_model_cache_spec.py
  test/crds/serving.kserve.io_inferenceservices.yaml
  test/crds/serving.kserve.io_localmodelcaches.yaml
Labels: lgtm, approved

#4118 Annotation to disable model cache
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/constants/constants.go
Labels: lgtm, approved

#4140 Clean up jobs in model cache agent
  go.sum
  pkg/controller/v1alpha1/localmodelnode/controller.go
  pkg/controller/v1alpha1/localmodelnode/controller_test.go
Labels: lgtm

#4142 Ensure Model root folder exists
  pkg/controller/v1alpha1/localmodelnode/controller.go
  pkg/controller/v1alpha1/localmodelnode/controller_test.go
  pkg/controller/v1alpha1/localmodelnode/file_utils.go
Labels: lgtm

#4141 Add NodeGroup Name Into PVC Name
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/constants/constants.go
  pkg/controller/v1alpha1/localmodel/controller.go
  pkg/controller/v1alpha1/localmodel/controller_test.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
  python/huggingface_server_cpu_openvino.Dockerfile
Labels: lgtm, approved

#4143 Make LocalModel Agent reconcilation frequency configurable
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/configmap.yaml
  charts/kserve-resources/values.yaml
  config/configmap/inferenceservice.yaml
  pkg/apis/serving/v1beta1/configmap.go
  pkg/controller/v1alpha1/localmodelnode/controller.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  python/kserve/docs/V1beta1LocalModelConfig.md
  python/kserve/kserve/models/v1beta1_local_model_config.py
Labels: lgtm, approved

#4109 Remove deepcopy-gen in favour of controller-gen
  pkg/apis/serving/v1alpha1/doc.go
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/apis/serving/v1alpha1/inference_graph_validation.go
  pkg/apis/serving/v1alpha1/local_model_cache_types.go
  pkg/apis/serving/v1alpha1/local_model_node_group_types.go
  pkg/apis/serving/v1alpha1/local_model_node_types.go
  pkg/apis/serving/v1alpha1/servingruntime_types.go
  pkg/apis/serving/v1alpha1/storage_container_types.go
  pkg/apis/serving/v1alpha1/trained_model.go
  pkg/apis/serving/v1alpha1/trainedmodel_webhook.go
  pkg/apis/serving/v1beta1/doc.go
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_defaults.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/v1beta1.go
  pkg/webhook/admission/localmodelcache/local_model_cache_validation.go
Labels: lgtm, approved

#4127 Add ability to set annotations on controll/webhook service and expose metrics bind port and address in helm chart
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/deployment.yaml
  charts/kserve-resources/templates/service.yaml
  charts/kserve-resources/values.yaml
Labels: lgtm

#4148 Remove redundant namespace yaml
  charts/kserve-resources/templates/localmodelnode/namespace.yaml
Labels: lgtm, approved

#4150 Fix Localmodel agent build
  .github/workflows/e2e-test.yml
  .github/workflows/kserve-localmodel-agent-docker-publish.yml
  localmodel-agent.Dockerfile
  test/scripts/gh-actions/build-images.sh
Labels: lgtm

#4116 Fix model server fails to gracefully shutdown
  python/kserve/kserve/model_server.py
  python/kserve/kserve/protocol/grpc/server.py
  python/kserve/kserve/protocol/rest/server.py
  python/kserve/test/conftest.py
  python/kserve/test/test_inference_client.py
  python/kserve/test/test_server.py
Labels: lgtm, approved

#4152 Ensure root model directory exists and add protection for jobs created
  Makefile
  pkg/controller/v1alpha1/localmodel/controller.go
  pkg/controller/v1alpha1/localmodelnode/controller.go
  pkg/controller/v1alpha1/localmodelnode/file_utils.go
Labels: lgtm, approved

#4155 Generate 0.14.1 release
  charts/kserve-crd-minimal/Chart.yaml
  charts/kserve-crd-minimal/README.md
  charts/kserve-crd/Chart.yaml
  charts/kserve-crd/README.md
  charts/kserve-crd/templates/serving.kserve.io_localmodelcaches.yaml
  charts/kserve-resources/Chart.yaml
  charts/kserve-resources/README.md
  charts/kserve-resources/values.yaml
  hack/generate-install.sh
  hack/quick_install.sh
  install/v0.14.1/kserve-cluster-resources.yaml
  install/v0.14.1/kserve.yaml
  install/v0.14.1/kserve_kubeflow.yaml
  pkg/controller/v1alpha1/localmodelnode/controller.go
  python/VERSION
  python/aiffairness/poetry.lock
  python/aiffairness/pyproject.toml
  python/artexplainer/poetry.lock
  python/artexplainer/pyproject.toml
  python/custom_model/poetry.lock
  python/custom_model/pyproject.toml
  python/custom_tokenizer/poetry.lock
  python/custom_tokenizer/pyproject.toml
  python/custom_transformer/poetry.lock
  python/custom_transformer/pyproject.toml
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/lgbserver/pyproject.toml
  python/paddleserver/poetry.lock
  python/paddleserver/pyproject.toml
  python/pmmlserver/poetry.lock
  python/pmmlserver/pyproject.toml
  python/sklearnserver/poetry.lock
  python/sklearnserver/pyproject.toml
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/error_404_isvc/pyproject.toml
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/pyproject.toml
  python/xgbserver/poetry.lock
  python/xgbserver/pyproject.toml
Labels: lgtm, approved

#4121 Enable transformer deeper readiness check tests
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/kserve/utils/inference_client_factory.py
  python/kserve/test/test_dataplane.py
  python/kserve/test/test_inference_client_factory.py
Labels: lgtm, approved

#4147 Update HuggingFace server dependencies versions
  python/huggingface_server.Dockerfile
  python/huggingface_server_cpu_openvino.Dockerfile
  python/huggingfaceserver/huggingfaceserver/__main__.py
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
  python/huggingfaceserver/tests/test_vllm_model.py
Labels: lgtm, approved

#4137 Add workflow for verifying go mod
  .github/workflows/golangci-lint.yml
Labels: lgtm, approved

#4113 Fix for CVE-2024-52304 - aiohttp upgrade
  python/custom_model/poetry.lock
  python/huggingfaceserver/poetry.lock
  python/kserve/poetry.lock
Labels: lgtm
