Repository kserve/kserve, pull requests merged in 2025-06, with the labels that each got.

#4507 Upgrade vLLM to v0.9.0.1
  python/aiffairness/poetry.lock
  python/artexplainer/poetry.lock
  python/custom_model/poetry.lock
  python/custom_tokenizer/poetry.lock
  python/custom_transformer/poetry.lock
  python/huggingface_server.Dockerfile
  python/huggingface_server_cpu.Dockerfile
  python/huggingfaceserver/poetry.lock
  python/huggingfaceserver/pyproject.toml
  python/huggingfaceserver/tests/setup_vllm.sh
  python/kserve/poetry.lock
  python/kserve/pyproject.toml
  python/lgbserver/poetry.lock
  python/paddleserver/poetry.lock
  python/pmmlserver/poetry.lock
  python/sklearnserver/poetry.lock
  python/test_resources/graph/error_404_isvc/poetry.lock
  python/test_resources/graph/success_200_isvc/poetry.lock
  python/xgbserver/poetry.lock
Labels: lgtm, approved

#4327 Fix pss restricted warnings
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/localmodel/deployment.yaml
  charts/kserve-resources/values.yaml
  config/localmodelnodes/manager.yaml
  config/localmodels/manager.yaml
  config/manager/manager.yaml
Labels: lgtm, hold

#4514 [Bug] Fixes error in trace logging
  python/huggingfaceserver/huggingfaceserver/request_logger.py
Labels: lgtm, approved

#4455 Stop and resume a model [Raw Deployment]
  pkg/apis/serving/v1beta1/inference_service.go
  pkg/apis/serving/v1beta1/inference_service_status.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/deployment/deployment_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/hpa/hpa_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/kube_ingress_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/otel/otel_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/service/service_reconciler.go
  pkg/utils/utils.go
Labels: lgtm, approved

#4218 Allow to set custom timeouts for `InferenceGraph` router
  cmd/router/main.go
  cmd/router/main_test.go
  config/crd/full/serving.kserve.io_inferencegraphs.yaml
  pkg/apis/serving/v1alpha1/inference_graph.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  python/kserve/docs/V1alpha1InfereceGraphRouterTimeouts.md
  python/kserve/docs/V1alpha1InferenceGraphSpec.md
  python/kserve/kserve/models/__init__.py
  python/kserve/kserve/models/v1alpha1_inferece_graph_router_timeouts.py
  python/kserve/kserve/models/v1alpha1_inference_graph_spec.py
  python/kserve/test/test_v1alpha1_inferece_graph_router_timeouts.py
  test/crds/serving.kserve.io_all_crds.yaml
Labels: lgtm, approved, ok-to-test

#4492 feat: support remote storage URI injection for serving runtimes
  pkg/constants/constants.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: lgtm, approved

#4522 [API] Define LLMInferenceService and LLMInferenceServiceConfig types and CRDs
  charts/kserve-crd-minimal/templates/serving.kserve.io_llminferenceserviceconfigs.yaml
  charts/kserve-crd-minimal/templates/serving.kserve.io_llminferenceservices.yaml
  config/crd/full/serving.kserve.io_clusterservingruntimes.yaml
  config/crd/full/serving.kserve.io_clusterstoragecontainers.yaml
  config/crd/full/serving.kserve.io_inferenceservices.yaml
  config/crd/full/serving.kserve.io_llminferenceserviceconfigs.yaml
  config/crd/full/serving.kserve.io_llminferenceservices.yaml
  config/crd/full/serving.kserve.io_servingruntimes.yaml
  config/crd/minimal/serving.kserve.io_llminferenceserviceconfigs.yaml
  config/crd/minimal/serving.kserve.io_llminferenceservices.yaml
  go.mod
  go.sum
  pkg/apis/serving/v1alpha1/llm_inference_service_types.go
  pkg/apis/serving/v1alpha1/v1alpha1.go
  pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  pkg/client/informers/externalversions/serving/v1alpha1/clusterservingruntime.go
  pkg/client/informers/externalversions/serving/v1alpha1/clusterstoragecontainer.go
  pkg/client/informers/externalversions/serving/v1alpha1/inferencegraph.go
  pkg/client/informers/externalversions/serving/v1alpha1/localmodelcache.go
  pkg/client/informers/externalversions/serving/v1alpha1/localmodelnode.go
  pkg/client/informers/externalversions/serving/v1alpha1/localmodelnodegroup.go
  pkg/client/informers/externalversions/serving/v1alpha1/servingruntime.go
  pkg/client/informers/externalversions/serving/v1alpha1/trainedmodel.go
  pkg/client/informers/externalversions/serving/v1beta1/inferenceservice.go
  pkg/openapi/openapi_generated.go
  pkg/openapi/swagger.json
  python/kserve/docs/V1alpha1LLMInferenceService.md
  python/kserve/docs/V1alpha1LLMInferenceServiceConfig.md
  python/kserve/docs/V1alpha1LLMInferenceServiceConfigList.md
  python/kserve/docs/V1alpha1LLMInferenceServiceList.md
  python/kserve/docs/V1beta1CustomExplainer.md
  python/kserve/docs/V1beta1CustomPredictor.md
  python/kserve/docs/V1beta1CustomTransformer.md
  python/kserve/kserve/models/__init__.py
  python/kserve/kserve/models/v1alpha1_llm_inference_service.py
  python/kserve/kserve/models/v1alpha1_llm_inference_service_config.py
  python/kserve/kserve/models/v1alpha1_llm_inference_service_config_list.py
  python/kserve/kserve/models/v1alpha1_llm_inference_service_list.py
  python/kserve/kserve/models/v1beta1_custom_explainer.py
  python/kserve/kserve/models/v1beta1_custom_predictor.py
  python/kserve/kserve/models/v1beta1_custom_transformer.py
  python/kserve/test/test_v1alpha1_llm_inference_service.py
  python/kserve/test/test_v1alpha1_llm_inference_service_config.py
  python/kserve/test/test_v1alpha1_llm_inference_service_config_list.py
  python/kserve/test/test_v1alpha1_llm_inference_service_list.py
  test/crds/serving.kserve.io_all_crds.yaml
Labels: lgtm, llm-crd

#4534 Stop and Resume a transformer
  Makefile
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/controller/v1beta1/inferenceservice/components/transformer.go
  pkg/controller/v1beta1/inferenceservice/controller.go
  pkg/controller/v1beta1/inferenceservice/controller_test.go
  pkg/controller/v1beta1/inferenceservice/rawkube_controller_test.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/httproute_reconciler.go
Labels: lgtm, approved

#4441 Allow OCI for multi-node/multi-gpu
  config/runtimes/kserve-huggingfaceserver-multinode.yaml
  pkg/apis/serving/v1beta1/component.go
  pkg/apis/serving/v1beta1/inference_service_validation.go
  pkg/apis/serving/v1beta1/inference_service_validation_test.go
  pkg/controller/v1beta1/inferenceservice/components/predictor.go
  pkg/webhook/admission/pod/storage_initializer_injector.go
  pkg/webhook/admission/pod/storage_initializer_injector_test.go
Labels: lgtm

#4556 fix: unset clampMax and clampMin, since they are not for replicas
  pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler.go
  pkg/controller/v1beta1/inferenceservice/reconcilers/keda/keda_reconciler_test.go
Labels: lgtm, approved

#4526 Refactor KServe to use global context for PredictorConfig
  python/aiffairness/aifserver/__main__.py
  python/aiffairness/aifserver/model.py
  python/artexplainer/artserver/__main__.py
  python/artexplainer/artserver/model.py
  python/custom_tokenizer/transformer.py
  python/custom_transformer/model.py
  python/custom_transformer/model_grpc.py
  python/huggingfaceserver/huggingfaceserver/__main__.py
  python/huggingfaceserver/huggingfaceserver/encoder_model.py
  python/huggingfaceserver/tests/test_model.py
  python/kserve/kserve/__init__.py
  python/kserve/kserve/context.py
  python/kserve/kserve/model.py
  python/kserve/kserve/model_server.py
  python/kserve/kserve/predictor_config.py
  python/kserve/kserve/protocol/dataplane.py
  python/kserve/test/test_dataplane.py
  python/kserve/test/test_server.py
Labels: lgtm, approved

#4411 feat: refactor storage initializer resources configuration
  charts/kserve-resources/README.md
  charts/kserve-resources/templates/clusterstoragecontainer.yaml
  charts/kserve-resources/values.yaml
Labels: lgtm, approved
